### ISSUE TITLE
Semantics for priorities

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#1023]
The [explanation of the rationale behind assigning semantics to priority levels](https://httpwg.org/http-extensions/draft-ietf-httpbis-priority.html#why-do-urgencies-have-meanings) is not especially convincing.

The idea that we might have consistent labeling of priorities is something this shares with DSCP, but there the semantics are given more precise semantics than this document does for its levels.  If these semantics are to carry any weight, then it needs to be really clear what the client might expect a server to do with each different value.  It seems to me that if a server was to complete all requests at priority N before allocating anything other than opportunistic resources to N+1 then you get pretty much the semantics as described.  Priority 0 gets completed first, and 7 last.

The idea that different clients might share an understanding of different values is nice, but for that to work you need to trust that clients will label things similarly.  Right now, I don't see any incentive to do so.  If one implementation were to shift their priorities one higher or one lower, the effect probably wouldn't be any different.

I do strongly agree with the idea that the number of buckets needs to be small.  8 is a reasonable number on balance.  But the associated trappings need far stronger motivation.

Keep the last paragraph of that section though.  That concept deserves greater prominence in the document.  It does that by largely contradicting the argument for assigned semantics though.

**Comment by tombergan** [comment]
I mostly agree with Martin here, though if I'm reading the proposal correctly, this is mostly a dup of #1026? If there's no specification for merging client-generated and server-generated priorities, then there's no need to give semantics for each priority level.

> I do strongly agree with the idea that the number of buckets needs to be small.

What is your objection to using 16 or 32 bit integers (or perhaps 15 or 31, to reserve a bit for "incremental")?

The current number of levels is copied from Chrome's current implementation, which is subject to change. For example, we've considered deprioritizing iframes, which you might imagine doing by creating two sets of levels, one from the main frame and another for iframes. This needs 2x as many levels. A similar thing might happen for foreground vs background tabs, which needs another 2x. It would be unfortunate to prevent future experimentation like this.

**Comment by martinthomson** [comment]
Constraints on the system mean that there is a greater chance that people will implement this.  If you have 4G different levels, it's almost certain that implementations will be forced to quantize.  A smaller set might make some choices harder, but when the primary reason for inconsistent implementation of h2 priorities was that there were too many choices, that seems justified now.  I would rather start with a very small set of options at the first level and then offer augments (incremental, visible/not, whatever) that refine that.  The risk that we get a very flexible design that isn't consistently implemented remains one of my biggest concerns here. A very simple core that can be extended was the main reason I am hopeful that this approach could work.

**Comment by kazuho** [comment]
@martinthomson 
> The idea that different clients might share an understanding of different values is nice, but for that to work you need to trust that clients will label things similarly. Right now, I don't see any incentive to do so.

Maybe we should better point out that a small number of well-defined urgency levels gives you collaboration, using JavaScript API as an example in addition to client-server collaboration.

If we are to allow JavaScript code running on web browsers specify the priority of requests that that code generates, the priorities need to have a well-defined meaning so that those requests can be prioritized against the requests issued by the browser, regardless of the web browser being used.

**Comment by martinthomson** [comment]
For that to work reliably, you would have to eliminate any freedom that browsers might exercise in terms of using different priority markings on requests.  I'm not comfortable saying that.  That's the other part of the semantic thing.  I can understand 5>3, but as soon as we get to saying that all browsers need to mark image loads as X, then we lose the ability to apply a different strategy.

I realize that this doesn't help JS integrate into this very well.  The best I can offer is the possibility of an API that takes abstract concepts and interprets those through the lens of the browser's strategy.  Either that or having the browser compress or reinterpret the values provided by content.  The latter might only be necessary during page load and only when the requests share the same connection as default loads.

**Comment by kazuho** [comment]
@martinthomson I understand your concern, and I would point out that status quo provides a workaround.

The draft defines four levels: prerequisite, document, supplementary, background. I think that these four levels can be defined well.

The flexibility that we need is within the supplementary level. As you point out, it would be beneficial to give more (or less) precedence to some supplementary resources. That's why we provide the client three levels (i.e. 3 to 5), while 4 being the default of the supplementary level.

At the same time, a logic that is specific to the website (i.e. the server, but we might want to say that JavaScript on the browser-side also belongs to this category) might have better knowledge regarding how its resources should be prioritized. Therefore, we allow these site-specific logic to use levels 2 and 6 to intervene even harder.

I think that this design is on-balance a good middle ground in providing web browsers enough wiggle room, at the same time allowing site-specific logic to tune priorities in a browser-agnostic manner.

**Comment by tombergan** [comment]
Thinking about this some more, especially after @martinthomson's comment [here](https://github.com/httpwg/http-extensions/issues/1026#issuecomment-577456924), I have no objections to 8 levels. We can always add more later if there is a strong motivation for doing so.

> For that to work reliably, you would have to eliminate any freedom that browsers might exercise in terms of using different priority markings on requests. I'm not comfortable saying that.

I strongly agree with this.

This issue is merging with #1026, especially after [this comment](https://github.com/httpwg/http-extensions/issues/1026#issuecomment-577465626).

**Comment by kazuho** [comment]
I think this issue can be closed together with #1026.

**Comment by LPardue** [comment]
agreed, lets close this and open new issues for any specific problems with the document.
