### ISSUE TITLE
Uploading a new version of RFC6265bis.

### ISSUE THREAD

**Issue by mikewest** [httpwg/http-extensions#1031]
https://circleci.com/gh/httpwg/http-extensions/2785?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link shows that uploading a new -04 draft of RFC6265bis failed, possibly because I used the wrong email address when committing the new tag.

Can I delete and recreate the tag from the right account?

@reschke, @mnot: can one of you help me out? The docs are not exactly extensive... :)

**Comment by reschke** [comment]
That seems to be related to @martinthomson 's magic I'm not familiar with.

Did you try submitting directly through the IETF web page?

**Comment by mikewest** [comment]
I can do it manually, I'm sure; I just don't want to screw things up if the repo tries to resubmit on my behalf based on that tag.

**Comment by martinthomson** [comment]
> No such user: mkwst@chromium.org

The datatracker submission API requires not only that the email address you report here matches an active account (reasonable), but that the email is the *primary* email address on the account.  Note however that the email address in the document itself does not need to match this email address.  Indeed, you could claim my email address here and it would probably work fine (please don't, though I'm considering doing that just so that I stop getting questions about this).

I get the email address from the annotations on the tag.  So you can override the tag email address [as I do in QUIC](https://github.com/quicwg/base-drafts/blob/master/tag.sh) as a workaround.

This is a point of frustration for me.  The [trac issue](https://trac.tools.ietf.org/tools/ietfdb/ticket/2639) has been open for ages, blocked on a point of contention.

**Comment by mikewest** [comment]
Poked at it manually, and it looks like it went through successfully. I'll try to make sure I use `@google.com` for this repo going forward...

**Comment by mikewest** [comment]
To close the loop on this: I set my email address to one matching my IETF account in the local repo (via `git config --local user.email mail@huzzah.example`), and was able to use the tagging process successfully to publish an -05. Might be worth updating https://github.com/httpwg/http-extensions/blob/master/SUBMITTING.md? I'll send a PR.
