### ISSUE TITLE
field-name cardinality

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#108]
See:
  https://github.com/mnot/I-D/issues/132

**Comment by mnot** [comment]
My initial thought is that the difference in efficiency is going to be extremely minor, and it *might* be useful to specify a header field name more than once (especially if we do something interesting WRT or in #104.

@zwoop WDYT?

**Comment by zwoop** [comment]
It's implementation dependent. If you make a generic API for "Key", you'd likely have a callback function to access a header. You could cache this of course, but the naive solution would call multiple times, and that's where I think the inefficiencies could be.

I'm ok with ditching this. But, maybe also consider allowing #104 such that you don't have to repeat the header name? It seems pretty heavy weight to have to say 

    User-Agent=x; User-Agent=y; User-Agent=z

instead of something like

   User-Agent=x|y|z

**Comment by mnot** [comment]
The idea behind #104 is that `user-agent=(x|y|z)` is really easy to express:

> User-Agent; substr=x; substr=y; substr=z

... while `user-agent=(x|y) & z` is also reasonable:

> User-Agent; substr=x; substr=y, User-Agent; substr=z

... but note that `user-agent=(x&y) | z` is impossible with that syntax.

So, I think the question is whether this hits the use cases reasonably well; if not, we'll need to re-think.

(And yes, this really belongs in #104).

**Comment by mnot** [comment]
ping @martinthomson

**Comment by martinthomson** [comment]
I think that I'm happy with either outcome here.  I don't think that infinitely complex composition of logical is a goal we should be aiming for.  Overall, I think that I'd prefer to do:

> User-Agent;s=x;s=y

As `UA=~/(x|y)/` and treat that as sufficient for use cases.

The question I have for @zwoop would be, what is easier to implement?

1. reject duplicates
2. match against all duplicates

My intuition is that matching all is likely to be easiest because it means that the handling of `Key` can be stateless, which is nice.

**Comment by mnot** [comment]
> I don't think that infinitely complex composition of logical is a goal we should be aiming for

+1

**Comment by zwoop** [comment]
Yeah, just matching against all duplicates would be easier. It'd be nice'ish if people avoided it :).

**Comment by mnot** [comment]
If it's genuinely needed, we could confine the complexity one or two parameters (match, substr) rather than trying to make it generic.

**Comment by igrigorik** [comment]
So, just to make sure I understand what we're proposing here...

- `user-agent;s=x;s=y` - User-Agent =~ x | y.
- `user-agent;s=x;s=y, user-agent;s=z` - User-Agent =~ (x | y) & z
- `user-agent;s=x, cookie;s=y` - User-Agent =~ x & Cookie =~ y

Is that right? Are there any other expressions that are possible via current syntax? Here's an [interesting edge case](http://googlewebmastercentral.blogspot.com/2012/11/giving-tablet-users-full-sized-web.html) that may be worth considering:

> Although both Android smartphones and tablets will include the word “Android” in the user-agent string, only the user-agent of smartphones will include the word “Mobile”. 

In previous incarnation you could handle this with the `n` parameter: `Key: user-agent;s=android;n;s=mobi`. However, with current syntax I don't think it'd be possible to distinguish two entries, one for Android tablet vs smartphone?

**Comment by mnot** [comment]
Looking at the spec again, I think that currently we can't really use multiple instances of a parameter or a header as special syntax; it will complicate things too much. However, we *could* put it in the parameter values themselves.

E.g., right now, if you did:

> Key: user-agent;substr=android;substr=mobi

You'll end up with four "buckets":

1. UA contains both `android` and `mobi`
2. UA contains `android` but not `mobi`
3. UA contains `mobi` but not `android`
4. UA contains neither `android` nor `mobi`

... and it would behave the same way if you did:

> Key: user-agent;substr=android, user-agent;substr=mobi

So, I think that gives you the behaviour you want. 

We *could* add syntax to `match` and `substr` to avoid creating all of the permutations of buckets, e.g.,

> Key: user-agent;substr="android&mobi"

So you'd end up with just:

1. UA contains both `android` and `mobi`
2. Everything else

... but I very much wonder if that's worth the complexity. Thoughts?

**Comment by phluid61** [comment]
@mnot unless we could key on something horrible like `"ipad" or ("android" and not "mobi")` we'll never cover all the likely-to-be-requested use-cases; and the complexity for adding just a single operator is probably quite high (more operators ⇒ even more complexity), so the cost-benefit for it isn't great.

Having the multiple buckets gets us there eventually anyway, it just means GalaxyTab and iPad users wouldn't benefit from each others' requests. It's still better than `Vary:User-Agent`, though. (With the added benefit that it (hopefully) makes server operators think a bit more about what resources they send to whom, and why, and how they're cached.)

**Comment by martinthomson** [comment]
I think that until we provide a Turing complete language, someone will always come up with a use case that cannot be met by this mechanism.  That leads either to accepting that this is a doomed effort, or embracing the fact that this has some limitations.  I think that the latter is the only approach where we get something better than what we have today.

As @mnot notes, the current scheme does allow someone to do a full search.  The only concern being that you have less reuse in cases where the same response covers multiple points in the space.  If you test for "ipad", "android" and "mobi", then you have an 8 point space, with many of those point receiving the same content.  The only disappointing part is that the cache can't reuse from different buckets.

I think that the example @igrigorik described is a great one to look at.  If Chrome on the Nexus 7 and Safari on iPad were willing to change UA strings to include a clear piece of generic identification (like "tablet", just sayin'), then the situation improves because fewer buckets are needed to target content to particular devices (or classes of device).

**Comment by mnot** [comment]
Right. The goal of Key is not to entrench User-Agent sniffing; it's to enable better things like Client Hints, and make things like UA sniffing a bit more tolerable on the way to that.

**Comment by igrigorik** [comment]
I don't know the background of why "Tablet" is omitted for those devices, but (personally) I agree that we probably should deliver that token in the UA string.. and that we don't have to burden Key with a turing complete language. That said, the "OR" use case applies well beyond UA-sniffing.. e.g. keying on cookie header values, which is a common task for many applications.

re, https://github.com/httpwg/http-extensions/issues/108#issuecomment-156295114: interesting, I guess that approach covers most cases, but the fragmentation is painful. Instead of hijacking `&` inside of the value, would it make sense to define an operator that creates a composite key for all the sub-buckets? e.g. `Key: user-agent;substr=a;substr=b;xyz` where xyz is a token that indicates that all the buckets should resolve to same key? Although, I guess that reduces the whole space to an _and_...? Ugh.

_p.s. to be honest, I guess I didn't read the spec close enough, because my interpretation of substr was that substr=a;substr=b would result in same key if `a | b`._

**Comment by mnot** [comment]
(taking OR discussion back over to #104)

**Comment by mnot** [comment]
I think we can close this with no action; make sense?

**Comment by zwoop** [comment]
+1. I think #104 covers the concerns here.
