### ISSUE TITLE
Specify a default extension model

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#1129]
JSON ultimately acquired a *de-facto* model for extensions that effectively boils down to "ignore object fields you don't understand".  It looks a little like SH aims for some of the same approach, but maybe we can be more assertive about it.

Right now, the spec says "you should probably allow unknown things" in a couple of ways.  There is pretty strong encouragement regarding parameters in particular (#1128 does similar things for dictionaries).

But this could be the default mode rather than a suggestion.  That is, you say that *unless explicitly stated to the contrary* values in dictionaries and parameters for keys that are not specified MUST be ignored.

I think that is how people will build this in many cases, so it's not a stretch.  It might just take a little finesse to get the text right.

**Comment by phluid61** [comment]
Is it reasonable for this spec to impose a constraint like that? Like, SH doesn't care one way or another what the _values_ of dictionary keys are, only that they de/serialise consistently.

**Comment by phluid61** [comment]
Oh, having read #1128 I see what you're getting at. Sort of RFC 6919 levels of assertiveness. That's reasonable; if you want to apply it to parameters as well can't you just twiddle that proposal?

**Comment by martinthomson** [comment]
I would prefer to discuss first :) and then probably run with a follow-up.

**Comment by mnot** [comment]
It's worded like it is now because that's a constraint on the software that's consuming / producing the header for a specific purpose -- NOT a SH implementation (i.e., an implementer of this spec).

Generic SH software *can't* make such decisions, since it doesn't have knowledge of the domain-specific requirements. I don't think we can put 2119-style requirements on other specs like that (even if we can encourage certain patterns of use, which got us here).

**Comment by martinthomson** [comment]
Yeah, after looking at this more, I don't think that this is feasible.  For the reasons @mnot cited, but also from the perspecting of finding the right words.  After all, it ends up in 6919-land pretty fast.
