### ISSUE TITLE
Dictionary serialisation algo problem

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#1164]
@annevk noticed that [dictionary serialisation](https://httpwg.org/http-extensions/draft-ietf-httpbis-header-structure.html#ser-dictionary) is messed up.

I _think_ the fix is to indent the top-level 2-5 -- but I want to have a good look at it, compare to implementation, and I'd like others to verify, as I'm wary of making changes at this late stage.

Blame seems to be [this commit](https://github.com/httpwg/http-extensions/commit/4f3252bbc73844559bf7bc8891424de08531f7da), which I vaguely remember as being... surprising. That will teach me to slow down when something weird happens with Git...

**Comment by mnot** [comment]
Ping @bsdphk @phluid61 @clelland to look over my shoulder...

**Comment by annevk** [comment]
Looking at https://github.com/httpwg/http-extensions/pull/999/files the problem is that what became top-level 3 and 4 should have been steps inside top-level 2. Further changes have happened so now that applies to top-level 5 as well. (Top-level 2 itself seems good as that initiates the loop.)

(Other for each statements do appear to have correct indenting.)

**Comment by mnot** [comment]
Like that?
