### ISSUE TITLE
Add guidance for signing compressed headers

### ISSUE THREAD

**Issue by richanna** [httpwg/http-extensions#1191]
The draft should provide guidance on how to sign headers when RFC7541 is used. This guidance might be as simple as "sign the uncompressed header field value."

**Comment by LPardue** [comment]
I don't think that header compression (HPACK or QPACK) really needs to be mentioned. This is because the signature operates over header fields at the HTTP semantic level, this whereas compression is a version-specific aspect of serialization. An encoder takes a header or trailer field section and produces an output that is sent on the wire, the semantic layer has sort of left the control loop at this phase.

**Comment by ioggstream** [comment]
@richanna do you think we can close this according to Lucas' comment?
