### ISSUE TITLE
Expiration not needed

### ISSUE THREAD

**Issue by richanna** [httpwg/http-extensions#1194]
In many cases, putting the expiration of the signature into the hands of the signer opens up more options for failures than necessary.  Instead of the `expires`, any verifier can use the `created` field and an internal lifetime or offset to calculate expiration.  We should consider dropping the `expires` field.

**Comment by ioggstream** [comment]
The private key's owner must to be able to constraint the time validity of the signature because he has no ability to control on the internal lifetime of the verifier.




Dropping `expires` is dangerous.

**Comment by ioggstream** [comment]
Can we close this? :)

**Comment by OR13** [comment]
+1 to closing.

**Comment by JCapriotti** [comment]
How would one handle a scenario of the server requiring a short expiration? Is there a "middle-ground" of allowing `expires` to be invalid?

**Comment by jricher** [comment]
@JCapriotti that's exactly the motivation behind potentially dropping `expires`: the server can always decide to reject something that hasn't "expired" from the client's perspective just because it has a tighter set of requirements. `expires` is ultimately just a hint from the client to put an upper bound on the trustworthiness of a signature. I personally think we can do a better job of capturing that reality in the text, and put the right expectations around the different parameters.

**Comment by JCapriotti** [comment]
@jricher thanks for that perspective; basically, `expires` meaningless in my scenario since it is really the server that cares about the age of the signature.

**Comment by jricher** [comment]
Expiration is now marked as a non-required parameter that is from the perspective of the signer, and a verifier can do what it wants with this information.
