### ISSUE TITLE
Rebrand Signatures draft

### ISSUE THREAD

**Issue by jricher** [httpwg/http-extensions#1203]
The core function of the signatures draft is actually two-fold:

 - normalization of an HTTP request to create an input for a signature algorithm
 - attachment of a signature to an HTTP request

The first part is arguably the harder and more important part for why this is here in this WG, but it gets lost. What if we rebrand/rename the signatures draft?

"HTTP Message Normalization and Signing"

**Comment by jricher** [comment]
I think the reorganization of the draft that occurred several revisions ago makes this more clear, even without renaming it. The effort as a whole is known as "HTTP Message Signatures" so I don't think the rebranding is necessary anymore. @richanna any thoughts on rephrasing the introduction text to help this? Right now the most relevant paragraph is:

```
The signing mechanism described in this document consists of three parts:
 - A common nomenclature and canonicalization rule set for the different protocol elements and other components of HTTP messages, used to create the signature base.
 - Algorithms for generating and verifying signatures over HTTP message components using this signature base through application of cryptographic primitives.
  - A mechanism for attaching a signature and related metadata to an HTTP message, and for parsing attached signatures and metadata from HTTP messages.
```

**Comment by richanna** [comment]
I don't see a need to rebrand or rephrase anything in the introduction. Canonicalization is only relevant insofar as it is a necessary step in order to have stable, predictable inputs to signing/hashing functions, and I think that's clear from the current intro. Note also that we only care about canonicalization to a point – `Vary: Content-Language, User-Agent` is semantically equivalent to `Vary: User-Agent, Content-Language`, but will result in different signatures. So any further emphasis on canonicalization would be misleading, in my opinion.
