### ISSUE TITLE
What signals are subsumed by priority hints?

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#1216]
The last [email to the list](https://www.w3.org/mid/CALGR9obRjBSADN1KtKF6jvFVzNS1+JzaS0D0kCVKHKkd4sn+MQ@mail.gmail.com) makes it quite clear that request ordering is still a useful signal about priority that can be combined with the proposed new field.  That is, a server can use both explicit signals AND the order of requests to determine how it prioritizes responses.

(For this, we should probably clarify that it is stream ID - as an indicator of when the request was sent - and not when the request is received that matters.  That creates some interesting side effects for intermediaries though.  If a proxy receives requests out of order, but then forwards them in a different order, does that alter or suppress an otherwise useful signal?)

What isn't clear from the draft is how other signals that were historically used for prioritization might be either used in combination with explicit signals or are rendered invalid by the priority signal being present.  The obvious one is the h2 PRIORITY frame, which I assume has to be superseded.  

For instance, can a server that would ordinarily use media type to prioritize requests still do so when the priority signals don't indicate clear preferences?  Or does that server have to use only request order and explicit priority signals?

To be clear, this isn't about "have to" or "MUST", but more about what expectations we set for clients.

**Comment by LPardue** [comment]
> That is, a server can use both explicit signals AND the order of requests to determine how it prioritizes responses.

I think this is a good observation. Stream ordering's role in how a server allocates resources is a bit buried. I think promoting it will help towards some of this discussion, so lets make a PR to do that. Personally, I see that as a property of the client-server connection with no need to recommend forward action. IMO whether the server has to fetch the file from a remote backend or just read it from a cache, there is no one-size-fits all answer.

So far our approach has been to adopt HTTP/2's general "expressing priority is only a suggestion" sentiment.  HTTP/2 does, while explaining the mechanics of trees, state how an implementation should allocate resources to them. We describe expectations for urgency and increment without normative language, generally leaning to making no recommendations. 

> What isn't clear from the draft is how other signals that were historically used for prioritization might be either used in combination with explicit signals or are rendered invalid by the priority signal being present. The obvious one is the h2 PRIORITY frame, which I assume has to be superseded.

We do spend some text explaining the more complicated case in H2 where SETTINGS is needed to disable tree-priorities, and how a client might send both signals until then. A client could expect either scheme to take effect until then, maybe we can spell that out.

> For instance, can a server that would ordinarily use media type to prioritize requests still do so when the priority signals don't indicate clear preferences? Or does that server have to use only request order and explicit priority signals?

So https://httpwg.org/http-extensions/draft-ietf-httpbis-priority.html#merging does say something like "the client could be wrong because the server might have additional information". This is mainly to describe how to merge client and server extensible priority signals. But I think it holds true for something such as learning the content-type after receiving a request for "accept: image/*". I'm not sure how extensible priorities makes this situation any different than today.

Without formal definition of other signals, it seems hard to predict how an implementation might decide their order of importance. 
I wonder if this is issue is really identifying that 
I'm not so sure how to address "other signals" such as this because it doesn't seem covered by anything in HTTP/2, nor anywhere else really. We do provide text that explains how a proxy might respond to client and origin server extensible priority signals,

**Comment by jonglezb** [comment]
It would make sense to give examples of signals that the server could use to make a scheduling decision (and of course, stress that this is non-exhaustive). For instance: content length, media type, request order, but people might find other interesting signals.

Since the priority hints sent by the client are, well, just hints, the server should be allowed to override them if it has a good reason.

To some extent, section "Merging Client- and Server-Driven Parameters" already lists some signals _and_ allows the server to override the client hints. It would benefit from having a section to itself, dedicated to give guidance on how a server can make its scheduling decision. The "Merging" section would then just describe how to deal with the resulting inconsistencies between client and server priorities.
