### ISSUE TITLE
Nice to have guidance about reponding to priority signals when received

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#1232]
On https://lists.w3.org/Archives/Public/ietf-http-wg/2020JulSep/0063.html @ekinnear provided some feedback:

> For the document as a whole, we’ve gotten some feedback internally that it would be really nice if there were some (minimal, recommendation only) guidance as to how to respond to the priority signals when received. This wouldn’t be restrictive, as we’re really excited to experiment here and see what awesome results we can achieve, but having a baseline of “implement this as written and you’ll do okay” might be worth considering to increase the likelihood that we have a large group of generally-performant implementations.
> 
> An example here would be if two requests of the same urgency arrive back-to-back, the first with the incremental bit set and the second without. What gets sent when? What do you do next if a third request arrives with the incremental bit also set before the first is complete? There are lots and lots of permutations, but a general approach of handling new items coming in is something that I think we’ve all been imagining during discussions, but we haven’t really written it down explicitly. Internally, as we discussed with some folks new to the topic, we discovered that our imaginations of what to do in cases like these didn’t actually align as well as we thought.

I'm wondering how much this crosses over with https://github.com/httpwg/http-extensions/issues/1216, and how the editors might choose to address this feedback.

**Comment by guoye-zhang** [comment]
I think everyone is in agreement how it should work if everything is incremental (round-robin), or everything is non-incremental (sequential delivery). The question is when they are mixed at the same urgency level.

Our goal is that client can signal incremental whenever it make sense without worrying about regressions. Let's imagine two cases:

1. At the same urgency level, a huge non-incremental file download has started, then a small incremental resource is requested.
2. At the same urgency level, an incremental hanging GET is waiting for response, while a non-incremental file download is requested.

Many proposed solutions would severely regress these cases, delaying delivery of resources and keeping the connection idle.

**Comment by guoye-zhang** [comment]
A solution I want to propose to always perform round robin: For example, if there are 2 incremental loads and 3 non-incremental loads at the same urgency level, we perform round robin with 5 slots, 1 for each incremental load, and the remaining 3 for the first non-incremental load that has data available.

This generalizes the model and would be least disruptive in my opinion.

**Comment by LPardue** [comment]
If everything is served round-robin, then there is no point having an increment distinguisher. Or am I missing something?

**Comment by guoye-zhang** [comment]
Non-incremental stream is handled differently in my suggested round-robin scheme. I'll describe example above in more detail:

5 streams at the same urgency level. Stream 0, 1, 2 are non-incremental, stream 3, 4 are incremental.

We would have 5 slots, 3 of which is dedicated to the first non-incremental stream with data available, which is stream 0. Other two slots are for stream 3 and 4.

Let's stream 0 is blocked waiting for server application to generate data. All its 3 slots would be used by the next non-incremental stream in the queue which is stream 1.

This round-robin scheme degenerates into sequential delivery when all streams are non-incremental, and degenerates into regular round-robin when all streams are incremental.

**Comment by LPardue** [comment]
This sounds a bit like Pat Meenan's scheme, which we decided we didn't
need. It does differ in so far as being an implementation choice rather
than a signal.

When you say slots are you thinking time or bytes?

Would it be better to send incremental streams first?

**Comment by guoye-zhang** [comment]
> When you say slots are you thinking time or bytes?

In ideal conditions, time and bytes are equivalent. I think whatever definition of "slot" implementations are using in plain round robin scheme would work, so I don't have a preference.

> Would it be better to send incremental streams first?

That would work if it solves the second scenario I described above (incremental hanging GET followed by non-incremental file download).

However, it creates unfairness between incremental and non-incremental streams. I think the goal is that client can opt in to non-incremental whenever it makes sense. For example, if JSON responses can only be processed after received in full, they can be marked non-incremental; images can be rendered progressively, so they are incremental. But it's not our intention that images preempt JSON.

**Comment by guoye-zhang** [comment]
Where I'm coming from is that we own a client API, and we have convenience mode where you receive the entire response in one callback, and advanced mode where you receive data in chunks. We currently automatically opt in to non-incremental delivery when convenience mode is used. However, that wouldn't be safe if this causes any unfairness.

**Comment by kazuho** [comment]
Regarding how to handle mixture of incremental and non-incremental requests, I think there could be various strategies that can be adopted.

To give an example, as stated in https://github.com/kazuho/draft-kazuho-httpbis-priority/issues/94#issuecomment-572032461, when the server knows that the first few bytes of the responses are more important than the remainder (consider progressive JPEG), it makes sense for the server to send the first few bytes of those responses before other non-incremental responses.

Or, when the server knows that the response cannot be processed incrementally, there is no reason for the server to interleave some bytes of that response with others. A prominent example of such response is a zip file. A zip file cannot be processed until it is completely downloaded, because the central directory exists at the end of the file.

Considering these examples, I tend to think that recommending one behavior would not be very helpful. Priorities indicated by clients are merely hints, my preference goes to allowing servers to do whatever they think are beneficial, using various hints with the extensible priorities being _one_ of them.

**Comment by LPardue** [comment]
I better understand @guoye-zhang's concern. I'll attempt a PR that describes the general problem in order to inform readers of pitfalls and recommend they avoid them. I don't think we want to be specific about how to do that.

**Comment by guoye-zhang** [comment]
I think there is still value in providing an example algorithm. The problem is nuanced enough that it'd be difficult to address all corner cases in a first attempt. The algorithm I proposed does not depend on any server heuristics of content type or even content length. It provides a low bar of "you'd be fine if you don't want to think about it and just implement this". You can totally discard it and implement whatever heuristics you want since it's just a hint, but it should be at least as good as this.

**Comment by LPardue** [comment]
In my experience, many implementers will just assume an example is the correct single solution. If clients assume too much about servers behaving a certain way, it can cause problems. 

We have little broad data to back it up athink it is single recommendation, which worries me. I  better to highlight the nuances and pitfalls.

**Comment by kazuho** [comment]
What @LPardue says. If we are to suggest some type of logic, it has to work well across the board.

I see at least three logics being discussed in this issue, that are to be used when the only hint given to the server is the extensible priority signals:
1. divide the bandwidth between incremental and non-incremental responses based on their numbers (https://github.com/httpwg/http-extensions/issues/1232#issuecomment-663724301)
2. serve incremental responses first, then the non-incremental ones (https://github.com/httpwg/http-extensions/issues/1232#issuecomment-663896182)
3. first few bytes of incremental responses are given priority above non-incremental requessts, the remainders are given lower precedence (https://github.com/kazuho/draft-kazuho-httpbis-priority/issues/94#issuecomment-572032461, linked from https://github.com/httpwg/http-extensions/issues/1232#issuecomment-665087636)

Assuming that the goal of prioritization is to maximize the amount of meaningful output provided to the user at earlier moments, both (1) and (2) have downsides.

The problem with (1) is that it devotes some bandwidth to non-incremental responses when incremental responses are inflight. During the early stages of a connection, spending all available bandwidth on incremental responses is beneficial, because a server can assume that sending *some* portion of the response provides benefit to the user, if that response can be processed incrementally. To give an example, sending 10% of 5 incremental responses is better than sending 50% of a non-incremental response.

In contract, (2) suffers during the mid stages of a connection, because it significantly delays the transfer of non-incremental responses. As an example, when a non-incremental response carrying a JSON file and an incremental response carrying a progressive JPEG image is competing at the same urgency level, it is natural to assume that completing the transfer of the JSON file is more important than completing the transfer of the progressive JPEG image.

As can be seen, my point is that the significant of sending a byte changes during the stages of a connection, or between the byte ranges of each response, if the response is incremental. That is why I tend to prefer (3), though the downside is that the logic is bit complex.

And going back to my previous point, this whole discussion is about servers not using other knowledge that are likely to be available. It could well be the case that the server could make better decision, had it been given the knowledge that the application has.

That's why I tend to think that suggesting pitfalls (and the possibility of using other signals) is the answer here.

**Comment by guoye-zhang** [comment]
@kazuho I agree with you that server should be more intelligent about data delivery if it has more knowledge about the content. However, it still needs a fallback algorithm when other sources of signaling are not available, for example if a new application sends a new image format that it does not understand. 10% is a good heuristic for JPG, but might not be applicable for, for example, streaming video files, as stalling at 10% would not be ideal.

Your argument that "10% of 5 incremental responses is better than sending 50% of a non-incremental response" is completely valid. I'd even say that completing 99% of non-incremental response is equivalent to completing 0%. However, percentage is only part the story. Let's consider a situation where incremental response is 1MB and non-incremental response is 1KB, do we send 1KB after 10% of 1MB? Round-robin is a safe default. There might also be cases where we don't know the length ahead of time.

The question that matters to me is "Is this algorithm worse than not supporting incremental-signaling at all?" I'd be happy to support other algorithms if they can achieve this (not being worse).

**Comment by guoye-zhang** [comment]
The answer could also be "if there is a single incremental response, all responses at the same urgency level are treated as incremental and just keep reusing your existing server heuristics"

**Comment by kazuho** [comment]
> The question that matters to me is "Is this algorithm worse than not supporting incremental-signaling at all?"

IIRC, at one point there was discussion regarding if we need incremental flag at all. Note that Chrome does not use weight-based prioritization at all in H2. Based on these points, I tend to think that it would not be that terrible for a server to not support incremental signaling at all, or to not do incremental when the responses being served are mixed.

**Comment by guoye-zhang** [comment]
Ability to mark all resources non-incremental is critical for Low Latency HLS, so I'd say it is very useful for us.

Overall, I just want to get a sense of if:
1. Incremental-signaling significantly changes how resources are delivered, and in some cases negatively, so don't change it unless you are absolutely sure what you're doing.
2. Incremental-signaling significantly changes how resources are delivered, but it is well-thought-out and with all corner cases considered, so you can set it wherever it makes sense.
3. Incremental-signaling is just a hint and mostly ignored by servers, setting it will probably be fine.

**Comment by jonglezb** [comment]
This is the first question that came to mind when reading the document: what happens when mixing incremental and non-incremental resources at the same priority level? It's definitely a difficult problem.

FYI, I published some theoretical results ([IEEE paper](https://ieeexplore.ieee.org/document/9142713), [open-access version](https://hal.inria.fr/hal-02570686)) that basically use the following approach on the server side:

- always respect the strict priority classes (what's called "urgency" here)
- within a priority class, send resources with the smallest "remaining completion time" first. In practice, it can be approximated by the remaining amount of data to send for this resource. If it's unknown, assume it's infinite, or estimate the remaining completion time some other way.
- within a priority class, a new resource will preempt an existing resource if it has a smaller estimated completion time (approximation: if it has smaller content length compared to what remains to be sent for the existing resource)

It's an adaptation of SRPT (Shortest Remaining Processing Time first).

I deal with incremental resources by assuming they can be modeled as several successive resources. If this is not possible, then the problem becomes much harder.

**Comment by jonglezb** [comment]
To clarify the last part: let's assume that a progressive image can be split into three "virtual" resources: for the sake of example, let's say 16 KB (metadata), 256 KB (low-res part), 4 MB (high-res part).

If it's in the same priority class as a 64 KB js file and a 512 KB non-progressive image, here is the order in which resources would be scheduled:

- 16 KB of the progressive image (metadata)
- 64 KB js file
- 256 KB of the progressive image (low-res part)
- 512 KB non-progressive image
- 4 MB of the progressive image (high-res part)

If there are several concurrent progressive images with the same 16K/256K/4M "split":

- send all 16 KB metadata sequentially, then
- send all 256 KB low-res parts sequentially, then
- send all 4 MB high-res parts sequentially. Since they will likely have different sizes, start with the smallest ones.

**Comment by LPardue** [comment]
Thanks for sharing the paper. I took a skim read. It seems like some of the assumptions do not hold in certain kinds of Internet deployments such as reverse proxies or CDNs e.g.

> We also assume that the scheduler has access to the total size S of the message, for instance through a HTTP/2 header, and that application data is always available when the scheduler needs it.

The paper does acknowledge that some assumptions might not hold and provides some different strategies.

The modelling of incremental resources as a series of successive resources is interesting. It is similar to the work that was presented on https://blog.cloudflare.com/parallel-streaming-of-progressive-images/. Notably, in contrast to my earlier statement, by using response headers an upstream can inform the Cloudflare edge to schedule different byte ranges within our priority scheme e.g:

```
cf-priority: 30/0
cf-priority-change: 512:20/1, 15000:10/n
```

The hope is that extensible priorities allows the community to define an extension parameter similar to `cf-priority-change` but that is beyond the scope of this document.

Getting back to the core issue here. I hope people will agree with me that there is going to be no universal perfect scheduler that is deployable. This document needs to contain widely-actionable text. My intent is to create a PR that describes some of the challenges without procsribing any particular solution.

**Comment by jonglezb** [comment]
Indeed, I had forgotten about it, but this "metadata / low-res / high-res" example above is inspired by the blog post.

> Getting back to the core issue here. I hope people will agree with me that there is going to be no universal perfect scheduler that is deployable. This document needs to contain widely-actionable text. My intent is to create a PR that describes some of the challenges without procsribing any particular solution.

I completely agree. While I'm happy we have found a generic scheduling scheme that has good theoretical properties, ultimately the "best" scheduling scheme really depends on the application. Well, thanks to @rmarx and others, we at least know that Round-Robin is a terrible idea in general ;)

**Comment by LPardue** [comment]
We didn't get any pushback on the PR, so I'm going assume it addresses this problem as understood at the end of the discussion. If that's not the case, please open new, specific issues targetted at the new text.
