### ISSUE TITLE
Clearing Client Hint preferences with browser history seems odd

### ISSUE THREAD

**Issue by amtunlimited** [httpwg/http-extensions#1238]
> User agents MUST clear persisted opt-in preferences when any one of site data, browsing history, browsing cache, cookies, or similar, are cleared.

Browsing history seems to stand out to me here. There are a couple of pedantic questions (does this mean full history, or back beyond a certain amount of time?) and doesn't seem to fit with precedent. In general, I don't expect much other information to be cleared when removing history information, but that might very well just be me.

**Comment by davidben** [comment]
I agree the text seems a bit overprescriptive here. I could imagine UAs that want to clear it with browsing history and UAs that don't, depending on what they're trying to accomplish. It's a question of which "please forget this" use cases the browser is aiming to meet with each option.

Perhaps the UA has an option whose aim is "please make this site forget about me". Then the UA should clear client hint preferences, site data, and cache, but may or may not decide history is separate. (Assuming the history is not web-visible!) Or perhaps the aim is "I don't want these links to appear in address bar completions". Then perhaps the UA will clear just history but not any site data because the user didn't ask to be logged out. Or perhaps the UA wants to combine these two into one option. Or perhaps the option is for developers, to clear particular pieces of cache to diagnose some issue. Then maybe the client hint cache should be cleared or maybe the option is just about the HTTP cache.

Ideally the text would capture enough that UAs can make the correct decision for each of their features. (And, since it has privacy implications when UAs forget, probably explicitly call out clearing this in "please make this site forget about me" cases like clearing cookies and site data.)

**Comment by reschke** [comment]
FWIW, the spec has been approved early July and is in the RFC Editor queue (see https://datatracker.ietf.org/doc/draft-ietf-httpbis-client-hints/). Changes at this stage can only be done with a lot of care.

**Comment by amtunlimited** [comment]
@reschke I was unaware, thank you.

@davidben I guess the question is is the issue worth poking? I don't think it'd consider it a blocker for publishing, but I'm not super experienced in the standards processes, where I suppose things are less "tweakable" after-the-fact

**Comment by davidben** [comment]
Ah yeah, the timing is awkward. At the same time, I don't think it does anyone any good if the document does not match what people intend to implement. Since browsing history is, well, a browser notion, I suppose the main question is what browser implementors would do.

Checking Firefox, it has separate dialogs altogether for "Clear [Site] Data" and "Clear History", with the latter sectioned under what Firefox remembers, not what the site remembers. The clear history dialog does have separate checkboxes for "Browsing & Download History" vs "Cookies" and "Cache", but if I tell it to just clear the browser-side history it, as one would expect, does not clear HTML localStorage (to pick an example of site state not explicitly covered under here).

That and the description suggests to me that, like in Chrome, the "Browsing & Download History" option is a "I don't want to see this in browser completions" feature, not a "I want the site to forget about me" feature, and so it would not make sense to associate the Client Hint cache with browsing history, only cookies and/or cache. @martinthomson, would you agree with this?

If so, I think that supports https://github.com/httpwg/http-extensions/issues/1238#issuecomment-667216778 and the current text is too prescriptive. Since it's late in the process and we probably don't want to make large changes, perhaps we should simply strike "browsing history" from the list. Then implementors can make a judgement as to whether "or similar" covers browsing history for their particular context.

**Comment by amtunlimited** [comment]
> perhaps we should simply strike "browsing history" from the list. Then implementors can make a judgement as to whether "or similar" covers browsing history for their particular context.

Sounds good to me; I can adjust the PR to match. Is there any process for getting changes propagated not that it's moved on to the next step?

**Comment by martinthomson** [comment]
> That and the description suggests to me that, like in Chrome, the "Browsing & Download History" option is a "I don't want to see this in browser completions" feature, not a "I want the site to forget about me" feature, and so it would not make sense to associate the Client Hint cache with browsing history, only cookies and/or cache. @martinthomson, would you agree with this?

There are two models in conflict here and we have tried over time to make that clear.  History is not site state, so you are right.  We do couple some of our capabilities around this: if a user asks the browser to forget a site, that also means that the browser will forget everything it stores for that site which (ideally, in principle) results in the site also forgetting about the user.

**Comment by yoavweiss** [comment]
> There are two models in conflict here and we have tried over time to make that clear. History is not site state, so you are right. We do couple some of our capabilities around this: if a user asks the browser to forget a site, that also means that the browser will forget everything it stores for that site which (ideally, in principle) results in the site also forgetting about the user.

Interesting! So if the user picks "forget my history", site data remains intact, while them picking "forget this site" results in both the site removed from history *and* site data being removed?

In that case, just removing "browser history" from the current paragraph (as David suggested) will still cover the latter case, right? (as "site data" is still explicitly mentioned)

**Comment by amtunlimited** [comment]
> In that case, just removing "browser history" from the current paragraph (as David suggested) will still cover the latter case, right? (as "site data" is still explicitly mentioned)

I would agree, and I've adjusted the PR to match.

**Comment by amtunlimited** [comment]
I'm just going to close this
