### ISSUE TITLE
Feedback on draft-ietf-httpbis-priority-01

### ISSUE THREAD

**Issue by olnrao** [httpwg/http-extensions#1244]
**URL**: https://tools.ietf.org/html/draft-ietf-httpbis-priority-01
**Summary**: In many places, response is used than request
**Details**:

**Section**: 4. The Priority HTTP Header Field
**Revision**: 
The Priority HTTP header field can appear in requests and responses. A client uses it to specify the priority of the **~~response~~ request**.  A server uses it to inform the client that the priority was overwritten.  An intermediary can use the Priority information from client requests and server responses to correct or amend the precedence to suit it  (see Section 6).

**Section**: 5. Reprioritization
**Revision**: 
After a client sends a request, it may be beneficial to change the priority of the **~~response~~ request**.  As an example, a web browser might issue a prefetch request for a JavaScript file with the urgency parameter of the Priority request header field set to "u=7" (background).  Then, when the user navigates to a page which references the new JavaScript file, while the prefetch is in progress, the browser would send a reprioritization frame with the priority field value set to "u=0".

In HTTP/2 and HTTP/3, after a request message is sent on a stream, the stream transitions to a state that prevents the client from sending additional frames on the stream.  Therefore, a client cannot reprioritize a **~~response~~ request** by using the Priority header field.

**Section**: 6. Merging Client- and Server-Driven Parameters
**Revision**:
It is not always the case that the client has the best understanding of how the HTTP **~~responses~~ requests** deserve to be prioritized. The server might have additional information that can be combined with the client's indicated priority in order to improve the prioritization of the **~~response~~ request**.
...
An origin can use the Priority ~~response~~ header field to indicate its view on how an HTTP **~~response~~ request** should be prioritized.  
...

(Ok, I think it's not wise for me to give every occurrence. I hope you get the point)

**Comment by LPardue** [comment]
The use of response is intentional because the interoperability of extensible priority signals is premised on hinting to the server how is should schedule sending of response data.

Using the term request everywhere makes the intention of the document unclear. Although a server _might_ consider the priority of an incoming request to make local scheduling decisions, e.g. decide to do work for one request over another before sending, that is not the intention of this document and we say nothing about it today.

**Comment by olnrao** [comment]
Thanks for the quick feedback, @LPardue.  I am bit confused here.  Unless server attends to the request at priority, it can't event know the priority.  Indirectly response priority is driven by priority requested by client in request headers.  Of course, after server reads the request, we can then talk about whether it should respond fast.  If we really want that level of clarity then we should have two headers - request priority to make sure this request is queued ahead of other normal requests, response priority to queue the response ahead of existing normal responses.  Unless we have both in place, I am not sure if we can achieve the desired goal you have stated.  I think I may be missing something.  It would be great if you can expand a bit more on where my thinking is faltered.  Thanks again for your help.

**Comment by LPardue** [comment]
RFC 7540 S 5.3 says:

>    The purpose of prioritization is to allow an endpoint to express how
>    it would prefer its peer to allocate resources when managing
>    concurrent streams.  Most importantly, priority can be used to select
>    streams for transmitting frames when there is limited capacity for
>    sending.

In practice, this means HTTP/2 prioritization is concerned with managing how response bytes are sent in DATA frames on streams when multiplexing is taking place. Many HTTP/2 servers do consume priority signals (in HEADERS or PRIORITY frames) and adapt scheduling to these signals. Sadly, some servers do not.

Extensible priorities is applicable to HTTP/2 and HTTP/3, so we need to select terminology that applies to both and accomodates the subtle differences when it comes to stream lifecycle.

Since HTTP/2 prioritization was mainly focused on response multiplexing, we choose to use the term `response` to make the primary purpose of extensible priorities unambiguos.

I have not heard anyone making a serious case for the need to control prioritizing request processing. So I'm of the opinion that we can not go to the effort of specifying anything.

**Comment by olnrao** [comment]
Thank you, @LPardue.  I did not connect the extensibility part in first go.  Thanks for taking time to expand.  Will close this.

**Comment by LPardue** [comment]
No problem. People do use the terms `request prioritization` and `response prioritization` interchangable, so I get why it's confusing. Since the signal here is a header that can appear on either message, I want to be especially careful with consistency of terms in the document.
