### ISSUE TITLE
State that priority parameters cannot be split across PRIORITY_UPDATE frames

### ISSUE THREAD

**Issue by dtikhonov** [httpwg/http-extensions#1267]
Because priority parameters are an sf-dictionary, they can be split across header lines.  This is not the case for priority updates carried in _PRIORITY_UPDATE_ frames.

While this restriction can be inferred from a couple of sentences in the draft, stating it explicitly -- priority parameters cannot be split across _PRIORITY_UPDATE_ frames -- would make the draft clearer.

**Comment by LPardue** [comment]
I hadn't thought much about this. https://tools.ietf.org/html/draft-ietf-httpbis-header-structure-19#section-3.2 says 

>  Note that Dictionaries can have their members split across multiple
>    lines inside a header or trailer section; for example, the following
>    are equivalent:
> 
>    Example-Hdr: foo=1, bar=2
> 
>    and
> 
>    Example-Hdr: foo=1
>    Example-Hdr: bar=2
> 
>    However, individual members of a Dictionary cannot be safely split
>    between lines; see Section 4.2 for details.

A client could send urgency and incremental parameters in separate PRIORITY_UPDATE frames. However, that risks the server processing each as if the other parameter was omitted, which is probably surprising and not the intention. Is that what you mean by "cannot be split"?

@kazuho WDYT about us adding text making this situation clearer?

**Comment by kazuho** [comment]
I am fine with stating that each PRIORITY_UPDATE frame is distinct and complete, rather than a conveyer of the difference.

The pros of that approach is that the server can ignore the value of the priority request header field if it has already received a PRIORITY_UPDATE frame. If we are to say that the frame carries the delta, the server will be required to parse the value of the request header field then apply the value that have been sent by using (possibly multiple of) PRIORITY_UPDATE frames.

I'm a bit disappointed that we would not have alignment with how the priority response header is being handled (it is considered as a delta that corrects the client-provided values), but I think the point explained above is more important.

**Comment by martinthomson** [comment]
I think the difference is OK.  I would not expect the header field to be updated by a partial trailer field, for instance.  All of the individual field lines in a header combine into a single value by the end of the header.  The frame doesn't get to provide multiple lines, so it has to be complete.

That is, unless I'm misreading the example in the structured fields draft.  I'll open an issue...
