### ISSUE TITLE
signatures: asterisk preceding some content identifiers

### ISSUE THREAD

**Issue by llorllale** [httpwg/http-extensions#1303]
The draft lacks normative text on the meaning of the asterisk preceding certain content identifiers in the `headers` signature parameter. Seems like they are meant to indicate signature metadata fields, but that still leaves two categories in need of discrimination: HTTP headers and the request line. Suggest we remove this asterisk and instead rely on the registry (section 5.2.2) and the definition of each item (sections 2 and 4.1).

**Comment by llorllale** [comment]
PR #1297 is removing parenthesis: https://github.com/httpwg/http-extensions/pull/1297#discussion_r508296903

**Comment by ioggstream** [comment]
@llorllale if the preceding asterisk works for you, can you please close?

Otherwise, could you update the issue title and description to be in line with the current version?

Thanks 😊

**Comment by llorllale** [comment]
@ioggstream 

> @llorllale if the preceding asterisk works for you, can you please close?
> 
> Otherwise, could you update the issue title and description to be in line with the current version?
> 
> Thanks blush

Updated title and description.

I'd first appreciate some clarity around the use of the asterisk. Like I said in the opening comment: I strongly suspect they're there to identify pseudo HTTP headers. I just can't flat out say so because there is no normative text explaining the use of the asterisks!

My question is: why are we marking pseudo-headers? For example, are we to differentiate between pseudo-header `*created` and an actual HTTP header `Created`? If so, we need normative text describing the expected behaviour. I would assume a new section is required just to explain the use of the asterisk when preceding tokens inside the `sig*` dictionary entry.

**Comment by llorllale** [comment]
This question is linked to #1304.

**Comment by ioggstream** [comment]
@llorllale thanks for updating.

1- `*` does not identify [pseudo-headers](https://tools.ietf.org/html/rfc7540#section-8.1.2.1) which are something related to a specific version of HTTP; instead, they distinguish between signature parameters and http fields. IIUC `*created` is the actual name of the signature parameter.
2- imho this spec should not rely on specific MESSAGING behavior and should build instead on [SEMANTICS](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html) only

For the rest, feel free to propose a PR with the text you expect to see here! It could trigger a faster discussion :)

**Comment by msporny** [comment]
> 1- * does not identify pseudo-headers which are something related to a specific version of HTTP; instead, they distinguish between signature parameters and http fields. IIUC *created is the actual name of the signature parameter.

Err, hold up -- "(request-line)" was intended to refer to a pseudo-header and other non-header values... I'm now seeing that we have something new in the spec with the addition of asterisk for signature parameters? Are we sure we want to do that? Anyone have the background on why this addition was made? Or are we switching everything over to asterisk-led stuff now?

**Comment by msporny** [comment]
Hmm, so I guess this change is being made because of the adoption of the Dictionary Structured Header Fields stuff... and because those require the outermost characters to be parenthesis in a set? Have we put any thought into what is going to happen w/ existing implementations? I guess they'd barf, which is an ok thing to do... as long as they will always barf.

**Comment by OR13** [comment]
this is fairly incomprehensible.... some implementations refer to pseudo headers, but I can't find a defintion for them anywhere... what is the correct way to structure the authorization header...starting with:

```
Signature keyId="${verificationMethod}",algorithm="hs2019",headers="(key-id) (created) (expires) (request-target) host content-type digest",signature="${signature}",created="${created}",expires="${expires}"
```

https://tools.ietf.org/html/rfc7540#section-8.1.2.3

^ are we doing this or not?

**Comment by msporny** [comment]
> some implementations refer to pseudo headers, but I can't find a defintion for them anywhere

The whole format has changed due to the proposed adoption of Structured Headers... there are now TWO headers you need to care about `Signature-Input` and `Signature` ... and I can't tell if everything has changed over to this new asterisk format, or if pseudo-headers are still wrapped in parens, and signature input params use asterisks. I'm guessing that everything that is either a pseudo-header OR a signature input parameter are prepended by asterisks now. Waiting on confirmation on that.

**Comment by OR13** [comment]
examples / test-vectors would help.... given the state of the spec, its not possible for me to divine any... a reference implementation is desperately needed.

**Comment by ioggstream** [comment]
@OR13 this spec is going to change a lot... a reference implementation won't be stable in a short period iiuc, but I think we should have it. There are [ ~40 issues to be worked out](https://github.com/httpwg/http-extensions/labels/signatures).

@msporny let me try to clarify the terminology, as I am a bit confused.

## avoid using the pseudo-headers term

- the `pseudo-header` term is  defined in http/2;
- in draft-cavage, pseudo-headers are only mentioned in constructing the `(request-target)` special header: I'd avoid even in that spec a reference to http/2 
- imho the term `pseudo-headers` should not be used explicitly neither in this I-D, nor in draft-cavage

## referencing the signature input fields

- In draft-cavage-http-signatures-12 the signature input is referenced as "signature parameters" or "special header".
iiuc this thread is related to "signature parameters and special headers" (draft-cavage terminology);
- while it's still a I-D and every change can be reverted, I am not that negative on splitting the stuff in two headers, because it simplifies the processing steps;  

My 2¢ and have a nice day, R.

**Comment by OR13** [comment]
I took at stab at an implementation over the weekend, https://github.com/transmute-industries/axios-http-signatures

but I can't figure out which version of the spec this is based on... (its modeled after digital bazaar's implementation).

I agree that this spec is not ready for a reference implementation, but I am also having a really hard time understanding what is proposed in the issues, without examples / code.

eager to help just unsure how best I can.

**Comment by jricher** [comment]
An alternative proposal is to separate headers, formal pseudo-headers, and "other defined signature inputs" into different parts of the structure.

As for existing implementations, they are allowed to barf when the format changes. Backwards compatibility with any specific I-D is not a specific goal here.

**Comment by jricher** [comment]
@OR13 This is a spec in progress, so the best you can do is implement what's in the spec today (whether that's the currently published WG draft or the editor's copy in the repository) and help us figure out what works and what doesn't in practice.

**Comment by ioggstream** [comment]
> separate headers, formal pseudo-headers, and "other defined signature inputs" into different parts

Reasonable :+1: 

Still I will replace everythere in this thre `pseudo-headers` as they are now [Signature Metadata](https://github.com/httpwg/http-extensions/blob/master/draft-ietf-httpbis-message-signatures.md#signature-metadata-signature-metadata)

@llorllale could you please :pray: update the issue text and replace `pseudo-headers` with Signature Metadata (referencing the spec) so that new readers (eg. http folks) won't be confused :)

**Comment by llorllale** [comment]
> An alternative proposal is to separate headers, formal pseudo-headers, and "other defined signature inputs" into different parts of the structure. This would get out out of the business of syntax for "header" vs "not header".

+1

> could you please pray update the issue text and replace pseudo-headers with Signature Metadata (referencing the spec) so that new readers (eg. http folks) won't be confused :)

Done

**Comment by ioggstream** [comment]
> @OR13 This is a spec in progress, 

I somewhat like the way Signed-Exchanges versions signed messages to avoid confusion between implementation of different drafts.

**Comment by OR13** [comment]
I've been able to determine that the version of this spec I have seen floating around are claiming to be https://tools.ietf.org/html/draft-cavage-http-signatures-11

So I think I can split my implementation now to support that version of the spec, and wait for the right time to try and implement the next round of breaking changes in a subsequent version.

**Comment by msporny** [comment]
> So I think I can split my implementation now to support that version of the spec, and wait for the right time to try and implement the next round of breaking changes in a subsequent version.

Yes, this is what we're being forced to do. Given that the HTTP WG version of the spec can't commit to an end to the breaking changes/restructuring, and given that we have to ship product to customers... we're committing to shipping the I-D in production (much like the rest of the implementers have been doing for years) and will just wait an see when the HTTP WG version of the spec stablizes.

@jricher @richanna -- is there a roadmap for when breaking changes will stop in the HTTP WG version of the spec?

**Comment by mnot** [comment]
Hi Manu,

We don't have any milestones for shipping this specification, and since we don't have other specifications yet depending upon it, it's unlikely we'll establish one. As a general guideline, I'd expect this to take several more months, although depending on how things go, it could stretch on longer.

As an implementer, I understand your frustration with this uncertainty. This is the nature of standards work; because we're getting more broad and deep input, it requires more discussion, work and changes. The current specification is not suitable for implementation or deployment.

As such, you seem to be doing the right thing -- shipping draft-savage now and waiting for this specification to stabilise. 

However, we don't want to get this specification stable only to find that it doesn't meet real-world needs. A few things that you and others can do to help us get done more quickly as well as ship a better spec (and corresponding implementations):

* Give constructive feedback on the spec. Issues and PRs are both great.
* Participate in the discussions when they're being held. Revisiting decisions that were already discussed wastes a lot of time.
* When the specification gets to sufficient stability (what we called 'first implementation draft' in HTTP/2 and QUIC), writing an implementation and/or tests, and giving feedback based upon that.

@jricher / @richanna - it might be good to update the 'Note to Readers' at the top of the draft to reflect its current state; while the statements there were true when it started, they might mislead folks now.

**Comment by jricher** [comment]
Intro paragraph text has been updated in PR #1329

**Comment by richanna** [comment]
> @jricher / @richanna - it might be good to update the 'Note to Readers' at the top of the draft to reflect its current state; while the statements there were true when it started, they might mislead folks now.

Agreed, will update.

> I'd first appreciate some clarity around the use of the asterisk.

Content identifiers for things that aren't header fields start with `*`. Agreed that this needs to be made explicit in the draft, similar to how the leading `:` in pseudo-header field names is explicitly described in 7540.

The leading `*` is intended to provide a safe "namespace", allowing us to identify header fields by their plain name (lowercased) without risk of collision. Though on revisiting 7230 I realize I was mistaken about two things:
1. Field names actually can start with `*`
2. Field names can start with a bunch of characters that Structured Field tokens cannot start with

Since we have to switch the Structured Field data type for content identifiers from tokens to strings (ugh double quotes everywhere 🙁) anyway, we can replace `*` with `@`, which is not allowed in field names (or tokens), and is thus reliably collision resistant.

> An alternative proposal is to separate headers, formal pseudo-headers, and "other defined signature inputs" into different parts of the structure.

I think this introduces more problems than it solves. I can't see a clean way to fit multiple lists per signature using Structured Fields while still preserving the ability to add multiple signatures. It also introduces additional complexity for generating the signature input, as now we need ordering rules for these different lists. When it's all in one list, the order in the input matches the order in the list.

**Comment by OR13** [comment]
+1 for a single list.

+1 for the symbol not being allowed in the tokens (`@` over `*`).

**Comment by richanna** [comment]
We should include guidance (in a "to be removed by RFC editor" appendix) on backwards compatibility when we make this change, to help early adopters transition. In this case, it might look something like "Since no HTTP fields with names starting with `*` are presently defined, validators can accept both `*` and `@` for a brief period of time until signers update to use `@`. See: #1410 .

**Comment by jricher** [comment]
I've submitted a PR to change the marker symbol to `@`, more directly use structured fields, and to make it more clear what the different inclusion methods are and how they work: #1411

**Comment by jricher** [comment]
Specialty fields were defined in -03 to address this, and the definition of covered content was expanded to accommodate the shift.
