### ISSUE TITLE
signatures: clarify letter case for content identifiers

### ISSUE THREAD

**Issue by llorllale** [httpwg/http-extensions#1308]
This line in the definition of `headers` is hard to understand, unless one assumes the "header fields" refers to HTTP headers:

> If specified, identifiers for header fields SHOULD be lowercased and all others MUST be lowercased.

Suggest clarification on what header fields are being referred to here. Or, in agreement with the suggestion in B.1.15, we could just force implementations to lowercase all content identifiers.

**Comment by richanna** [comment]
I'm very in favor of simply mandating lowercase for all content identifiers.

**Comment by msporny** [comment]
The reason the spec didn't do this originally was because implementers complained about a mandatory lowercase for all identifiers because it didn't matter. They'd lowercase anyway when doing c14n. The pseudo-headers were always lower-cased because they weren't real headers and we could more easily suggest that implementers do this. That said, there's really no strong argument that I know of where they should be lowercased.

Fundamentally, I get the theoretical purity here and don't have a super strong opinion on this. Implementers got it wrong and developers got it wrong, and it caused implementations to throw errors that were annoying to developers: "If a computer can lowercase it for me deterministically, why are you asking me to do it?!".

What's the reasoning for mandating lowercase?

**Comment by ioggstream** [comment]
> What's the reasoning for mandating lowercase?

Interoperability.

**Comment by msporny** [comment]
> Interoperability.

How does mandating lowercase increase interoperability? 

There are two ways to get there... 1) mandate lowercase, causing developers to have to take on that mental effort (which is usually a bad way to go -- they're human for now, so fallible), or 2) implementations lowercase everything (make the machines do the heavy lifting, because they have to check for lowercase anyway).

**Comment by ioggstream** [comment]
I usually like something that breaks early and avoid troubleshooting at runtime. Recently we suggested using lowecase for digest-algorithms.

But I'm open to other, interview-based or data-drive-based positions.

**Comment by msporny** [comment]
> I usually like something that breaks early and avoid troubleshooting at runtime. Recently we suggested using lowercase for digest-algorithms.

"suggest" or "mandate"? The former makes sense. I'm struggling to understand how the latter makes sense if implementations MUST call lowercase() on certain input parameters?

> But I'm open to other, interview-based or data-drive-based positions.

What sort of data would be convincing to you? I ask, because this seems to be an instance where gathering the data for/against is going to be very difficult, but reasoning about is fairly trivial. For example:

1. Require implementations to lowercase certain input parameters (e.g., all left hand values being c14n'd and any argument that could end up being c14n'd -- specifically, don't lowercase right hand values being c14n'd) to the c14n function.

If we do this, how does the algorithm break wrt. case sensitivity?

**Comment by ioggstream** [comment]
> "suggest" or "mandate"? The former makes sense.

httpbis-digest-headers is a refresh of RFC3230, so we could not `MUST lowercase`: if it was a new spec, we'd `MUST lowecase`.

> What sort of data would be convincing to you?

I don't need to be convinced :) I'm really open to feedback, and I'll leave this kind of decision to the http-wg.

**Comment by msporny** [comment]
@ioggstream wrote:
> httpbis-digest-headers is a refresh of RFC3230, so we could not MUST lowercase: if it was a new spec, we'd MUST lowecase.

Now I'm confused. :)

We're talking about the HTTP Message Signatures spec, right? Not the httpbis-digest-headers spec? HTTP Message Signatures is a new spec, so we can mandate MUST lowercase... the question is where... 1) in the c14n algorithm, or 2) as guidance for input into the algorithm?

@richanna wrote:
> I'm very in favor of simply mandating lowercase for all content identifiers.

Perhaps @richanna can provide some input on what exactly would be mandated via specific spec text changes?

**Comment by richanna** [comment]
The draft has been updated to mandate lower-case for content identifiers for header fields. See [section 2.1](https://www.ietf.org/archive/id/draft-ietf-httpbis-message-signatures-01.html#name-http-header-fields) (bold emphasis added for clarity):
> An HTTP header field is identified by its header field name. While HTTP header field names are case-insensitive, **implementations MUST use lowercased field names** (e.g., `content-type`, `date`, `etag`) **when using them as content identifiers.**
