### ISSUE TITLE
Deprecate all legacy algorithms below sha-256.

### ISSUE THREAD

**Issue by ioggstream** [httpwg/http-extensions#1377]
## I expect

- to `deprecate(d)` all legacy algorithms with MUST NOT ;  this includes  crc32c, which seems to be stilil used in https://cloud.google.com/storage/docs/hashes-etags
- to avoid using `obsolete` or other terms.

Replaces #1138 #1139

**Comment by martinthomson** [comment]
Curious as to why you thought that CRC-32 and ADLER32 are OK.

**Comment by LPardue** [comment]
In the context of Digest, I don't think anyone using an algorithm matters, unless they are using Digest. Google decided to do their own thing, so their on their own and shouldn't impact our decisions here.

The important thing us that we aren't the global algorithm police but we are, in collaboration with the expert and IANA, responsible for https://www.iana.org/assignments/http-dig-alg/http-dig-alg.xhtml

**Comment by ioggstream** [comment]
@martinthomson adler32 is deprecated, so it's in the same bucket of md5, unixsum and unixcksum (after this PR).

>  I don't think anyone using an algorithm matters, unless they are using Digest.

@LPardue ok to me to deprecate all non-crypto algorithms then. Do we all agree?

**Comment by LPardue** [comment]
TBH I'm finding the distinction between `obsoleted` and `deprecated` algorithms confusing. I can't recall why we went that way. Given that the conversation has evolved a bit since the -00 draft, I wonder if we should just align on `deprecated` with the requirement "MUST NOT use", with the understanding that endpoints will probably ignore that advice with little punishment.

Since @manger is the expert, and suggest `obsolete` (https://github.com/httpwg/http-extensions/issues/828#issuecomment-517095275) I wonder if he has an opinon on the matter.

**Comment by ioggstream** [comment]
I reconstructed the old threads and the reasoning was the following:

- `obsoleded` SHOULD NOT | NOT RECOMMENDED: those algorithms are not "broken" but are not currently useful wrt other protection mechanisms like TLS;
- `deprecated` MUST NOT: those algorithms are "broken" as they are not serving the purpose they were originally designed of (eg. `md5`, `sha`).

@martinthomson proposal was to MUST NOT everything that is below sha-2.

I really don't have preferences on this issue, I just want to get it done in whatever way, since I won't use anything below sha-256 ;)

**Comment by LPardue** [comment]
I'd like to avoid having to explain the rationale between these two similar states. Since we use obsolete already through the document for different aspects of digest, I'm fine with dropping the term `deprecated` and just using `obsolete(d)` with MUST NOT throughout. However, this is probably something we should put to the WG for confirmation.

**Comment by LPardue** [comment]
When discussed at the February interim, people seems to prefer using `deprecated` everywhere.

**Comment by ioggstream** [comment]
Closed via #1567 / #1543
