### ISSUE TITLE
backward compatibility for current http-signatures implementations

### ISSUE THREAD

**Issue by kaniini** [httpwg/http-extensions#1410]
There's a wonderful world out there of servers implementing ActivityPub, which already implement HTTP Signatures.

Unfortunately, `draft-ietf-httpbis-message-signatures-01` has completely broken compatibility with current implementations, because it changed `(request-target)` to `*request-target` for the signing string, as well as completely changing the way the `Signature` header works.

Is there any advice for allowing both forms of the signature to exist at the same time?

I know, you're going to say: "deploying internet-draft specifications in production is not good practice", but I didn't make that decision, the ActivityPub community made that decision several years ago based on perceived stability of the spec.

This is a serious problem that blocks any possibility of upgrading to support the latest draft, as it breaks *real world* use of the extension.

**Comment by msporny** [comment]
> Is there any advice for allowing both forms of the signature to exist at the same time?

Yes, and the expectation is that most libraries can (and will) support the old version and the new version. Presently, while the specification is silent on how to do that, implementers are putting in two code paths -- one for the old version and one for the new version by doing feature detection on the signing string... 

In short, if you see (request-target) -- you use the old algorithm to verify... if you see *request-target, you use the new algorithm to verify. The libraries will also be given the option of generating an old-style signature (which is what ActivityPub uses) and a new-style signature (which ActivityPub can switch to once the official spec is live AND the ActivityPub community has deployed enough infrastructure to be sure that they can support new style signatures without breaking the ecosystem).

**Comment by kaniini** [comment]
Uhh, how does that work?

The signing string is not known to us ahead of time as we generate it on the verifying side.

Are you saying that we should look for headers="(request-target)" in the Signature header?  What if somebody creates a new signature with `Signature-Input: headers=(...)`?

**Comment by kaniini** [comment]
It seems to me the best way to go is if `Signature-Input` is in headers: it's a new-style signature, else it's old-style.

I think that's simple enough on the verify side.  I'm working on generalizing my http_signatures python implementation to work with any aiohttp.web application, so I will do this work when I split that out :)

**Comment by msporny** [comment]
> It seems to me the best way to go is if Signature-Input is in headers: it's a new-style signature, else it's old-style.

Yes, that's possibility as well -- like I said, the spec is almost certainly going to be silent on this, and it'll be up to implementers to do feature detection properly.

Now, speaking as an implementer (not as a spec author) -- I was averse to breaking changes that were not easily detectable... I don't know how much care is going into making sure there is clear feature detection possible, but I expect if we ever hit a state where it creates a huge burden on the ActivityPub community, we'd take a deep breath and serve the needs of people using this stuff in the wild rather than go down the academic purity path. We're not there yet, so I wouldn't worry too much. If we do get there, I expect that you (and I) will complain loudly (and will be heard -- I expect the HTTP WG doesn't have an interest in alienating the implementation base for the HTTP Signatures specification).

**Comment by jricher** [comment]
The `draft-ietf-http-message-signatures` spec is based on input from `draft-cavage-http-signatures` but is not intended to be directly compatible with it.  As the old draft was an independent work and not tied to any standards working group, implementation of it is always an at-risk proposition. Sometimes that risk is worthwhile, but sometimes it can cause pain.

Changes are happening in the draft to address problems with the draft, and these changes will not be hampered by backwards compatibility with the independent draft. This is not simply an exercise of "academic purity" as some might say, but rather driven by a desire to make a specification that works for a wide variety of use cases. While many have adopted the independent draft, and that experience is deeply valuable, it's important to remember that there are also many other communities who have not been able to adopt the independent draft because of limitations. Furthermore, in my personal experience, many of the implementations of the independent draft aren't compatible with each other because they either work against different versions of the draft, or they implement only portions of the draft that seem relevant at the time. Having a stable, engineering-driven RFC will help that. 

I can assure you that the editors of the spec are not blind to the issues that breaking compatibility will cause in some parts of the world, and as said above there are a lot of things we can do to signal developers clearly what's going on. I've personally been a part of several major protocol migrations (OAuth 1 -> OAuth 2, OpenID 2.x -> OpenID Connect), and so I really get where you're coming from. The spec is not likely to be silent on migration issues, in spite of what's said above, but I do agree that we aren't at the point of getting that sorted out yet. It could be something as simple as renaming a header or something more complex like detecting an internal header format, but it's something that this spec won't be blind to. In the end though, it will be worlds better than the current situation where two independent implementations of the individual draft might look like they should work together but in fact might or might not talk to each other depending on a dozen different decisions and variables.

**Comment by richanna** [comment]
I agree with Justin that the spec need not be silent on backwards compatibility/migration. Given the history here I think it's reasonable to include guidance on how to distinguish these signatures from Cavage, at least while in draft form.

> It seems to me the best way to go is if Signature-Input is in headers: it's a new-style signature, else it's old-style.

Yes, checking for the presence of a `Signature-Input` header field seems to me to be the best way to distinguish HTTP Message Signatures from Cavage signatures.

> it changed (request-target) to *request-target...

Note that this is going to change again – but not back to (...). See #1303 . I added a note there about including backwards compatibility guidance.

**Comment by kaniini** [comment]
> Note that this is going to change again – but not back to (...). See #1303 . I added a note there about including backwards compatibility guidance.

Should we bother with implementing the current draft or wait for the next draft instead?  When do you think the new format will be stable?

**Comment by jricher** [comment]
I would personally wait at least until the next draft as there are some larger changes currently in the pipeline. In the editors' copy you can see the changes that have incorporated structured headers and have made some core syntax changes. We don't have a direct timeline for publication, but we're working on it.

**Comment by jricher** [comment]
Discussion of backwards compatibility and detecting this spec in use (vs. previous individual drafts) added in -03
