### ISSUE TITLE
signatures and empty fields vs http-semantics-latest

### ISSUE THREAD

**Issue by ioggstream** [httpwg/http-extensions#1496]
## Question

Does the fact that intermediaries can aggregate fields and ignore empty fields impact on the definition of this spec?

See:
- https://github.com/httpwg/http-core/issues/836#issuecomment-826166475 
- https://greenbytes.de/tech/webdav/draft-ietf-httpbis-semantics-latest.html#abnf.extension.recipient

**Comment by jricher** [comment]
Combining field values in a deterministic way (which is required for signatures) is iffy at the best of times. There's a defined canonicalization for combining fields which, I believe, comes from the existing definitions in the HTTP core specs -- this might be able to be re-defined. If intermediaries follow the combination rules without dropping, it should be fine. If an empty field is signed by the sender and removed in transit, then that empty field won't be in the target message, meaning the signature would fail. But that's expected behavior because a signed element was removed or modified, it's exactly the time you'd want the signature to fail. If this kind of transformation is a known problem for an application, then the problematic field shouldn't be covered by the signature. This is one of the core reasons why the Signatures draft leaves it to applications and profiles to define required fields.

**Comment by ioggstream** [comment]
iiuc here is that if this spec supports combining fields, this should be done ignoring empty fields.

About breaking signatures, in general it's very hard to support or anticipate any transformation from intermediaries. I am not sure this brings much value, but I am curious about examples where this is needed.

**Comment by ioggstream** [comment]
Seems fixed in the latest semantics release. Empty fields are now retained.
