### ISSUE TITLE
[SIGNATURES] Are algorithm aliases allowed in the registry?

### ISSUE THREAD

**Issue by msporny** [httpwg/http-extensions#1538]
Will the algorithm registry allow the registration of aliases for algorithms? For example:

* recommended-signature-2015 (aliased to eddsa-2015... or just this value -- no aliases)
* recommended-nist-2013 (aliased to ecdsa-2013... or just this value -- no aliases)

**Comment by jricher** [comment]
Speaking as an individual and implementor, I do not see the value in allowing aliases like this. I would like to understand what is gained by having multiple names point to the same value. What problem is this trying to solve?

It also raises additional error cases that need to be handled, like: Can a spec add an alias without adding an algorithm definition, or do all aliases need to be registered alongside the algorithm definition? Can an alias point do a different definition at different times? Is there any functional difference between an "alias" name and registering multiple "normal" names?

This also would be problematic for interoperability. What if an implementation knows the underlying algorithm but only one of the aliases? Two otherwise compatible pieces of code would not be able to talk to each other, for no good reason.

**Comment by ioggstream** [comment]
I suggest following  https://datatracker.ietf.org/doc/html/rfc7696 for algos management
