### ISSUE TITLE
Separate lifetime from commitment element

### ISSUE THREAD

**Issue by MikeBishop** [httpwg/http-extensions#162]
Kari has raised an interesting potential weakness with the dual use of .well-known/http-opportunistic.  The presence of the resource indicates support for cross-port Alt-Svc without strong authentication.  The presence of a commit member, however, indicates that only strongly-authenticated alternatives should be used (effectively, opting out of the weaker mode).

However, since the commitment to strong auth has an explicitly stated lifetime, while the consent to cross-port doesn't, it's possible for the end result to be that a client believes the server has consented to weak cross-port alternatives after the commitment has expired.

Several reasonable solutions exist:

- Move the duration out to an explicit "lifetime" member which details the time for which the entire structure can be treated as valid; "commit" would effectively become a flag.
- HTTP caching semantics might be used for the same purpose; "commit" still becomes a flag
- Explicitly state a desired mode of behavior (strong-auth only, same-host only, same-host or strong auth, etc.) and optionally a lifetime.  This is harder to extend in the future, but may be the clearest today.

**Comment by martinthomson** [comment]
This is a problem because the client might have a still-fresh copy of the http-opportunistic resource, but one that is now older than the `commit` field?  I actually think that is fine, but I would also be OK with the change to having an entry in the resource be more strongly typed (the first or third of your example solutions).

To eliminate one option, I don't think that caching semantics are something we want to tie too heavily into the semantics here.

**Comment by mnot** [comment]
My sense from the discussion in B-A was that we wanted to make things in the .well-known explicit. 

E.g., add something like:

    "http-over-tls": [443, 444]

to indicate that HTTP URIs can be used with TLS over ports 443 and 444.

This would also take care of #160.

Thoughts?

**Comment by mnot** [comment]
ping @MikeBishop @martinthomson

**Comment by mnot** [comment]
Please review changes above.

**Comment by MikeBishop** [comment]
I'm not sure that change resolves this issue.  It makes the list of alternatives explicit, but the fact remains that the list of acceptable alternative ports (which may be unauthenticated) lives perpetually (or for the lifetime of the .well-known response), while the commitment lives for a time-limited period.

I still think the cleanest solution here is a "lifetime" that applies to the whole response, and "commit" is a flag that remains true over the same lifetime.

**Comment by martinthomson** [comment]
That seems reasonable to me.

**Comment by mnot** [comment]
Remind me again - why are we not using freshness lifetime for this?

Also, I'm assuming that the change above is still a good thing (for #160)?

**Comment by mnot** [comment]
Straw-man:

~~~ example
{
  "http://example.com": {
    "tls-ports": [443]
  },
  "http://www.example.com:81": {
    "tls-ports": [],
    "tls-commit": 86400
  }
  "http:/other.example.com": {
    "tis-ports": [443,8080],
    "tls-commit": 3600
  }
}
~~~

Thoughts?

**Comment by martinthomson** [comment]
That works.  Each origin is mapped to a set of ports, and an optional commitment.

**Comment by mnot** [comment]
Not sure we closed the original issue here - confirm?

~~~
{
  "http://example.com": {
    "tls-ports": [443]
  },
  "http://www.example.com:81": {
    "tls-ports": [],
    "tls-commit": true
  }
  "http:/other.example.com": {
    "tis-ports": [443,8080],
    "tls-commit": true
  }
}
~~~

With some sort of lifetime mechanism. That could be a `lifetime` member, or it could be HTTP caching freshness lifetime.

If we have a `lifetime` member, I think we have to either a) require it on EVERY origin, or b) fall back to HTTP caching freshness lifetime.

I know my preference. @martinthomson?

**Comment by martinthomson** [comment]
Oh yeah, we lost the lifetime.  Can we just make tls-commit a time in seconds?

**Comment by mnot** [comment]
That's what's currently in the spec; see straw-man I made before you said "that works".

The problem is that doing so doesn't seem to address the original issue here.

**Comment by martinthomson** [comment]
Let me try to restate:

There is a possibility that we can have the following state:

* no reasonable assurances, because the `/.well-known/http-opportunistic` resource does not exist, but
* a commitment to strong authentication, which has been persisted from a previously-acquired resource.

It's tempting to say "well don't do that then".  The problem here is that the well-known resource is easy to block, which allows an attacker to force a client back to cleartext.  The point of creating the commitment is to make that attack impossible.

The freshness lifetime option is hazardous because it means that you potentially won't get queries for new copies on shorter timescales, though I guess you could require revalidation or something like that.

A single `lifetime` member at the top level or a lifetime for every alternative is better, I think.  You then don't have to reach down into caching details to make your decisions.  The only risk there is that - outside of any commitment - it creates a situation where the alternative is valid on paper (the lifetime hasn't expired), but it isn't available, but I guess that's no different to advertising an alternative that doesn't exist.

So, in the interests of a less brittle solution:

```js
{ "http://example.com": { "tls-ports": [443], "tls-commit": true, "lifetime": 1000 } }
```
