### ISSUE TITLE
Ben Kaduk's COMMENTs on proxy-status

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#1620]
- [x] Section 2.1.3

>  The "next-protocol" parameter's value indicates the ALPN protocol
  identifier [RFC7301] used by the intermediary to connect to the next
  hop.  This is only applicable when that connection was actually
  established.
>
>  The value MUST be either an sf-token or sf-binary, representing a TLS
  Application-Layer Protocol Negotiation (ALPN) Protocol ID (see

I do know about "h2c" and Upgrade, but I think there are cases where
neither TLS nor Upgrade is used.  Is there some way to indicate, e.g.,
that HTTP/1.1 without TLS was used?  I do not believe that setting
"http/1.1" here has those semantics in the way that "h2c" does, and it
seems that there may some value in indicating whether a secure transport
was used for the next hop in a similar way to how setting "h2" or "h3"
here would do so.

**Mark**: The simplest thing to do here would be to register `h1c`. Thoughts?

---

- [x] Section 2.1.3

>  [...] If the protocol
  identifier is able to be expressed as an sf-token using ASCII
  encoding, that form MUST be used.

There seems to be some ossification risk of the sf-binary form is never
used.  I would hope that the use of structured fields mitigates that
risk, since sf-binary support is needed in the generic field decoder,
but I don't know that I would specifically rely on it.  The MUST here
prohibits greasing to be sure; maybe the benefit of consistency
outweighs the risk, though.

**Mark**: I think the analysis is about right, and no change is necessary.

---

- [x] Section 2.3.13

TLS protocol errors are typically accompanied by a TLS alert message
being generated; would the 'alert-id' and 'alert-message' extra
parameters be applicable here (in addition to for "tls_alert_received"
down in §2.3.15)?

**Mark**: I think the intent here is that when an alert is received, `tls_alert_received` is more appropriate; this is a more general fallback, and we should clarify that. @PiotrSikora?

---

- [x] Section 2.3.15

>     -  alert-message: an sf-token containing the applicable
>        description string from the TLS Alerts registry.  See
>        [RFC8446].

I don't think there's a formal restriction on what characters are
allowed in description strings in the TLS Alerts registry, so that,
e.g., one could in theory have an alert description containing
characters like ";" that are not allowed in an sf-token.  It's so
unlikely to happen in practice that I'm not actually concerned, but I
will ask if we want to formally provide some behavior to allow for such
cases.

**Mark**: I'm inclined to change this to allow either `sf-token` or `sf-string`. @PiotrSikora?

---

- [x] Section 2.3.24

>     -  coding: an sf-token containing the specific coding that caused
>        the error.

Is it worth referencing the registry of such codings?

**Mark**: a723d43f

---

- [x] Section 4

[I included some suggestions for additional detail in the security
considerations in my PR, mentioned above]

It is probably worth saying something about how there is no E2E
validation of accuracy, e.g., a proxy could claim that it used a secure
h2 or h3 transport for the next hop even though it didn't actually do
so.

**Mark**: 81d1da1e

**Comment by mnot** [comment]
@kaduk please see questions above.

**Comment by PiotrSikora** [comment]
> I do know about "h2c" and Upgrade, but I think there are cases where
> neither TLS nor Upgrade is used. Is there some way to indicate, e.g.,
> that HTTP/1.1 without TLS was used? I do not believe that setting
> "http/1.1" here has those semantics in the way that "h2c" does, and it
> seems that there may some value in indicating whether a secure transport
> was used for the next hop in a similar way to how setting "h2" or "h3"
> here would do so.
> 
> **Mark**: The simplest thing to do here would be to register `h1c`. Thoughts?

@mnot one issue with registering `h1c` alone is that it then implies that `http/1.1` refers to requests sent over a secure transport, which is not always the case, since it currently refers to both. We might need to also register `h1`.

However, it appears that we're mixing transport and applicaton protocols, so perhaps we should include `next-transport` instead of trying to contain that information in the `next-protocol` field? I know this is a much bigger change, but it might be relevant with the recent work around QBONE/MASQUE, HBONE and other transport protocols providing multiplexed substrate for existing, potentially insecure, application protocols. Perhaps also `next-transport-is-secure` boolean?

Separately, I think the more generic question here is what if the next protocol isn't registered in the ALPN registry (e.g. there is a proprietiary protocol used across internal hops)? Should we allow free-form `sf-string`?

**Comment by PiotrSikora** [comment]
> TLS protocol errors are typically accompanied by a TLS alert message
> being generated; would the 'alert-id' and 'alert-message' extra
> parameters be applicable here (in addition to for "tls_alert_received"
> down in §2.3.15)?
> 
> **Mark**: I think the intent here is that when an alert is received, `tls_alert_received` is more appropriate; this is a more general fallback, and we should clarify that. @PiotrSikora?

Yes, `tls_alert_received` should be used for errors with TLS alert message, and `tls_protocol_error` is a more generic error type for errors without TLS alert.

Per section 2.1.1:
>   When sending the error parameter, the most specific Proxy Error Type
>   SHOULD be sent, provided that it accurately represents the error
>   condition.

**Comment by PiotrSikora** [comment]
> I don't think there's a formal restriction on what characters are
> allowed in description strings in the TLS Alerts registry, so that,
> e.g., one could in theory have an alert description containing
> characters like ";" that are not allowed in an sf-token. It's so
> unlikely to happen in practice that I'm not actually concerned, but I
> will ask if we want to formally provide some behavior to allow for such
> cases.
> 
> **Mark**: I'm inclined to change this to allow either `sf-token` or `sf-string`. @PiotrSikora?

I have hard time imagining that TLS Alerts Registry would add an alert that doesn't follow the existing `snake_case` style, and I imagine that allowing `sf-string` might result in a free-form text used here (instead of a verbatim copy of the `description` string from the TLS Alerts Registry), but I won't object if you want to allow it.

**Comment by kaduk** [comment]
> > The "next-protocol" parameter's value indicates the ALPN protocol
> > identifier [RFC7301] used by the intermediary to connect to the next
> > hop.  This is only applicable when that connection was actually
> > established.
> > The value MUST be either an sf-token or sf-binary, representing a TLS
> > Application-Layer Protocol Negotiation (ALPN) Protocol ID (see
> 
> I do know about "h2c" and Upgrade, but I think there are cases where
> neither TLS nor Upgrade is used. Is there some way to indicate, e.g.,
> that HTTP/1.1 without TLS was used? I do not believe that setting
> "http/1.1" here has those semantics in the way that "h2c" does, and it
> seems that there may some value in indicating whether a secure transport
> was used for the next hop in a similar way to how setting "h2" or "h3"
> here would do so.
> 
> **Mark**: The simplest thing to do here would be to register `h1c`. Thoughts?

As Piotr notes, the situation here is a bit messy.  There's also some bits in
here that might cause discomfort (at least for me) relating to using an ALPN
identifier in scenarios where the ALPN identifier is not actually used to negotiate
or activate the use of the corresponding protocol.  That is, even if I do speak
http/1.1 to the next hop over TCP, I didn't really "use the 'h1c' ALPN identifier"
to do so ... though saying that I "use the protocol identified by the 'h1c' ALPN
identifier" might avoid that concern.

So, I'm not opposed to registering 'h1c', but Piotr's `next-transport` suggestions
do seem interesting to me.  It also makes me wonder if we get a cleaner divide
between protocol and transport by using "HTTP version" rather than ALPN
token...though this would of course be problematic for non-HTTP next-hop
protocols.  I guess there's probably enough chance of non-HTTP next-hop
protocols to scupper that idea, but it's a thought.

**Comment by kaduk** [comment]
> TLS protocol errors are typically accompanied by a TLS alert message
> being generated; would the 'alert-id' and 'alert-message' extra
> parameters be applicable here (in addition to for "tls_alert_received"
> down in §2.3.15)?
> 
> **Mark**: I think the intent here is that when an alert is received, `tls_alert_received` is more appropriate; this is a more general fallback, and we should clarify that. @PiotrSikora?

I agree that when you receive an alert, `tls_alert_received` is more appropriate.
In cases where you don't receive an alert, but rather a malformed message or a message that indicates the peer only supports a set of parameters disjoint from what's locally supported, there is not a received alert, though, but the TLS implementation might generate an alert.  My comment was intended to refer to this latter case where an alert is sent as opposed to received.  Passing information about the alert that was generated might serve to supplement the knowledge that there was a TLS protocol error.

**Comment by mnot** [comment]
I've tried to clarify the relationship between `tls_protocol_error` and `tls_alert_received`; see 4b61857d.

If there are any other error types that would benefit from similar clarification of their relationships, please point them out.

**Comment by mnot** [comment]
I started a PR for `next-transport`, but became more convinced that it'd be more useful to talk about the crypto for the forward connection, some sort of `next-crypto` that could indicate its security properties. At least for now, ALPN identifiers clearly identify the transport protocol in use, but not necessarily its security properties. 

Does that make sense? if so, the question is how much detail to put in; it could be a boolean, or a protocol identifier w/ version, or even a cipher suite (although I tend to think that could/should be factored into a separate extension parameter in the future if needed).

Thoughts?

**Comment by mnot** [comment]
E.g., see #1628 - thoughts @kaduk @PiotrSikora ?

**Comment by MikeBishop** [comment]
I don't necessarily oppose the addition, but it feels strange to be adding new capabilities to a protocol during IESG review.

**Comment by kaduk** [comment]
Looking at #1628, it seems like this is a space where it's fundamentally hard to come up with an option that's generic to all or nearly all protocols a proxy might use to go forward to the next hop.
Given that at the HTTP layer we only really attempt to distinguish "secure" vs "not secure" for https/http scheme, maybe that's the only granularity we should try to expose here.  It's still not perfect, but maybe less likely to over-promise.

**Comment by mnot** [comment]
Something like `next-secure` is definitely simpler and safer. Will PR.

**Comment by mnot** [comment]
@MikeBishop's comments on both pull requests convince me that this is _tricky_, and shouldn't be designed at the last minute before shipping. There are many other aspects we don't talk about, such as cipher suite used; a future extension parameter can address this (and them, if desirable).

**Comment by kaduk** [comment]
Can we still get some clarification about whether `next-protocol` uses the ALPN token to refer to the corresponding protocol being used, vs. the actual ALPN token having been used?

**Comment by mnot** [comment]
The current intent is the former, since we're using e.g., `http11`. Is that problematic? If not, will clarify.

**Comment by kaduk** [comment]
(I don't see how using `http/1.1` implies that it has to refer to the protocol being used, since you can send "http/1.1" just fine in the TLS ALPN extension and there by have actually used the ALPN token, but) I think this would just mean saying "the ALPN protocol identifier of the protocol used by the intermediary to connect".  The current "ALPN protocol identifier used [...] to connect" would risk implying that the identifier itself (not the protocol it identifies) was used to connect, and thus, AFAIK, that TLS was used if "http/1.1" is indicated.  Unless there is some other way to convey the "http/1.1" ALPN identifier while connecting to the next hop that's not the TLS ALPN extension?

**Comment by mnot** [comment]
Having trouble fully interpreting that, but my current intent is to add something like this to the spec:

> Note that the APLN identifier is being used here to identify the protocol in use; it may or may not have been actually used in the protocol negotiation.

Does that help?

**Comment by kaduk** [comment]
Yeah, that would work.

https://github.com/kaduk/http-extensions/commit/81f6ab58b4ab3dda31d1b1cf0dca8ddf7c5e4bf3 is what I was proposing

**Comment by mnot** [comment]
Done.
