### ISSUE TITLE
[bcp56bis] recommend "fail safe" semantics for request header fields w.r.t. redirect

### ISSUE THREAD

**Issue by kaduk** [httpwg/http-extensions#1626]
Extracting from #1617 :

> > An application
using HTTP should specify if any request header fields that it
defines need to be modified or removed upon a redirect; however, this
behaviour cannot be relied upon, since a generic client (like a
browser) will be unaware of such requirements.
>
> Should we encourage the application designer to use "fail safe"
semantics for such request header fields in light of the non-guarantee
that application-specific requirements will be heeded? (Possibly in a
later section more focused on header fields or application state rather
than here.)
>
> Editor: That sounds like a substantial new text that would require more WG discussion. Perhaps in the next revision.

Sorry, I don't see how that's a useful justification for not considering a change.  It comes across as something like "once the document has left the WG, no further substantial change is possible", which makes a mockery of the IETF Last Call and IESG Evaluation stages of the document lifecycle.  If significant issues are raised after the document leaves the WG, we still address them, even if addressing them requires making changes that do require going back and having more WG discussion.  Issues that are not sufficiently significant can and do get pushed back to a later revision, but only after discussion and assessment of their severity/significance, a step that seems to have not happened (yet), here.

It seems like we could give some useful guidance here without getting too involved; it migh suffice to note that application designer should consider the risk of removal when choosing what the default semantics for the header field should be.  As this is "consider <topic>" advice rather than "do <specific thing> in <specific way>", it seems like the risk of getting it wrong is rather low.

**Comment by mnot** [comment]
I note that this document is now in the RFC Editor queue (and was when you opened this issue); you failed to challenge the reason given when it was in IESG evaluation (the revision history tells me that six days passed between my comment and this issue being opened). Also, I note that the issue you highlight was raised as a COMMENT, not a DISCUSS. By definition, COMMENTs are non-blocking.

I responded as I did because this is not a problem with the specification in terms of interoperability, security or function; it is a suggestion for additional content which you yourself characterise as 'guidance'. As such, I've handled it like any other suggestion by a participant at this stage in the process -- if it's an urgent fix (e.g., the spec has an actual flaw, the spec could be misunderstood), we fix it after WG and broader consultation as needed; if it's purely editorial, we fix it. This doesn't fall into either of those categories. It's asking us to consider and document something genuinely new that hasn't been discussed in the WG, at all. Hence, my reluctance to add text that might not reflect careful consideration and full consensus, or to delay publication unnecessarily.

Turning to the actual issue you raise - what you're looking for is documentation of what is arguably a general property of HTTP fields, not just those defined for APIs, and I note that we don't discuss it in the [most appropriate place for that](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#considerations.for.new.fields). 

However, I don't think this is specific to fields -- it's more a property that any application-specific extensions won't be understood or honoured by software that isn't aware of the application. That includes header and trailer fields, message content, and of course the URI.

We have a whole [BCP about URIs covering this topic](https://datatracker.ietf.org/doc/html/rfc8820), which is already mentioned in the spec. That's the case because there's a certain moral hazard involved; it's very easy to squat on URI name space and nothing immediately bad happens when you do. 

For fields and message content, perhaps there isn't any existing guidance because a person who attempts to rely on generic software understanding their application's semantics will immediately be faced with the reality of it not working; it's self-policing. As such, documenting this would be unsurprising to almost everyone and ignored by most, I suspect; I don't think it adds much value to the spec to point out the obvious. This issue was mentioned around redirection specifically because the behaviour of clients regarding headers in redirection has until recently been extremely poorly specified, with some variance in implementations. As a result, it seemed prudent to highlight this specific potential pitfall.

So I don't think adding specification text is the right outcome here, and am closing this issue. If you disagree, please request it to be reopened and we can take it to the working group list and/or IESG as @tfpauly and @fpalombini think appropriate.

Finally, I'll ask you to be more thoughtful about use of phrases like 'make a mockery' with regard to process. I don't think that's an appropriate characterisation of what's happening here. I do, however, have reservations about ADs inserting themselves into the process in a privileged way, regardless of good intent.

**Comment by kaduk** [comment]
Thank you very much for this thoughtful note; it more than addresses my previous concerns!
Your point about phrases like "make a mockery" is well-taken, as well.  To be clear: I was not ascribing that as intent, and agree that it's not what's happening here.
