### ISSUE TITLE
When SETTING deprecate H2 priority, is extensible priority mandatory?

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#1679]
Above, you indicate any scheme can be used, with this being just one option. 

This does make guidance about PRIO_UPDATE frames/header field more difficult later, so maybe some other textual adjustment is needed earlier:

e.g., for the remainder of this text ,we assume the use of the scheme defined in this document as the alternate

Or, move the following text from below up and adjust a bit 
> Where both endpoints disable RFC 7540 stream priority, the client is expected to
send this scheme's priority signal

_Originally posted by @rmarx in https://github.com/httpwg/http-extensions/pull/1601#r708087994_

**Comment by LPardue** [comment]
The text isn't amazingly clear if endpoints have to use Extensible priority when they explicitly disable H2 priority. I suggest we state they do. If anyone really wants to invent a new scheme, they will need to deal with negotiation.

**Comment by kazuho** [comment]
> The text isn't amazingly clear if endpoints have to use Extensible priority when they explicitly disable H2 priority. I suggest we state they do. If anyone really wants to invent a new scheme, they will need to deal with negotiation.

Yeah I see two somewhat contradicting statements:
* _Endpoints are expected to use an alternative, such as the scheme defined in this specification._
* _Until the client receives the SETTINGS frame from the server, the client SHOULD send both the HTTP/2 priority signals and the signals of this prioritization scheme (see Section 5 and Section 7.1)._

I would argue that the former is precise, and that the latter is a bit misleading in recommending endpoints send Extensible Priorities rather than _any_ alternative to H2 priorities.

The rationale is as follows.

In principle, negotiation is a hop-by-hop mechanism and therefore cannot be used for negotiating the use of an end-to-end signal, which includes the header-field variant of Extensible Priorities. To paraphrase, in a world where end-to-end signals are used for prioritization, multiple signals are expected to co-exist.

IMO, SETTINGS_DEPRECATE_RFC7540_PRIORITIES is no more than an optimization, that allows clients to conserve bandwidth (by omitting the PRIORITY frames), servers to reduce complexity (by ignoring PRIORITY frames being received). These benefits are stated correctly in the section.

**Comment by LPardue** [comment]
Thanks Kazuho. I tend to agree. The thing I also wanted to avoid is endpoints disabling RFC 7550 stream priority and then not providing any suitable replacement by accident. I think there is agreement that not doing scheduling is pretty bad. But we also highlight that other inputs, beyond this scheme and beyond anything that would be standardised are fine to use too.

I'm getting an idea of how we could change the text to address the points made on this issue.

**Comment by LPardue** [comment]
Reading again the current text

> Where both endpoints disable RFC 7540 stream priority, the client is expected to
send this scheme's priority signal. Handling of omitted signals is described in
{{parameters}}.

This is effectively a differently worded restatement of the guidance for implementers of Extensible Priorities 

> This document defines the urgency(`u`) and incremental(`i`) parameters. When
receiving an HTTP request that does not carry these priority parameters, a
server SHOULD act as if their default values were specified.

That is, imagine both endpoints send SETTINGS_DEPRECATE_RFC7540_PRIORITIES and a client wants the default prioritization for a request (u=3,i). It can omit the Priority header field and have some expectation that a server implementing Extensible priorities will interpret that as a signal to apply the default.

The simple action here is to make SETTINGS_DEPRECATE_RFC7540_PRIORITIES independent from any advice to use a specific alternative.
