### ISSUE TITLE
save-data extensibility

### ISSUE THREAD

**Issue by hardie** [httpwg/http-extensions#168]
I understand that the current method has the save-data aspect of client hints as a simple on/off switch.  I wonder, though, about the willingness to consider allowing for some extensibility.  Right now, someone saying "save-data=on" is signing up for pretty much anything.   Separating acceptance of data saving for different elements, e.g. agreeing to smaller video resources but not lower fidelity audio, seems like it may be useful.  I suggest that the working group consider making this an extensible field with "save-date=all" as the default, with semantics matching the current "save-data=on".  Then later extensions can be specified for more granular statements.

**Comment by igrigorik** [comment]
I think we can already achieve this with current definition:

- We can define other tokens
- We can define parameters - e.g. "on;video-only", etc.

Changing from "on" to "all" doesn't really change anything. Also, we already have both client and server implementations that are relying on "on". 

_p.s. some background: https://github.com/igrigorik/http-client-hints/pull/63/commits/e8bafcf5702e23a4052905137a741274e80d602b_

**Comment by mnot** [comment]
@hardie - any further comment?

**Comment by hardie** [comment]
I think the parameter method would be quite useful, and if the doc describes that it would be useful.  I'm less sanguine about introducing parameters later, but I certainly wouldn't fall on any sharp objects if that were the decision of the WG.

**Comment by igrigorik** [comment]
I guess we _should_ clarify that it is extensible and define "on" as one of its recognized values...

```
Save-Data = "Save-Data" ":" save-data-token *( ";" [ token ] )
            save-data-token = "on"
```

Does that make sense? I'm sure my ABNF is off.. :)

**Comment by hardie** [comment]
On Wed, May 4, 2016 at 9:36 AM, Ilya Grigorik <notifications@github.com>
wrote:

> I guess we *should* clarify that it is extensible and define "on" as one
> of its recognized values...
>
> Save-Data = "Save-Data" ":" save-data-token *( ";" [ token ] )
>             save-data-token = "on"
>
> Does that make sense?
>
That does make sense.  I think you need a way to define how someone gets a
token value created, and then register "on" as the first token value.

regards,

Ted

**Comment by igrigorik** [comment]
Resolved via #179.

**Comment by vfaronov** [comment]
Is there a reason to use semicolon here instead of the more typical comma?

Also, the grammar does seem off: it does not allow whitespace (because the “implicit `*LWS`” rule of RFC 2616 no longer applies), and it uses `:` instead of `=`. Assuming you really want semicolons, I think it should be:

         Save-Data = sd-token *( OWS ";" OWS [sd-token] )

(I can file a separate issue if you want)

**Comment by reschke** [comment]
I wouldn't say comma is "typical" -- it depends a bit on the use case. For instance, alt-svc uses a list of comma-delimited directives, each of which can have semicolon delimited parameters.

In any case, if this does not use commas, the spec ought to state what happens when commas turn up in a field value, or if a field occurs multiple times in a messages (this is stated for the other client hints).

**Comment by igrigorik** [comment]
> I wouldn't say comma is "typical" -- it depends a bit on the use case. For instance, alt-svc uses a list of comma-delimited directives, each of which can have semicolon delimited parameters.

That, indeed, was the intent - e.g. "on;video-only". 

Re, OWS: good catch. Addressed in https://github.com/httpwg/http-extensions/pull/190.
