### ISSUE TITLE
Intermediaries modifying Priority header fields

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#1715]
>  If intermediaries want to specify prioritization on a multiplexed HTTP connection, they SHOULD use a PRIORITY_UPDATE frame and SHOULD NOT change the Priority header field.

Recommendations like this generally need more discussion about why this might be a good idea.  Otherwise, they will be ignored.  It seems to me like this is a great example of a recommendation that an intermediary will be happy to ignore.

**Comment by ianswett** [comment]
Conceptually, I prefer the idea that intermediaries should use the frame and endpoints should use the header, because the frame is a connection-level concept and the header is end-to-end.  The practical benefit of this is that if I had an h2/h3 backend connection as an intermediary that I put requests on from multiple different users, I'd probably want to pick the priority myself, but the backend/AFE may want to know and use the client's original priority.

**Comment by martinthomson** [comment]
So it's nice that you have this clean conception of what intermediaries SHOULD do and how we can accommodate good practices.  How does reality fit into this?

**Comment by kazuho** [comment]
@MikeBishop 
> Right -- the header shows what the client originally wanted, and the frame shows what the peer on this hop wants; if those are different entities, it's better to keep them separate.

I'm not sure if I agree with the characterization here. While it is true that headers are end-to-end, that does not necessarily mean that intermediaries should preserve those values when forwarding requests. An example here is caching proxies setting, changing the If-Modified-Since header when they translate a request to a conditional GET for a response that it has a cached copy.

I totally agree that_if_ the is to send a hop-by-hop signal then it should send a PRIORITY_UPDATE frame. 

But is there a reason to discourage intermediaries from sending an end-to-end signal?

Consider the case of an CDN that uses server-side knowledge to adjust client-driven priority. When forwarding a request for which the CDN has decided to change the priority, it would be make more sense to send a header-based signal, to make sure that hops near the origin would respect the adjusted value, regardless of the number of hops to the origin.

**Comment by ianswett** [comment]
In terms of what people do, I'm not sure we have quite enough experience to be sure.

Possibly we should soften the SHOULD and say that if the intermediary only intends to provide a prioritization signal for this connection, it SHOULD use PRIORITY_UPDATE because that preserves the client's original intent, and then explain the implications of intermediaries changing the value, and possibly why they might do so?
