### ISSUE TITLE
Server advertise support for extended CONNECT but does not support websocket as a :protocol

### ISSUE THREAD

**Issue by ddragana** [httpwg/http-extensions#1773]
I think this is an issue. and we need graceful way to fall back to fallback. 

I do not believe that HTTP_1_1_REQUIRED and 421 response code are the right solution.

I think it would be good to make this part of WebSockets over HTTP3 spec.

edit: remove double negation -> I think that   HTTP_1_1_REQUIRED and 421 response code are not the answer.

**Comment by DavidSchinazi** [comment]
The server could just close the stream with H3_VERSION_FALLBACK. Is that not sufficient?

**Comment by MikeBishop** [comment]
Perhaps for WebSockets, but there's a more general question here.  When a client uses Extended CONNECT with an unknown protocol, what is the correct failure mode?  There's no guarantee that HTTP/1.1 would support an arbitrary requested protocol, even if it might be more likely to work with WebSockets.

**Comment by DavidSchinazi** [comment]
I'm not sure we need a general solution, because it isn't clear that we have a general problem. The answer here will depend on why the client is using this protocol in the first place. For example with MASQUE, the client will know which proxy to connect to thanks to out-of-band configuration, so the proxy operator is responsible for ensuring its HTTP servers are in sync with its config servers. For WebSocket on the other hand, the issue is that WebSockets were originally designed for h1 and there exist servers that are gradually deploying h2 or h3 for GET but don't yet support WebSocket there. For those, H3_VERSION_FALLBACK should be sufficient.

**Comment by MikeBishop** [comment]
> For example with MASQUE, the client will know which proxy to connect to thanks to out-of-band configuration, so the proxy operator is responsible for ensuring its HTTP servers are in sync with its config servers.

That's nice in theory.  We should still say what happens when the proxy operator makes a mistake.

**Comment by DavidSchinazi** [comment]
> We should still say what happens when the proxy operator makes a mistake.

Why is this specific to extended CONNECT then? A server operator could make a mistake and end up with some GET resources not working on h3 too, right?

**Comment by LPardue** [comment]
The example I would use here is a server that  supports masque on H3 and H2 CONNECT. If for some reason a proxy operator gets desyncd with the config that it may or may not be responsible for, then things could go wrong. In a scenario where version fallback to HTTP/1.1 is not desirable, articulating such an error is underspecified.

Similarly for H2 and H3 websocket, telling client the resource is not available or the stream was reset with the fallback error code is misinformation.

**Comment by mnot** [comment]
`501 Not Implemented`+ a header describing why?

**Comment by ddragana** [comment]
Yes, that should work. This should be in the spec.

**Comment by RyanTheOptimist** [comment]
Sent out https://github.com/httpwg/http-extensions/pull/1823 to address
this using the 501 response code recommendation.
