### ISSUE TITLE
clearer advice on server interpretation

### ISSUE THREAD

**Issue by icing** [httpwg/http-extensions#1794]
In rfc7540, the 'exclusive' priority description gave explicity advice on when it needs to be disregarded:

```
rfc7540 5.3.1
 ...
 Inside the dependency tree, a dependent stream SHOULD only be
 allocated resources if either all of the streams that it depends on
 (the chain of parent streams up to 0x0) are closed or it is not
 possible to make progress on them."
```

I feel the new priorities draft is not explicit enough on this and implemenations might misinterpret its requirements as in

```
draft: 10.
 Therefore, non-incremental responses of the same urgency SHOULD 
  be served in their entirety, one-by-one, based on the stream ID[...]
```

I propose to change:

```
draft 10.
 It is RECOMMENDED that, when possible, servers respect the 
urgency parameter (Section 4.1), sending higher urgency  responses 
before lower urgency responses.
```

to

```
 Connections SHOULD be progressed whenever response data is available 
 and urgency/incremental information MUST not prevent use of downstream 
 bandwidth. Given that, it is RECOMMENDED that servers respect the urgency 
 parameter (Section 4.1), sending higher urgency  responses before lower 
 urgency responses.
```

**Comment by LPardue** [comment]
So IMO RFC 7540 had to say what you quoted because it had the explicit flag. Extensible priorities is a lot less rigid in the relationship between requests. 

I'm not a fan of the suggestion to say "urgency/incremental information MUST not prevent use of downstream 
 bandwidth" because 1) it is a strong requirement (MUST), which is opposed to the general theme of section 10 and 2) it is not clear which actor the requirement is levied upon.

As an alternative suggestion, we could add some more flavour text to highlight that it is generally more beneficial for servers to fill the pipe's bandwidth than let it go quite do to any combination of scheduling decisions whether based on the RECOMMENDations in the section or not. That could be something like a new paragraph at the top of section 10 like

```
Server scheduling determines how connection resources such as bandwidth are used. It is generally beneficial for the server to maximise its use of available bandwidth when serving concurrent requests. Therefore, use of bandwidth is one form of input to a prioritization process that considers other inputs. This section describes considerations that servers make when scheduling.
```

**Comment by kazuho** [comment]
Rereading this issue, I think that the existing text could be misinterpreted in several ways:
* that once the server has started sending a non-incremental response of low urgency, it should continue sending it until the end even when a response of higher urgency becomes available to the server (point raised by @icing),
* that when the non-incremental response cannot fulfill the bandwidth, other responses of same or lower urgency should be sent as well (point raised by @LPardue).

At the moment, both @LPardue's and my text being proposed in #1803 fixes the latter, but not the former.

For the former, I think the question is if we need phrases like "one-by-one" or "entirety." I would argue that maybe changing:
> Therefore, non-incremental responses of the same urgency SHOULD be served in their entirety, one-by-one, based on the stream ID, which corresponds to the order in which clients make requests.


to
> Therefore, non-incremental responses of the same urgency SHOULD be served in the ascending order of the stream ID, which corresponds to the order in which clients make requests.

**Comment by LPardue** [comment]
Not sure why I reopened this issue back in December, it was resolved by the linked PR.
