### ISSUE TITLE
Client scheduling applies to what message?

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#1868]
Section 9 says:

> A client MAY use priority values to make local processing or scheduling choices about the requests it initiates.

Bob Briscoe asked if this is supposed to be "responses to the requests that it initiates". Another interpretation could be that it applies to both requests that are sent and responses that are received.

**Comment by kazuho** [comment]
It has always been my position that this applies to requests.

To be specific, this statement matters to intermediaries that forward requests to backend servers, especially when the request-level concurrency to back-end servers is smaller than that of the front-end connection. In such deployment, pending requests can get queued up within the intermediary. Then, when picking up the next request to be forwarded from that queue, it makes sense to pick up one that has the highest priority.

This does not matter a lot to end clients, because end clients do not need to (or probably not use) the signalling method being defined by a standardization organization that governs protocols but not internal behaviors.

**Comment by bbriscoe** [comment]
The subject of the sentence is the client, not intermediaries.

**Comment by kazuho** [comment]
In [HTTP terminology](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#terminology), intermediary is a node that acts as both client and server, forwarding HTTP messages.

What I argued in my previous comment is that existing text is correct to cover both user agents (i.e., clients that initiate requests) and intermediaries (clients that forward request), but it matters more to the latter.

**Comment by bbriscoe** [comment]
Of the 84 occurrences of 'client' in the draft, I suspect a number were actually intended to mean 'user agent'. This one in §9 seems to be one of them, because in §5 it says
> Guidance for how endpoints can act on Priority header
> values is given in Section 10 and Section 9." 

Also, I noticed that there is a list of [Considerations for New Fields](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#considerations.for.new.fields) in §16.3.2 that would have been useful to follow for the new Priority field.

**Comment by LPardue** [comment]
Why do you think it wasn't?

**Comment by bbriscoe** [comment]
I don't understand whether you are referring to the first half of my previous posting (before 'Also') or the second. And whichever you mean, I don't see what you really mean. Can you elaborate pls?

**Comment by LPardue** [comment]
The latter half of your comment seemed to imply that the considerations for new header fields were not taken into Priority. We did and I don't see on what grounds that implication holds, so I was asking.
