### ISSUE TITLE
Signatures: Content-Digest syntax mismatch

### ISSUE THREAD

**Issue by yaronf** [httpwg/http-extensions#2000]
The syntax for `Content-Digest` in the signatures draft uses the structured field syntax (surrounds the Base64 value by two colons), but draft-ietf-httpbis-digest-headers-07 doesn't have these colons.

```
Content-Digest: sha-512=:WZDPaVn/7XgHaAy8pmojAkGWoRx2UFChF41A2svX+T\
  aPm+AbwAgBWnrIiYllu7BNNyealdVLvRwEmTHWXvJwew==:
```

**Comment by LPardue** [comment]
We have moved digest fields to use structured fields and the next draft will use the Byte Sequence type for all field values. This was just an unfortunate matter of timing.

**Comment by jricher** [comment]
Yes, I preemptively updated the examples used in our generator script based on the direction the digest headers draft is going in the editors copy. GNAP core -09 has the same syntax in its examples (since the example generators share code between these two): https://www.ietf.org/archive/id/draft-ietf-gnap-core-protocol-09.html#name-http-message-signing

Closing since this has been changed in the editor's copy of of digest and does not need to change in signatures.
