### ISSUE TITLE
trouble following "that overrides that"

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#2003]
[Section 4](https://www.rfc-editor.org/authors/rfc9218.html#section-4):  We had trouble following "that overrides that".  To what does the second "that" refer - the client's signal or something else?  It is also not clear to us what is performing these actions.

Original:

     Sending a
     PRIORITY_UPDATE frame preserves the signal from the client carried by
     the Priority header field, but provides a signal that overrides that
     for the next hop; see [Section 14](https://www.rfc-editor.org/authors/rfc9218.html#section-14)

Possibly (highlighting what is sending the frames):
 An intermediary can send a
 PRIORITY_UPDATE frame to preserve the signal from the client that is 
 carried by the Priority header field; however, the next hop can send 
 a signal that overrides the client's signal; see [Section 14](https://www.rfc-editor.org/authors/rfc9218.html#section-14)

**Comment by LPardue** [comment]
Interesting. Ben Kaduk raised a comment about text in this paragraph during the IESG review. The current text is our attempt to make things clearer, done via https://github.com/httpwg/http-extensions/pull/1880

We can try to clarify further but I don't think the RFC editors suggestion is suitable because it changes the intent of who changes what. How about an alternative along the lines of:

> Intermediaries can consume and produce priority signals in a PRIORITY_UPDATE
frame or Priority header field. An intermediary that passes only the Priority header field
on to the next hop, preserves the original end-to-end signal from the client; see {{header-field-rationale}}.
An intermediary could pass the Priority header field and additionally send a
PRIORITY_UPDATE frame. This would have the effect of preserving the original 
end-to-end signal, while instructing the next hop to use a different priority; per the
guidance in {{frame}}. An intermediary that replaces or adds a Priority header field to
requests overrides any signal from a client, which can affect prioritization for all 
subsequent recipients.
