### ISSUE TITLE
Specify how origin frames interact with Altsvc

### ISSUE THREAD

**Issue by siyengar** [httpwg/http-extensions#214]
It seems like we should filter against the original origin when using alt-svc and we should specify this in the origin frame draft

**Comment by mnot** [comment]
Hey Subodh - could you expand upon this a bit more?

**Comment by siyengar** [comment]
Ya I was wondering if clarification was needed on the indented behavior origin frames with altsvc

With altsvc you can point origin1 -> origin2. Should the filter on the origin frame apply to origin1 or origin2. My understanding is that intention is to apply it to origin1, but want to make sure that's correct.

**Comment by mnot** [comment]
Ah. What you get in an alternate service is "below" what happens at the "origin" layer -- it isn't a new origin. I'll try to clarify, thanks.

**Comment by mnot** [comment]
Current draft has:

> Finally, servers that allow alternative services {{?RFC7838}} will need to explicitly advertise
those origins when sending ORIGIN, because the default contents of the Origin Set (as per {{set}})
do not contain any Alternative Services, even if they have been used previously on the connection.

I think this addresses the concern.

**Comment by martinthomson** [comment]
"those origins" might be better stated as "origins that have alternative services"

**Comment by mnot** [comment]
I changed it to:

> Finally, servers that host alternative services {{?RFC7838}} will need to explicitly advertise
their origins when sending ORIGIN, because the default contents of the Origin Set (as per {{set}})
do not contain any Alternative Services' origins, even if they have been used previously on the
connection.

... about five minutes ago. Good enough?

**Comment by martinthomson** [comment]
Absolutely!

**Comment by enygren** [comment]
I'm not sure "because the default contents of the Origin Set (as per {{set}}) do not contain any Alternative Services' origins" is accurate.  Even with the current text, an Alt-Svc to a different server name but default port will be in the default set if it is what is used to establish the connection.  (ie, SNI is the Alt-Svc's origin and port is the default.)

The cases where this is relevant is when:

* Connections are being coalesced  (i.e., the Alt-Svc server name shares an IP address and port with an origin).  This can happen in the reverse, still making the new text here somewhat misleading.  If the connection from the Alt-Svc is opened first and then another with origin hostname tries to coalesce onto it, the SNI will be from the Alt-Svc origin hostname.  In this case, the SNI would be origin1.
* The weird issue with #331 and ports
