### ISSUE TITLE
digest: document structure

### ISSUE THREAD

**Issue by reschke** [httpwg/http-extensions#2172]
Section 1.1 is currently a bit confusing, because it leaves out sections, and does not present them in order (likely the cause of a recent re-org).

**Comment by ioggstream** [comment]
@reschke do we need it?

**Comment by reschke** [comment]
it should either make sense, or should be removed.

**Comment by ioggstream** [comment]
@LPardue if it's not required, I think that the document is fine without.

**Comment by LPardue** [comment]
mnot asked us to add one a while back, which I think helped at that point. 

Editorial changes in the meantime have had an effect though, so I tried to add some colour to the structure in https://github.com/httpwg/http-extensions/pull/2213. 

The intention is that people can launch of from here to focus on bits they might need, like the field definitions or example. Since security and IANA sections are standard, mentioning them seems superfluous. 

If the opinion is that the proposal doesn't help, let's just remove the section.
