### ISSUE TITLE
Case sensitive matching of the `__Secure-` and `__Host-` cookie prefixes leads to bypasses for insecurely implemented servers

### ISSUE THREAD

**Issue by ddworken** [httpwg/http-extensions#2231]
Cookie names are case-sensitive, which means that `Foo` and `foo` are different cookies. Many frameworks incorrectly treat cookie names as case-insensitive. This is a bug, but a seemingly common one (see below). This incorrect behavior is generally not noticed or not promptly fixed because it is unlikely that a service would have both a `Foo` and a `foo` cookie. 

But the way that this buggy behavior interacts with cookie prefixes leads to a bypass of the protections offered by cookie prefixes. Specifically, suppose that a service uses a cookie `__Secure-foo` and relies on this cookie having the `secure` flag and being set by a secure page. An attacker can then set the cookie `__secure-foo` cookie without the `secure` attribute. This will be seen by a buggy backend as equivalent to a `__Secure-foo` cookie, thereby bypassing the protection that they were aiming to achieve. 

It seems to me like this would be a relatively easy tweak to make to the spec. We could change it so that cookie prefixes are case-insensitive so that `__Secure-foo` and `__sECuRe-foo` are both treated as having the prefix (but are otherwise treated as different cookies). Cookie attributes are case-insensitive, so it makes sense to me that prefixes could be treated the same way. 

As evidence of this being a common mistake, see:

* https://github.com/dotnet/runtime/issues/62778
* https://github.com/dart-lang/sdk/issues/11011
* https://docs.oracle.com/javase/8/docs/api/java/net/HttpCookie.html#equals-java.lang.Object-
* https://github.com/laravel/framework/issues/1639
* https://github.com/curl/curl/commit/0336a548f1d969aae5fc92ce22ad177a36f971fc

**Comment by sbingler** [comment]
Thanks for the issue!

Are you aware of any instances of this happening in the wild? I.e. servers understanding cookie prefixes but treating them case insensitive?

@mikewest Was any consideration given to case sensitivity when [draft-ietf-httpbis-cookie-prefixes-00](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-cookie-prefixes-00) was being discussed?

**Comment by ddworken** [comment]
> Are you aware of any instances of this happening in the wild? I.e. servers understanding cookie prefixes but treating them case insensitive?

This can actually be an issue even without servers understanding cookie prefixes. The core risk here is that a service is using a prefixed cookie (with the goal of preventing session fixation attacks) but that the underlying framework treats cookies case insensitively leading to a bypass of the defense offered by cookie prefixes. This previously applied to Dart and Laravel, and I believe still applies to dotnet and any java servers using `java.net.HttpCookie`.

**Comment by mikewest** [comment]
> @mikewest Was any consideration given to case sensitivity when [draft-ietf-httpbis-cookie-prefixes-00](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-cookie-prefixes-00) was being discussed?

I don't recall any, and didn't find any in a quick search. Exact string matches are fast and simple and certainly my preference, but if there's evidence that frameworks and services have mistakenly parsed cookie names more loosely, there's little harm in matching their behavior.

**Comment by sbingler** [comment]
Thanks, seems like a security positive change to me then.

**Comment by sbingler** [comment]
@johnwilander FYI

**Comment by martinthomson** [comment]
In retrospect, this is fairly obvious.  Even though cookies are preserved as case-sensitive by browsers, they might be consumed (and matched) by case-insensitive code.  As the server produces and consumes the value, that is their prerogative.  That this extended to prefix-checking is no real surprise.  I'm supportive of making the change.

Does anyone know if there is any meaningful use of the prefix with case variants?  I'd say no on the basis that the prefix was optimized for a low rate of collisions with existing use, but maybe the original checks were narrowly targeted to the specific casing that was chosen.

**Comment by sbingler** [comment]
> Does anyone know if there is any meaningful use of the prefix with case variants?

I did a quick query against HTTP Archive, `httparchive.requests.2022_08_01_desktop`:

- 188030 cookies (case-insensitively) matched `__Secure-` or `__Host-`
- Of those, 543 cookies did **not** case-sensitively match `__Secure-` or `__Host-`. I.e.: They're case variants

583/188030 ~= 0.29%

All the case variants I saw were either all lower case or all upper case.

Of those, 43 cookies did not conform to the requirements of the cookie prefixes and would be rejected by UAs with this change.

**Comment by dveditz** [comment]
> Of those, 43 [out of the 543] cookies did not conform to the requirements of the cookie prefixes and would be rejected by UAs with this change.

To make it more explicit, 0.02% of the cookies in this sample that are currently working perfectly fine (albeit without the protection the site devs think they're getting) will stop working. There's a good chance these are important cookies if they went to the trouble of adding prefixes. The remaining 0.27% cookies that thought they were getting protection but currently aren't would be improved by this proposed change.

43 is a small enough number that our web compatibility teams could try to reach out. I'm sure there are additional sites that aren't captured by the HTTP Archive—especially any that only use prefixes for cookies after a user has logged in—but it would be a start.

I was hoping the Java 8 documentation link in the first comment was "just old" (it doesn't reference rfc6265, only rfcs 2109 and 2965), but [Java 18 is identical](https://docs.oracle.com/en/java/javase/18/docs/api/java.base/java/net/HttpCookie.html#equals(java.lang.Object)).

Cookie prefixes are pseudo-attributes, hacked into the cookie name in the interest of letting sites deploy them quickly without having to wait for server software stack upgrades to support a new attribute. They became default case-sensitive because we treat names that way (now), but it's perfectly reasonable to treat them case-insensitively the same as other attributes.

The old specs defined cookie names as just another `attr`, and explicitly said "Attributes (names) (attr) are case-insensitive."  There seems to be a lot of server software that has taken RFC 2109 to heart. Given the authorship of the specs it's possible Netscape Navigator behaved this way, but I can't find any evidence Gecko ever did. IE7 definitely had case-sensitive cookie names, and I can't imagine it differed from IE 6 or IE 5.  Following browsers, rfc6265 talks about "same name" matching but doesn't explicitly say "case-sensitive" even though the algorithm it defines gives you that result. The fact that it is rather explicit about case-**IN**sensitive matches for all the other attributes individually should have been a clue. Maybe if you came at it from an rfc2109 bias the difference wouldn't jump out at you.

**Comment by sbingler** [comment]
> 43 is a small enough number that our web compatibility teams could try to reach out
Agreed, those 43 cookies are produced by 16 sites in the dataset so even easier!

Based on the replies in the thread so far I'm going to modify RFC6265bis to require case insensitive matching by UAs.
Servers should continue to assume (those that are, anyway) that UAs are case sensitive for backwards compatibility.
