### ISSUE TITLE
how are matrix parameters and range requests handled?

### ISSUE THREAD

**Issue by mooreb** [httpwg/http-extensions#2248]
I had hoped that matrix parameters would be discussed in one of sections 2.2.7, 2.2.8, 2.2.9

I have internal applications that produce and consume URLs like:
  `/foo;version=1/manifest`
as described in:
  https://bitwise.blog/MatrixParams/

I had hoped that range requests:
  https://www.rfc-editor.org/rfc/rfc9110#name-range-requests
would be discussed in your rfc.

**Comment by reschke** [comment]
From HTTP's point of view, they do not matter. They are just something that can occur in a path.

FWIW, the same is true for "regular" query parameters; their syntax definition is not part of HTTP.

**Comment by mooreb** [comment]
Thank you very much Julian. I appreciate your prompt response very much.

I think my question was not very clear; please allow me to attempt to be a little more crisp.

I'm seeing that the rfc takes care to deconstruct "regular" query parameters into @query-param in section 2.2.9. I'm wondering if matrix parameters will (or should?) get the same treatment.

I'm also thinking about the ordering of matrix parameters and "regular" query parameters; are they always considered left-to-right, textually, in the order of the original URL? Will matrix parameters merge into the regular query parameters? form a separate namespace? be omitted from the rfc?

**Comment by reschke** [comment]
The core specs (RFC 911x) do not define the syntay of query parameters.

You are now referring to the mesage-signatures draft, right?

**Comment by mooreb** [comment]
Hi Julian,

Thank you again.

yes, sorry, I am referring to the message signatures draft. I am sorry for not being more explicit about that; there's a lot going on in this repo.

**Comment by jricher** [comment]
There is no derived component defined for matrix parameters. Name-value parameters from the HTTP URL spec are supported because they're an extremely common case. It's slightly controversial because they aren't part of HTTP proper (as @reschke mentioned) but that's a detail lost on most developers so we tried to carefully put them in. If someone wanted to write an extension to do the same thing with matrix parameters, they could do that and register a new derived component to handle it. But, I don't see a compelling reason to add something special for it.

In all of these cases, you can just sign the query string directly without parsing it out, which is both safer and more in line with the core HTTP docs.
