### ISSUE TITLE
Non-cachable HEAD responses

### ISSUE THREAD

**Issue by Acconut** [httpwg/http-extensions#2294]
In a message to the mailing list (https://lists.w3.org/Archives/Public/ietf-http-wg/2022OctDec/0006.html), Austin Wright (@awwright) voices concerns of the inability to cache HEAD responses from the Offset Retrieving Procedure:

> GET/HEAD is supposed to be cachable (and so returning a client-specific Upload-Offset would be dubious)

In fact, the current draft -00 recommends the server to disallow caching the response header:

> The response SHOULD include Cache-Control: no-store header to prevent HTTP caching.

Is this a conflict between the intended usage of HEAD requests and its actual usage inside resumable uploads? Or is this not a problem?

**Comment by jrflat** [comment]
I don't think this is a huge conflict, but if we are concerned we could potentially look into something like a RESUME method like Austin suggests in his email. I also think the "non-intended" usage of HEAD is mitigated when using server-generated URLs rather than client-generated token (#2292). It feels more natural to respond to a `HEAD /upload/unique-identifier` with an `Upload-Offset`  header as opposed to responding to `HEAD /upload` with different `Upload-Offset` values based on the clients' tokens.

If a middlebox doesn't abide by the `Cache-Control: no-store` rule, having the unique server-generated paths would at least isolate the issue to a single upload session. The client also has the chance to get at least 1 valid `Upload-Offset` from the server before running into issues with a cached value. If the client receives the cached value later at some point and tries to resume, it would get a `409 Conflict`, so maybe the client could just retry the upload entirely at which point it receives a new upload URL? We could also just recommend using HTTPS.

**Comment by Acconut** [comment]
I agree that there seems to be little concerns about this issue, so we can close it for now.
