### ISSUE TITLE
explore solution space for non-ASCII characters in Strings

### ISSUE THREAD

**Issue by reschke** [httpwg/http-extensions#2343]
RFC 8941 does not support non-ASCII characters in sf-string (but recommends to use sf-binary when non-ASCII characters are needed).

The solution space is roughly:

1. No support at all
2. No support, but addings hints about workarounds, such as
2.1 Using sf-binary (approach in RFC 8941)
2.2 Using RFC8187 parameter encoding (works only for parameters at it uses the "*" marker)
2.3 Using an escaping mechanism inside sf-string (with out-of-band info to indicate that it is in use) - currently proposed for the "Problem" header field (see https://github.com/ietf-wg-httpapi/rfc7807bis/commit/ebf9465504713876e6cd507629511313bdbce39c)
3. Direct support
3.1 By extending sf-string to allow native UTF-8
3.2 By extending sf-string to support a new escaping mechanism (for instance, by introducing new backslash escapes)
3.3 By adding a new type ("sf-ustring") that somehow supports non-ASCII codepoints (NOTE: this used to say "characters")

Note that the question whether non-ASCII octets appear in the field value (obs-text) is somehat orthogonal, expect if 3.1 would be chosen.

**Comment by bsdphk** [comment]
Your point 1 is disingenious and misleading: As long as we allow two distinct glyphs in sf-string, people can transfer any bit-sequence they want to with it and sf-binary allows the to transfer any byte sequence.  Please remove it.

Anything which changes the definition of `sf-string` is a hard no from me, because:

A) It will dilute retrofit
B) It will enable emojis in `sf-string` by default, unless spec-writers explicitly forbid them.

There goes your 3.1 and 3.2.

Anything which requires general-purpose SF serializers or parsers to know anything about time-variant registries of human politics or other foibles, for instance MIME, UniCode, Codepages, TimeZones, LeapSeconds etc. are a hard no from me, as a matter of principle.

That takes 3.3 out, because without access to a registry, there is no way to tell what might or might not be a "character".

For all I care, people can use any of your 2.1, 2.2 or 2.3, or anything else they come up with.

If anything need to be said about that, it should obviously be said in RFC8187(bis) since it already occupies precisely that topic on the standards track.

In particular I do not want 2.3, not even as an appendix, because of the risk that it "leaks" and `%xx` unintentionally is interpreted in places where that is not explicitly allowed (See also: The "../" hole, Log4J, etc.)

So with all due respect Julian:  Stay in your lane, this stuff belongs in your own RFC, not in SF

**Comment by reschke** [comment]
> Your point 1 is disingenious and misleading: As long as we allow two distinct glyphs in sf-string, people can transfer any bit-sequence they want to with it and sf-binary allows them to transfer any byte sequence. Please remove it.

Not helpful. If we follow that line of argument to the end, we just need sequences of "0" and "1", and the whole idea of "structured header fields" is useless.

> Anything which changes the definition of sf-string is a hard no from me, because:
>
> A) It will dilute retrofit

That's an interesting point.

> B) It will enable emojis in sf-string by default, unless spec-writers explicitly forbid them.

I don't see why that is a problem in a string datatype.

> There goes your 3.1 and 3.2.
>
> Anything which requires general-purpose SF serializers or parsers to know anything about time-variant registries of human politics or other foibles, for instance MIME, UniCode, Codepages, TimeZones, LeapSeconds etc. are a hard no from me, as a matter of principle.

Strawman. To understand UTF-8, you need RFC 3629. That's it.

> That takes 3.3 out, because without access to a registry, there is no way to tell what might or might not be a "character".

I'll rename it to "codepoint" if that makes a difference to you.

> For all I care, people can use any of your 2.1, 2.2 or 2.3, or anything else they come up with.

All of these need out-of-band signals, and will not be supported by tooling. If you believe that's unimportant, then why add sf-date?

> If anything need to be said about that, it should obviously be said in RFC8187(bis) since it already occupies precisely that topic on the standards track.

RFC 8187 applies to parameter syntax; thus it wouln't help with bare strings.

> In particular I do not want 2.3, not even as an appendix, because of the risk that it "leaks" and %xx unintentionally is interpreted in places where that is not explicitly allowed (See also: The "../" hole, Log4J, etc.)

I happen to agree that an approach is problematic if there's no in-band signal that shows that is in use. It causes confusion about when to unescape and when not to.

> So with all due respect Julian: Stay in your lane, this stuff belongs in your own RFC, not in SF#

I continue to disagree with that.

**Comment by mnot** [comment]
As far as I can see this is out of the scope we agreed to when we started this work, and would represent a potentially signficant delay to it. I'm going to wait for @tfpauly to say whether we should be working on it before I spend any time responding.

**Comment by reschke** [comment]
@awwright - RFC 8187 is one possible approach here; but it would only work for strings that appear as parameter values /such for "Problem" it would be good enough). To make it "automatic" when using an SF parser, the spec though would have to change to require that.

**Comment by tfpauly** [comment]
@reschke, all:

Given the scope of the revision that the group agreed upon when embarking on 8941bis, I don't think this kind of change fits within "minor technical issues and editorial fixes":

> - Add the Date type, currently in draft-ietf-httpbis-retrofit
> - Make the "Defining New Structured Fields” section align with the style guide (https://httpwg.org/admin/editors/style-guide#structured-fields), to not recommend the use of ABNF in new header definitions
> - Add clarifications to the use of ABNF in the document (for example, emphasize that they are not normative), subject to WG discussion
> - Address minor technical issues and editorial fixes

Expanding the scope would require a new consensus call to see what the WG thinks about the scope of this kind of change. We can do that if necessary, but I am concerned that this level of change is not in the limited spirit of the revision.

@reschke at this point I'd prefer to see a document/proposal with motivating use cases written up, separate from 8941bis.

**Comment by reschke** [comment]
The use cases are on the table:

- The HTTPAPI problem format document invents yet another way to embed non-ASCII
- Retrofit essentially proposes parser switches
- We need to decide how the sfbis document affects existing documents that refer to the older revision

I don't believe that writing another document that captures these discussions is productive; what we need to do is address these issues.

**Comment by tfpauly** [comment]
(Speaking as chair)

While I acknowledge that draft-ietf-httpapi-rfc7807bis does define a way to encode UTF-8 within ASCII strings that is not sf-binary, I don't see that as a reason to expand the scope of the sf-bis effort that the WG agreed to initially.

My impression is that the sf-bis document doesn't affect existing documents that refer to the original RFC at all in the current state of things, since sf-string's definition wouldn't change. The only semantic change the WG agreed to was the addition of sf-date, not modifying existing types or adding new types.

The issue of how to handle non-ASCII field values, as far as I can tell, is made no better nor worse by sf-bis; it is maintaining the definition of sf-string and sf-binary, which are tools that field definitions can choose to use. Changing the definition of those types or adding a new type is a larger, unrelated change that doesn't fit in the defined scope.

**Comment by martinthomson** [comment]
I would love to see a discussion about whether it makes sense to support arbitrary strings in fields (as opposed to just ASCII strings).  However, I agree with @tfpauly that this is not appropriate to include in the scope of the current change.

It's true that the changes we're considering here suggest that further changes might be possible or even appropriate.  But the scope of a change was deliberately small and it should remain so.  Then we'll have a chance of shipping an incremental improvement that is meaningful in a reasonable period.

Doing arbitrary strings won't be easy.  I can see that there are pressures to do, so I don't object to starting that work.  In parallel.  If that work resolves quickly, we can discuss how that might be integrated into the whole.  But that discussion isn't so mature.
