### ISSUE TITLE
Cookies set with or without leading dot in domain attribute

### ISSUE THREAD

**Issue by bagder** [httpwg/http-extensions#238]
... are they two distinct cookies and in which order should they be sent?

[on the list](https://lists.w3.org/Archives/Public/ietf-http-wg/2016OctDec/0046.html)

**Comment by johnwilander** [comment]
Reading this old mailing list discussion, you mention that Firefox and Chrome agree on how to handle this but Safari and Edge do it differently. You don't happen to have those three behaviors documented, do you? If not, can we at least get the Chrome+Firefox behavior stated here? Thanks!

**Comment by bagder** [comment]
Clearly I didn't use enough details when I wrote about it back then, and now I can't remember the specifics anymore. I suppose someone would have to do another similar experiment to figure it out again... sorry! :disappointed:

**Comment by mikewest** [comment]
We now have https://wpt.fyi/results/cookies/http-state/domain-tests.html?label=experimental&label=master&aligned copied over from Adam's old test repository, and several of those tests do exercise leading `.`s. Unfortunately we did a bad job of aligning the domain tests with the WPT framework (`home.example.com` is hard-coded). I'll poke at them to see if it's possible to rework the test data to match WPT's domain structure.

**Comment by mikewest** [comment]
It's a bigger problem than I have time for at the moment. Basically, we did a bad job porting the domain tests, and none work the way they're supposed to. We need to rewrite them.

**Comment by mikewest** [comment]
I put together [quick tests](https://github.com/web-platform-tests/wpt/pull/20934) for the specific thing this bug is asking about, and Chromium and Firefox both interpret `Set-Cookie: a=b; Domain=.web-platform.test` as `Set-Cookie: a=b; Domain=web-platform.test` (stripping the leading `.`), while Safari appears to treat it as `Set-Cookie: a=b` (e.g. ignoring the `Domain` attribute).

https://tools.ietf.org/html/rfc6265#section-5.2.3 suggests that Chromium/Firefox's behavior is expected. The leading `.` should be stripped, and therefore only one cookie is set as the two declarations are exactly the same. Given that we have some agreement between two engines and the spec, I'd prefer to close this out after the tests land, and treat the disagreement as a bug in WebKit/CFNetwork.

**Comment by johnwilander** [comment]
> I put together [quick tests](https://github.com/web-platform-tests/wpt/pull/20934) for the specific thing this bug is asking about, and Chromium and Firefox both interpret `Set-Cookie: a=b; Domain=.web-platform.test` as `Set-Cookie: a=b; Domain=web-platform.test` (stripping the leading `.`), while Safari appears to treat it as `Set-Cookie: a=b` (e.g. ignoring the `Domain` attribute).
> 
> https://tools.ietf.org/html/rfc6265#section-5.2.3 suggests that Chromium/Firefox's behavior is expected. The leading `.` should be stripped, and therefore only one cookie is set as the two declarations are exactly the same. Given that we have some agreement between two engines and the spec, I'd prefer to close this out after the tests land, and treat the disagreement as a bug in WebKit/CFNetwork.

Sounds like the right thing to do. I’ll put on my todo list to file the CFNetwork bug.

**Comment by mikewest** [comment]
Tests landed in https://github.com/web-platform-tests/wpt/pull/20934, no spec update necessary. Closing this out.
