### ISSUE TITLE
signatures: structure 2.1

### ISSUE THREAD

**Issue by reschke** [httpwg/http-extensions#2394]
Strictly editorial: Section 2.1 is way too long; moving a few more things into sub sections might be good.

(I can provide a PR if desired)

**Comment by jricher** [comment]
As editor, I disagree with this. The section consists of the definition, the caveats (which are several because HTTP fields are super weird), some general examples, and a listing of the flags that are explained in the next sub-sections. I personally see no value to split any of those out into sub-sections, as the narrative flows between them and they're tied together under a single topic.
