### ISSUE TITLE
message-signatures: requirements on sf dictionary parsing

### ISSUE THREAD

**Issue by reschke** [httpwg/http-extensions#2413]
2.1.2 says:

> Each parameterized key for a given field MUST NOT appear more than once in the signature base. Parameterized keys MAY appear in any order in the signature base, regardless of the order they occur in the source Dictionary.

How is an implementation supposed to verify that, given the fact that a SF parser will happily parse the field value (see RFC 8941, Section 4.2.2, step 2.4)?

**Comment by jricher** [comment]
This is checked fairly simply by checking the input of the signature components. If you've got two field entries with the same key parameter, you throw an error and stop creating the signature base. That's true for both the signer and verifier. The reason for this is exactly because of the expected behavior of a dictionary parser -- it's an ambiguity that can't reliably be covered by a signature because only the "last" element with a key gets used by the data structure in spite of other things getting shadowed.

**Comment by reschke** [comment]
Ah, sorry, I misread that and was confused by the MUST requirement here. In practice, a key appearing multiple times would be completely harmless, no? (because, by definition, it would always have the same value).

**Comment by jricher** [comment]
Correct, so it's a prohibition on the input behavior more than anything to avoid a possible ambiguity or rough edge for implementers.

**Comment by reschke** [comment]
OK,  I'm not sure this mandates a MUST requirement then; the reason I was confused was that I thought "otherwise something bad will happen", but that does not seem to be the case. Switching to "editorial".
