### ISSUE TITLE
message-signatures: format of signature base

### ISSUE THREAD

**Issue by reschke** [httpwg/http-extensions#2417]
2.5:

> The signature base is a US-ASCII string containing the canonicalized HTTP message components covered by the signature.

This seems to be inconsistent with Section 2.2.8 ("Query Parameters"), which could create non-ASCII component values.

**Comment by reschke** [comment]
FWIW, a query parameter (after application of https://url.spec.whatwg.org/#application/x-www-form-urlencoded) could contain CR, LF and other control characters.

**Comment by reschke** [comment]
So we likely need to serialize information extracted from query parameters using some kind of encoding; maybe an SF Byte Sequence.

**Comment by jricher** [comment]
This is tricky -- originally the query parameters were kept in percent-encoded form but from WG discussion we changed that to just use the unencoded value instead since several percent-encoded forms could be used. However it does look like the unencoded form could end up with problematic values here, so maybe we need to go back to that.

I'd rather us use an encoding native to the value rather than inventing something to put on top of it, even trying to re-use the `bs` flag we've already got defined for headers.

**Comment by reschke** [comment]
And we did that because to extract query parameter values, we need a query parser, and that is defined the way it is. I believe that decision was good, we now just need to figure out out to transform the extracted values so that they can be used in the signature base.

(And, FWIW, at the end we also should have an example for a case like that in the spec).
