### ISSUE TITLE
message-signatures: HTTP Signature Algorithms names

### ISSUE THREAD

**Issue by reschke** [httpwg/http-extensions#2421]
6.2.1:

> Algorithm Name:
>    An identifier for the HTTP Signature Algorithm. The name MUST be an ASCII string consisting only of lower-case characters ("a" - "z"), digits ("0" - "9"), and hyphens ("-"), and SHOULD NOT exceed 20 characters in length. The identifier MUST be unique within the context of the registry.

1. Can it start with a hyphen?
2. Under which circumstances would be more than 20 characters ok?
3. Uniqueness seems to be evident, given that we talk about a registry.

**Comment by jricher** [comment]
1. Sure, why not?
2. If you try to get the name down under 20 and it doesn't make sense, is misleading to implementors, or isn't unique.
3. Yes.

**Comment by reschke** [comment]
1. It's ... uncommon in identifiers.

**Comment by jricher** [comment]
Is "uncommon" enough to make it prohibited? It seems like the DE would question that decision prior to registration.

**Comment by reschke** [comment]
I'm just surprised that the rules are very different from other related HTTP registries, and I wonder why that is the case.

**Comment by jricher** [comment]
There's not a compelling reason for the rules to be different for this element. What rules would you propose for algorithm names?

**Comment by reschke** [comment]
Ok, I now realize that this applies to most or all registries introduced here.

That said, why not just use HTTP's "token" ABNF?

**Comment by jricher** [comment]
If anything, the restriction should be the contents of `sf-string`, of which this is already a subset. I don't think adding uppercase characters is a good idea, because you're going to run into practical problems if `RSA`, `rsa`, and `rSa` all mean different things in the registry, even if the value is case-sensitive by nature.

I see no compelling reason to expand the character set beyond what's already allowed in each registration.
