### ISSUE TITLE
Reuse of the Upload-Complete header field on requests and responses

### ISSUE THREAD

**Issue by guoye-zhang** [httpwg/http-extensions#2500]
@martinthomson brought up that during the WG meeting that reusing Upload-Complete on requests and responses can be confusing. They don’t mean exactly the same thing: `Upload-Complete: ?1` on the server means it has received the full upload, while `Upload-Complete: ?1` on the client means the body it will send is a complete upload.

**Comment by guoye-zhang** [comment]
We discussed this internally and prepared a response:

Upload-Complete is used on both requests and responses because it is symmetrical. Upon a typical successful transaction, an `Upload-Complete: ?0` request results in an `Upload-Complete: ?0` response, and an `Upload-Complete: ?1` request results in an `Upload-Complete: ?1` response. A server implementation can simply echo the field.

However, they are also meanings that we can take advantage of. The presence on the request means it’s a resumable request, and the presence on the response is also a useful signal. Since we are upgrading regular uploads, there are cases where 4xx/5xx responses are intentional and we can't just eat it by attempting to resume. We would be much more confident that the response came from the real server rather than a middlebox which shouldn’t randomly add `Upload-Complete: ?1`.

The server can also use `Upload-Complete: ?1` to terminate a request early if it does not care about the body, similar to the early response mechanism in HTTP/3.

**Comment by Acconut** [comment]
I am having second thoughts about this as well. While debugging a server implementation, the naming of the headers also confused me for a moment (even though I wrote parts of the draft). The reason is that `Upload-Complete` in a response (or `Upload-Incomplete` how it is currently called) refers to the current state of the upload, while `Upload-Complete` in a request refers to the potential state in the future, if the request completed successfully.

I don't think that we have a general issue with the concept of `Upload-Complete` and have to change much. But maybe a simple name change can help here already to alleviate the confusion.

We could use `Upload-Complete` for the response header to indicate that it represents the current state. And `Upload-Is-Completing` for request headers to indicate that process the request successfully will complete the upload.

We loose the symmetry of the names in request and response, but maybe this makes their relation even clearer.

**Comment by jrflat** [comment]
I think `Upload-Complete` for both client and server works because it represents their own perspectives of the upload.

For the client, sending `Upload-Complete: ?1` means "the upload is complete on my end, I've included all the data to complete it." The client isn't making assumptions about whether the server has received all the data; it's only expressing to the server that from its perspective, the upload data supplied is now whole.

For the server, responding `Upload-Complete: ?1` acknowledges the client's view of the complete upload and says, "Yes, the upload is complete on my end, too."

Same goes for `Upload-Complete: ?0`.

**Comment by Acconut** [comment]
At IETF 117, we agreed on using `Upload-Complete` for requests and responses: https://github.com/httpwg/wg-materials/blob/gh-pages/ietf117/minutes.md#upload-complete

I will open a PR for this and then we can close this issue.
