### ISSUE TITLE
Server should reject upload resumptions with inconsistent Content-Length

### ISSUE THREAD

**Issue by guoye-zhang** [httpwg/http-extensions#2544]
When the server receives a series of appends:

```
PATCH /upload
Upload-Offset: 10
Content-Length: 90

<interrupted after 10 bytes>
```

```
PATCH /upload
Upload-Offset: 20
Content-Length: 30

409 Conflict
<10+90 != 20+30>
```

If the offset+length is inconsistent, the server should reject the upload.

**Comment by smatsson** [comment]
To clarify; Is what you are saying here that the `Content-Length` provided during the upload creation procedure should act as the total size of the file, similar to Upload-Length in tus1x?

**Comment by Acconut** [comment]
I am not sure if we want this. I ran into this exact problem because your NIOResumableUpload implementation uses this logic (see https://lists.w3.org/Archives/Public/ietf-http-wg/2023JulSep/0024.html).

We currently have the `Upload-Incomplete` header to indicate the completeness of the upload. Based on this information, the server can determine if an upload is complete or not without relying on `Content-Length`. Adding `Content-Length` to the upload logic would mean that we have two indicators for upload completeness, which could potentially disagree with each other.

Personally, I think we should not use `Content-Length` to determine the upload's completeness and only determine it based on whether the client set `Upload-Incomplete: ?0` in a successful request. For each Upload Creation Procedure or Upload Appending Procedure, the `Content-Length` should be set to the number of bytes that the client wants to send in this individual procedure.

For example, if you want to transmit 100 bytes in the first POST request, set `Content-Length: 100` (or not if you use `Transfer-Encoding: chunked`). If you want to transmit 200 bytes in the following PATCH request, set `Content-Length: 200`. If you want to finish the upload then, set `Upload-Incomplete: ?0` and the upload is considered complete with its 300 bytes of content.

**Comment by guoye-zhang** [comment]
The issue in NIOResumableUpload was a bug, not how this is supposed to work. Offset + Content-Length = final upload size when the upload is complete, and if the client has told the server about the final size, it shouldn't be allowed to change its mind.

**Comment by jrflat** [comment]
> Personally, I think we should not use Content-Length to determine the upload's completeness and only determine it based on whether the client set Upload-Incomplete: ?0 in a successful request. For each Upload Creation Procedure or Upload Appending Procedure, the Content-Length should be set to the number of bytes that the client wants to send in this individual procedure.

Echoing what Guoye said, `Content-Length` should not determine the upload's completeness, but if an `Upload-Incomplete: ?0` request has a `Content-Length`, then the server can expect and enforce the final upload size based on that `Content-Length`. This prevents a client from appending more bytes to their upload than the server anticipated.

Ex.
1. Client starts an upload `Upload-Incomplete: ?0`, `Content-Length: 100`
2. Server expects a final upload size of 100 bytes
3. Upload is interrupted, offset-retrieving, server sends `Upload-Offset: 50`
4. Client now tries to append an extra ~10GB
5. Client sends `Upload-Offset: 50`, `Upload-Incomplete: ?0`, `Content-Length: 10000000000`
6. Server can reject this request

**Comment by Acconut** [comment]
> if an `Upload-Incomplete: ?0` request has a `Content-Length`, then the server can expect and enforce the final upload size based on that `Content-Length`. This prevents a client from appending more bytes to their upload than the server anticipated.

I see, thanks for the explanation. That makes sense. Basically, `Upload-Incomplete: ?0` in conjunction with `Content-Length` let the server know the final upload size, which should not be changed 👍

**Comment by guoye-zhang** [comment]
Final size = upload-offset + content-length if the upload is complete

**Comment by LPardue** [comment]
So the first ever request with Upload-Incomplete: ?0 and content-length sets the expected final size. Every other request must have a content-length less than that value?

**Comment by guoye-zhang** [comment]
Yeah, once the final length is determined, it cannot be changed by subsequent requests.

**Comment by LPardue** [comment]
OK I think that makes sense but it's not obvious from the spec. We should try and make it more accessible with some new or different text.

**Comment by Acconut** [comment]
I started on the wording in #2595
