### ISSUE TITLE
Signalling incomplete resolution back to the client?

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#2549]
In the implementation considerations, it discusses caveats related to getaddrinfo.

> An implementation MAY include incomplete information in the next-hop-aliases parameter to accommodate cases where it is unable to include the full chain, such as only including the canonical name if the implementation can only use getaddrinfo as described above.

The thought crossed my mind that this might be something worth telling the client about too, so it knows its working with some constraints. However, this would add some complexity to the wire encoding and other things, so on reflection probably doing nothing is ok. Opening this issue in case had similar thoughts.

**Comment by tfpauly** [comment]
I think this had come up previously in some discussions, but I'd be inclined to leave it as-is to avoid complexity here.

For the case of a proxy that only has getaddrinfo, it "doesn't know what it's missing" and so it can't really say if it has the whole chain or not. It very well might!

This seems like a case of the proxy saying as a whole "I'm only able to support XYZ features to this degree", since this wouldn't be something that changes for each response. I'm not sure it fits well in a header parameter here.

**Comment by LPardue** [comment]
yeah agree. I'm happy for this issue to be closed, I'll leave that up to you when to do so.

**Comment by tfpauly** [comment]
Will hold on to see if anyone has strong opinions / good ideas, but then can close.

**Comment by tfpauly** [comment]
No other feedback, closing!
