### ISSUE TITLE
Supported Range of Dates

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#2622]
Implementing Date in Python as a `datetime.datetime` object has an issue -- Python dates are limited to a specific range. 

Given that it's good to expose SF as idiomatic data structures wherever possible, I poked around a bit for limits on date/time objects in libraries, and found (all expressed as limits on years, as that's the most significant bit):

* Python - [1-9999](https://docs.python.org/3/library/datetime.html#constants)
* Rust - [262145-262143](https://docs.rs/chrono/0.4.26/chrono/naive/struct.NaiveDate.html)
* Go - [0-9999](https://pkg.go.dev/time#Parse)
* PHP - [64bits](https://www.php.net/manual/en/intro.datetime.php)
* JavaScript - [-271821-275760](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date)
* Ruby - [unbounded](https://stackoverflow.com/questions/15988539/what-is-the-range-of-the-ruby-date-or-datetime-object)
* Java - [-292269055-292278994](https://stackoverflow.com/questions/3598091/java-min-and-max-date-range)

Should we specify a minimum range of dates that an implementation should support (likely 1-9999) so that developers can be confident of them (as we've done for other data types)?

**Comment by reschke** [comment]
Hm. Do these differences affect other parts of HTTP as well, such as processing the "Date" field (or fields specific to caching...?).

**Comment by mnot** [comment]
(it's just that HTTP dates rarely go outside the range 1970 - "forseeable future")

**Comment by reschke** [comment]
Restricting to a year-based range would IMHO make sense if we actually would be using calendar dates (which we do not).

**Comment by mnot** [comment]
To be clear, I'm not proposing we restrict it -- just require implementations to support at least a particular range of values, just as we do with many other types.

Don't get stuck on years, that's just a rough sizing to get an idea of what we're looking at. I think we'd express it in integer values.

**Comment by bsdphk** [comment]
I've commented in the PR that I dont like this, but let me add a bit of context:

Handling of time, in real life and in computers, is incredibly messy and one of the most unreadable scientific books of all time is "Calendrical Calculations" which is our best shot at that subject matter.

I really do not want us to wade into this tarpit, because everybody who has ever done so, has just added more tar in the process.

My really strong preference is if Date was defined as "Seconds since Epoch" according to POSIX" with the full range of signed 15 decimal digits we inherit from Integer, so that we in no way adds any further complexity.

**Comment by mnot** [comment]
> My really strong preference is if Date was defined as "Seconds since Epoch" according to POSIX" with the full range of signed 15 decimal digits we inherit from Integer, so that we in no way adds any further complexity.

That's effectively what we have, even with this addition. This text is just requiring implementations to support _at least_ a certain range, so that it can be relied upon for interoperability.
