### ISSUE TITLE
Retrofit etag mapping: string, not byte sequence?

### ISSUE THREAD

**Issue by bathos** [httpwg/http-extensions#2630]
Was [byte sequence](https://httpwg.org/http-extensions/draft-ietf-httpbis-sfbis.html#name-byte-sequences) / `sf-binary` considered for [mapping ETag](https://httpwg.org/http-extensions/draft-ietf-httpbis-retrofit.html#section-3.3) (or more precisely, mapping [opaque-tag](https://httpwg.org/specs/rfc9110.html#field.etag)) in the retrofit? Currently this uses [string](https://httpwg.org/http-extensions/draft-ietf-httpbis-sfbis.html#name-strings) / `sf-string`, but:

1. Semantically, an `opaque-tag` value is opaque data, not string data.
2. The `opaque-tag` production permits [obs-text](https://httpwg.org/specs/rfc9110.html#fields.values), and `sf-string` cannot represent octets in that range.

This may well be a motivated decision rather than an oversight, but I couldn’t turn up any information about how the decision was made. I would have guessed that the general goal for mappings would be to choose the SFV type whose value space covers the widest range of pre-retrofit valid values possible and/or the SFV type with the closest semantics, though, and afaict that would be “byte sequence” in both cases here.

**Comment by mnot** [comment]
obs-text and similar are there only for 'historical reasons' -- they're not to be encoraged, or considered 'normal' HTTP.

Every SF mapping has edge cases where technically valid values will fail SF parsing, and that's fine -- the idea isn't to match the original ABNF, because that's not possible in most cases, and also because the variance between the ABNF and real world are considerable.
