### ISSUE TITLE
Overhead in cache digest algorithm

### ISSUE THREAD

**Issue by sebdeckers** [httpwg/http-extensions#264]
(Originally misfiled at https://github.com/mnot/I-D/issues/204)

I believe the algorithm may be improved to increase speed and reduce digest size.

#### De-dupe URLs before hashing them

Wastes time sorting and skipping through the list in a later stage.
Inflates value of N, needlessly increasing size of the entire digest.

#### Trim URL origin

Every URL has identical origin. Hashing this repetitive data is wasted effort.

**Comment by kazuho** [comment]
Thank you for your suggestions.

> __De-dupe URLs before hashing them__

Is it likely that there'd be lot of freshly-cached (or stale-cached) responses sharing the same URL?

My assumption is that the answer is no, and that we do not need to recommend deduping the URLs before hashing (note: deduplication after hashing and truncating would still be necessary even if you dedupe the URLs beforehand).

If the answer is yes, then we should consider including additional keys into the hash context so that the server can more correctly identify what is being cached.

> __Trim URL origin__

I agree that we can trim the origin part of the URL, since in the latest draft we have an origin field for every CACHE_DIGEST frame.

**Comment by mnot** [comment]
My .02 --

De-duping the URLs is an implementation optimisation; it's not necessary to specify it (but it doesn't hurt if we really want to).

Trimming the URL origin makes me nervous; it's defence-in-depth against implementation errors.

**Comment by sebdeckers** [comment]
@mnot Agreed on both points. 👍

Trimming origins would be tricky with coalesced connections and cross origin PUSH.
