### ISSUE TITLE
Change of "origin"

### ISSUE THREAD

**Issue by kazuho** [httpwg/http-extensions#2643]
At the moment, section 1.2 (Problems) start with the following sentence:
>    Classic HTTP CONNECT proxies are identified by an origin.  The proxy does not have a path of its own.  This prevents any origin from hosting multiple distinct proxy services.

I totally get what it tries to say, but it is confusing if not incorrect.

[RFC 9110 section 9.3.6](https://www.rfc-editor.org/rfc/rfc9110#name-connect) states that a CONNECT request is handled by a "proxy" and the target specified by the "host:port" tuple is the "origin."

Therefore, HTTP CONNECT proxies are not identified by an origin. Rather, they are identified by the user's proxy settings.

I think we'd better update the problem statement, and might also consider pointing out that the definition of "origin" will be different between CONNECT and connect-tcp (or use different terms to identify the CONNECT target and the entity that creates a tunnel in order to avoid confusion, maybe?).

**Comment by kazuho** [comment]
PS. Practical example showcasing the side effect of the change to the definition is that the way to authenticate becomes different; when a client tries to establish a CONNECT tunnel with authentication, it uses "proxy-authorization" header, whereas when a client tries to establish a connect-tcp tunnel, it uses "authorization." I think it's worth noting.

**Comment by DavidSchinazi** [comment]
I'm realizing that this spec has the opportunity to fix the origin issues present in regular CONNECT. While we're there it'd be great to clarify how connect-tcp interacts with Alt-Svc because it's unclear for CONNECT. I sent some more [details to the mailing list](https://lists.w3.org/Archives/Public/ietf-http-wg/2023OctDec/0132.html) about why it's unclear for CONNECT.
