### ISSUE TITLE
[rfc6265bis] SameSite=Strict cookie isolation on cross-site windows

### ISSUE THREAD

**Issue by Pedro-Bernardo** [httpwg/http-extensions#2644]
We are reporting on the behavior of `samesite=strict` cookies on cross-site windows opened through `window.open` that goes against our assumptions (implied by the current specification) on when and how `samesite=strict` cookies should be isolated. Breaking these assumptions can lead to security issues, allowing the bypass of `samesite=strict` cookies as a defense mechanism against CSRF and XS-Leak attacks.

## 1. Overview

The following table shows  when `samesite=strict` cookies are attached to requests associated with `iframe`s and pages opened through `window.open` (where :x: stands for *not attached*/*not accessible* and :white_check_mark: for *attached*/*accessible*):

| Action/Element        | iframe | window.open        | 
| --------------------- | ------ | ------------------ |
| page load             | :x:    | :x:                |
| document.cookie       | :x:    | :white_check_mark: |
| subresource load      | :x:    | :white_check_mark: |
| user-initiated reload | :x:    | :x:                |
| JavaScript reload     | :x:    | :white_check_mark: |

The behavior of `samesite=strict` cookies regarding page reloads for pages opened through `window.open` from a cross-site position is evident from the [specification](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-rfc6265bis-12#section-8.8.5):

> **Requests issued for reloads triggered through user interface elements** (such as a refresh button on a toolbar) **are same-site only if the reloaded document was originally navigated to via a same-site request**. This **differs from the handling of other reload navigations, which are always same-site if top-level**, since the source navigable's active document is precisely the document being reloaded.
> This special handling of reloads triggered through a user interface element **avoids sending `SameSite` cookies on user-initiated reloads if they were withheld on the original navigation** (i.e., if the initial navigation were cross-site). 

Currently, the specification mandates blocking cookies on user-initiated page reloads but not on reloads performed through JavaScript. We think that `samesite=strict` cookies should also be blocked in this scenario, as this interaction between JavaScript navigations and `samesite=strict` cookies allows attackers to bypass the restrictions imposed by `samesite=strict` (see 2.1). Additionally, we verified that `samesite=strict` cookies, even when not sent in the top-level request that loads a page, are still attached to requests that load subresources for that page. This behavior is not explicitly defined in the specification. However, its counterpart (setting a cookie) is defined as follows:

> The "SameSite" attribute affects cookie creation as well as delivery. Cookies which assert "samesite=lax" or "samesite=strict" cannot be set in responses to cross-site subresource requests, or cross-site nested navigations.

Although these requests are not cross-site, they are performed implicitly by a page navigated from a cross-site context, effectively enabling an attacker to perform authenticated cross-site requests (see 2.1), or cookie tossing attacks.

> **If the reload navigation were instead considered same-site, and sent all the initially withheld `SameSite` cookies, the security benefits of withholding the cookies in the first place would be nullified**

Following this argument, when considering that user-initiated page reloads are deemed cross-site and therefore do not attach `samesite=strict` cookies, it seems reasonable to assume both JavaScript navigations and subresource loads should also not attach `samesite=strict` cookies, as they are also transparent to the user.

### 2.1 samesite=strict cookies bypass and CSRF

It is possible to abuse the previously described behavior to bypass CSRF protections An attacker can forge same-site requests starting from a cross-site position by abusing gadgets that result in secondary same-site requests. An example of one of these gadgets is a JavaScript-based redirect that performs a redirection using attacker-controlled data. Here is a possible attack flow:

1. Victim visits https://good.com/set, setting the cookie `foo=bar; samesite=strict` cookie for domain `good.com`.
2. Victim then visits https://attacker.com/, which executes `window.open("https://good.com/redir?q=/")`
	1. The request to https://good.com/redir?q=/ is cross-site, so it does not attach `samesite=strict` cookies
3. https://good.com/redir?q=/ performs a navigation to the value of the URL parameter `q` through `document.location.href = '${parsedURL.query['q']}'`
	1. This triggers a request to https://good.com/, which attaches `samesite=strict` cookies, allowing an attacker to make authenticated requests from a cross-site position

A similar scenario was discussed in this [post](https://portswigger.net/web-security/csrf/bypassing-samesite-restrictions#bypassing-samesite-restrictions-using-on-site-gadgets).

Besides JavaScript redirections, other requests, such as subresource loads, could also be exploited to subvert the security assumptions granted by `samesite=strict` cookies.

### 2.2 XS-Leaks 

`samesite=lax` cookies effectively defend against certain classes of XS-Leaks attacks. However, `window.open`-based attacks are still possible since `samesite=lax`cookies are attached to top-level cross-site requests. Since `samesite=strict` cookies are not attached to top-level cross-site requests,  they have been deemed an effective mitigation against `window.open`-based XS-Leaks. 

As discussed in 2.1, gadgets that allow attackers to forge same-site requests from a cross-site position can be leveraged for XS-Leaks. An example would be a page that performs a stateful subresource load, which modifies the page DOM. If an attacker opens this page through `window.open`, `samesite=strict` cookies will not be attached, but following subresource loads in the new page will attach these cookies, leading to state-dependent changes to the DOM, which could be measured by the attacker (through frame counting for example).

Best regards

**Comment by sbingler** [comment]
Thanks for your well researched issue! I’ll try and address some of the points you brought up.

First and foremost, SameSite is meant as only one layer in a defense in depth strategy, its design and implementation tries to balance our security and privacy goals with the realities of the web as it exists today. This ultimately means that it must be used with smart site design that leverages the other security tools and features available.

### Similarities between window.open and navigating
`window.open` differs from the original site (let’s call it a.example) navigating itself by allowing a.example to continue to hold and manipulate a reference to the new window. But, every navigation a.example makes on that reference will have an initiator of a.example (On Chrome at least, I haven’t checked other browsers, but I believe it’s true for all).
This means that, as far as SameSite is concerned, an a.example window navigating itself directly or opening a new window and navigating that instead are all the same type of top-level navigation. This appears to hold true for all the examples and notes in your post.

### Addressing your points

> Currently, the specification mandates blocking cookies on user-initiated page reloads but not on reloads performed through JavaScript.

This was a purposeful decision. We wanted to allow the site to be able to operate specific “landing pages” in order to allow third-party entities (maybe a sign in flow or payment processor) to navigate the user back and then the landing page could refresh to allow access to cookies in order to complete the process. Since the reload must be explicitly initiated by the page it would require the site developer to “opt-in” to the behavior and hopefully design the landing page with that behavior in mind.

Conversely, we disallowed user initiated reloads because that doesn’t show an intention on the site’s behalf that it wants or needs cookies following that cross-site navigation. Users have been taught over the years to try reloading if a page looks broken, something that could occur if cookies aren’t present. Continuing to block cookies helps prevent users from inadvertently weakening their own security.

> Additionally, we verified that samesite=strict cookies, even when not sent in the top-level request that loads a page, are still attached to requests that load subresources for that page. This behavior is not explicitly defined in the specification.

That’s expected and intended. Samesite operates on a per request basis (or on a per JS call basis) so all requests, sub-resource or otherwise, are subject to the same rules. See [here](https://httpwg.org/http-extensions/draft-ietf-httpbis-rfc6265bis.html#name-same-site-and-cross-site-re).  
The spec assumes that since the page loading the same-site resources is in control of what it loads, it shouldn’t load anything that makes harmful changes.

> abusing gadgets

You’re correct that if a site exposes an API like you’ve given in 2.1 then it’s possible to give an attacker control + access to SameSite cookies. But to me it appears that the gadget is the footgun and I’m not sure how/if SameSite should solve this. Allowing any cross-site entity to make requests as yourself is a dangerous tool!

> Besides JavaScript redirections, other requests, such as subresource loads, could also be exploited to subvert the security assumptions granted by samesite=strict cookies.

I mentioned above that pages are in control of what they load and as long as they only load safe resources that they’re expecting they should be fine, but if you have any examples to the contrary I’m very interested in hearing about them.


> However, window.open-based attacks are still possible since samesite=laxcookies are attached to top-level cross-site requests

Going back to how `window.open`s are basically the same as any other top-level navigation, this is the intended behavior. Lax cookies shouldn’t be used for anything that can allow changes to anything important.

> leading to state-dependent changes to the DOM, which could be measured by the attacker (through frame counting for example).

Agreed, it’s definitely possible to leak state this way. I’m not familiar with the reasoning with why the single-origin policy allows `window.open` references to read `window.length`, but I’m sure the spec writers had a good reason.


Hope that helped clear things up, let me know if you have any other questions or concerns.

**Comment by lavish** [comment]
Hi @sbingler, thanks (as usual) for the kind and thorough response!

I did a bit of additional investigation and found some discussions that we missed before opening the issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1459321 and https://github.com/httpwg/http-extensions/issues/628

As far as I understood, the current behavior concerning page reloads has been defined only recently (2021). Before that, different browser vendors had [conflicting security concerns](https://bugzilla.mozilla.org/show_bug.cgi?id=1459321#c3). Even nowadays, browsers do not seem to fully agree on the intended behavior, or at least Firefox is inconsistent with Chrome's behavior since it does not attach SameSite=strict cookies after a call to `location.reload()`. Some confusion on this matter is justifiable. :)

I now see the rationale behind the design that enables specific pages to opt-in to SameSite=strict cookies upon a self-initiated reload. I always thought SameSite=lax cookies ensured compatibility with SSOs and payment flows, as lax cookies are attached to top-level navigations. But this "strict + reload hack" (so to say) puts the webpage in control instead of attaching cookies to all cross-site top-level requests. The downside of this behavior, as discussed, is that JS-based open redirectors become a gadget for bypassing SameSite=strict cookies. I'm not sure if the benefits outweigh the risks, but probably, the spec would benefit from a more explicit discussion of this trade-off.

> The spec assumes that since the page loading the same-site resources is in control of what it loads, it shouldn't load anything that makes harmful changes.

Concerning subresource loading, I would argue that in general this is not a valid assumption. In principle, here we have an untrusted context (the cross-site page opened via `window.open()`) that automatically loads authenticated resources. This is somehow the dual of SRI, CSP, mixed content, and other security mechanisms that prevent a trusted context from loading untrusted resources that an attacker could abuse. We have not measured the prevalence of security issues caused by this behavior in the wild (i.e., xs-leaks introduced by an authenticated subresource being loaded), but I would expect a non-negligible number of affected instances.

The current behavior surprised me, and it is possible that developers who care about protecting from xs-leaks are also unaware of the potential risks. For instance, the [xs-leaks wiki on SameSite cookies](https://xsleaks.dev/docs/defenses/opt-in/same-site-cookies/) states that:

> Strict cookies provide the strongest security guarantees, but it can be very difficult to deploy Strict same-site cookies in an existing application.

citing only other reasons (e.g., the 2 minutes exception rule) as major limitations of SameSite cookies.

To conclude, we just wanted to discuss this issue after encountering a behavior that diverges from our mental model of SameSite cookies and that we could not entirely justify it after reading the spec. As for JS-initiated reloads, if the behavior is here to stay, I think the spec could mention these limitations more explicitly to prevent developers from building their applications based on wrong assumptions.

Thanks again for the discussion!
Marco

**Comment by sbingler** [comment]
Hi @lavish,

As you found in those discussions, reload behavior wasn’t well aligned previously and I’m not sure how purposeful each UA’s behavior was at the time.

> Firefox is inconsistent with Chrome's behavior since it does not attach SameSite=strict cookies after a call to location.reload().

I know Firefox has a number of SameSite related behaviors behind default disabled configs, this could be as well. I don’t have easy access to Firefox at the moment but I believe the nightly builds have these flags enabled. What happens if you try testing on a nightly build?

> I now see the rationale behind the design that enables specific pages to opt-in to SameSite=strict cookies upon a self-initiated reload. I always thought SameSite=lax cookies ensured compatibility with SSOs and payment flows,

SameSite=Lax is useful for flows that use top-level navigation, but if a flow is happening in an iframe then SameSite=Lax cookies would be blocked. The reload technique enables these iframe based flows to function.

> Concerning subresource loading, I would argue that in general this is not a valid assumption.

The issue here is that a page may still load sub-resources that require SameSite=Strict auth cookies even if the initial request didn’t include those auth cookies?

Plainly, any site that allows unauthenticated access to a page which loads authenticated sub-resources is incorrectly using SameSite. Sites should return a 401 error, or some other denial, if the initial request does not include the appropriate cookies. 

Sadly though, I agree with you that there are probably sites that do not.

> To conclude, we just wanted to discuss this issue after encountering a behavior that diverges from our mental model of SameSite cookies and that we could not entirely justify it after reading the spec.


Just to confirm, the behavior you’re talking about are:
* Window.open navigations are not as restrictive as iframe navigations.
* Non-user controlled reloads allow cookies
* Sub-resource requests send SameSite cookies
* Redirect gadgets allow access to SameSite cookies

Did I miss any?

> As for JS-initiated reloads, if the behavior is here to stay, I think the spec could mention these limitations more explicitly to prevent developers from building their applications based on wrong assumptions.

What do you mean by “these limitations”? Are you referring to the redirect gadget?

**Comment by sbingler** [comment]
Any remaining comments/concerns before I close?

**Comment by lavish** [comment]
Hi @sbingler,

Sorry, I missed your earlier reply in October, and I'm just now seeing it. Thanks for the ping.

> What happens if you try testing on a nightly build?

I tried Firefox 123.0.1 (stable) and Firefox 125.0a1 (nightly), and they behave the same way. SameSite `strict` cookies are not attached to requests initiated via `location.reload()`, but they are attached to requests caused by `location.href = location.href`. Chrome sends the cookie in both cases.

> [...] Sadly though, I agree with you that there are probably sites that do not

Indeed. While open redirectors and script gadgets are known to carry their problems, I am concerned about issues enabled by authenticated subresource requests, as they are less known to web developers.

> Did I miss any?

I don't think so.

> What do you mean by "these limitations"? Are you referring to the redirect gadget?

All of the above, actually. I understand that it's challenging to change the behavior at this point. Still, I think it would be beneficial to explicitly document both redirection gadgets and authenticated subresource requests under Sec. 8.8 of the spec. This would help web developers to understand the risks better and adopt mitigations.

Cheers,
Marco
