### ISSUE TITLE
"WWW-Authenticate" vs. "Proxy-Authenticate"

### ISSUE THREAD

**Issue by bemasc** [httpwg/http-extensions#2694]
Related to #2643 and #2692

HTTP request proxies use "Proxy-Authenticate" in order to distinguish proxy authentication from destination authentication ("WWW-Authenticate") in the mixed bag of headers that is presented to the proxy.  Classic HTTP CONNECT proxies don't have that problem, but they still use "Proxy-Authenticate", probably just for consistency.

The MASQUE RFCs don't say anything about which authentication headers to use.

"connect-tcp" and MASQUE should definitely follow the same rules, whatever they are.  @kazuho noted that RFC 9110 says "the Proxy-Authenticate header field applies only to the next outbound client on the response chain".  This implies that a general-purpose gateway is not expected to forward Proxy-Authenticate headers.  However, there is actually no such thing as a general-purpose gateway for Extended CONNECT, so this seems somewhat moot.

Personally, I think that our guidance should probably also line up with what we want to say for [the mirror protocol](https://datatracker.ietf.org/doc/draft-group-privacypass-consistency-mirror/) which is (in my view, despite some authors' protestations) a modernized HTTP request proxy.

**Comment by tfpauly** [comment]
I somewhat think it's both — it's content and the proxy. 🤷

**Comment by kazuho** [comment]
@bemasc Thank you for opening the issue.

> "connect-tcp" and MASQUE should definitely follow the same rules, whatever they are. @kazuho noted that RFC 9110 says "the Proxy-Authenticate header field applies only to the next outbound client on the response chain". This implies that a general-purpose gateway is not expected to forward Proxy-Authenticate headers. However, there is actually no such thing as a general-purpose gateway for Extended CONNECT, so this seems somewhat moot.

If we are to consider extended CONNECT gateways as proxies, then the question would be what the URI of the connect-tcp request means.

RFC 9110 says that target URI specifies the origin. It is only because all the existing extended CONNECT family deals with origins that the TLS handshakes to those servers implementing the extended CONNECT family can be validated using certificates issued for that origin.

To conclude, to me in seems that the use of WWW-Authenticate is mandated by the using URI as the target.

**Comment by bemasc** [comment]
I don't think anything is really mandated.  Within the current language of RFC 9110, I think we are free to choose either interpretation.  However, I'm happy to say that "WWW-Authenticate" is the winner here, and "Proxy-Authenticate" does not traverse "connect-tcp" (or "connect-udp") gateways.
