### ISSUE TITLE
Revalidation

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#2700]
The ability to group for purposes of revalidation was added somewhat speculatively. We should evaluate it and see if it's useful, safe, etc.

**Comment by mnot** [comment]
Perhaps what we should do is remove revalidation, but assure that tags can be extended in a way that allows future uses like that to be safely specified.

**Comment by MikeBishop** [comment]
I'm inclined to say this is dangerous as-is.

Assume the deployment of a batch of resources has a file in it which does not always change with every release. If that resource is the first one to be revalidated, the lifetime of the stale resources is extended and the stale copies continue to be served. The cache will then fail to discover that they have changed, because it won't attempt to revalidate them.

If you want to do this, I think you need something like a group ETag, where the revalidation can indicate that _this_ resource hasn't changed, but the state of the group has.
