### ISSUE TITLE
Can dictionary keys repeat?

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#281]
We need clear rules about whether this is OK

```
Header: identifier;v=1;v=2
```

**Comment by bsdphk** [comment]
I have added the following text:

```
Key identifiers in dictionaries SHALL be unique, but semantically
overlapping key identifiers for instance 'text/plain' and 'text/*'
are ok.
```

**Comment by martinthomson** [comment]
This invalidates the choice in QUIC, see https://quicwg.github.io/base-drafts/draft-ietf-quic-http.html#rfc.section.2.1

**Comment by MikeBishop** [comment]
Either keys need to repeat, or there needs to be a list syntax as a value.  Either would satisfy the use case, but "neither" is a painful option.

**Comment by MikeBishop** [comment]
As @jyasskin is encountering, there needs to be something better here.

**Comment by jyasskin** [comment]
Specifically, I believe this issue is a request to have some way to represent a dictionary member whose value is an ordered list? My use is in https://tools.ietf.org/id/draft-yasskin-http-origin-signed-responses-01.html#signature-header, where `certUrl` and `validityUrl` maybe should be lists of strings, and maybe the order should be significant to express a series of fallback URLs.

[Quic](https://quicwg.github.io/base-drafts/draft-ietf-quic-http.html#alt-svc-version-hint) specifies its order to be significant.

I do appreciate the default provided by "SHALL be unique" that dictionary members aren't lists unless we explicitly write that they are, since it helps my algorithms fail closed when someone sends an unexpected extra value.

**Comment by mnot** [comment]
So, in the current iteration of structured headers, I think this question applies to both Dictionaries and Parameterised Labels.

Currently, Dictionaries forbid repeating members ("If dictionary already contains this_key, raise an error."). Similar language is in the parsing algorithm for parameterised labels. 

If that remains, it would be good to reinforce this in requirements (rather than just leaving it in the algorithms) for Dictionaries; Parameterised Labels already does that.

**If** Alt-Svc were defined as a structured header, I think QUIC's use case could be shoe-horned in; e.g.,

    Alt-Svc: hq=":49288";quic="1,51303334"

That's not pretty, of course, but I question how common this particular scenario is (most headers that need to be ordered can just use a list).

For @jyasskin's use case, something similar can happen (whitespace is a natural choice for delimiting URLs); e.g.,

    Signature: sig2;
      sig=*MEQCIGjZRqTRf9iKNkGFyzRMTFgwf/BrY2ZNIP/dykhUV0aYAiBTXg+8wujoT4n/W+cNgb7pGqQvIUGYZ8u8HZJ5YH26Qg;
      validityUrl="https://example.com/resource.validity https://fallback.example.net/foo";
      certUrl="https://example.com/certs https://and.another.example.org/bar";
      certSha256=*kQAA8u33cZRTy7RHMO4+dv57baZL48SYA2PqmYvPPbg;
      date=1511301183; expires=1511905983

If we allowed multiple instances of Dictionary (and Parameterised Label) keys, I'm concerned that it would be significantly more difficult to map structured headers into common data structures, and therefore would increase the friction against the introduction of generic parsing and serialisation tools for them -- as well as complicate their use. Remembering that the goal for SH is **not** to be able to express every conceivable header, but to get the 80% of "cream", I think this is a good tradeoff.

**Comment by jyasskin** [comment]
I can live with guidance to represent arrays by defining a custom parser within strings.
