### ISSUE TITLE
explicitly call out what to do with empty name string in Set-Cookie (rfc6265bis)

### ISSUE THREAD

**Issue by adamse** [httpwg/http-extensions#2963]
What should a user agent do with the "set-cookie-string" `=hej`?

The current RFC says that the name string can be empty and then in a subsequent step to ignore that cookie. https://datatracker.ietf.org/doc/html/rfc6265#autoid-27

**Comment by sbingler** [comment]
Hi, 

[6265bis Section 5.6 Step 3](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-rfc6265bis#name-the-set-cookie-header-field)  instructs 

>If the name-value-pair string lacks a %x3D ("=") character, then the name string is empty, and the value string is the value of name-value-pair.
Otherwise, the name string consists of the characters up to, but not including, the first %x3D ("=") character, and the (possibly empty) value string consists of the characters after the first %x3D ("=") character.

which covers the case of a nameless cookie such as `=hej`. I think clarifying, similar to the value string, that the name string could be possibly empty would improve readability, I'll make that change.

**Comment by adamse** [comment]
Thank you @sbingler. This means there is a change in the recommended parsing algorithm: now empty named cookies are ok. Is that intended?

**Comment by sbingler** [comment]
That's correct. Even though it's strongly  not recommended we found that servers still produced unusual set-cookie strings, including empty cookie names, and many UAs accepted them. So the parsing change is meant to standardized behavior so that UAs can at least all do the same thing with them.

I still _strongly_ recommend that any sites only use cookies with a non-empty name that conforms to [Section 4](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-rfc6265bis#name-server-requirements)'s syntax. Same for the value field too, now that I'm mentioning it. It'll probably work otherwise, but why make your life harder?
