### ISSUE TITLE
Expect CT: includeSubDomains

### ISSUE THREAD

**Issue by craigfrancis** [httpwg/http-extensions#322]
Should the `Expect CT` header also have a `includeSubDomains` directive?

In the same way that [Strict-Transport-Security](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security) and [Public-Key-Pins](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Public-Key-Pins) has this feature.

**Comment by estark37** [comment]
I've intentionally omitted `includeSubdomains` in Expect-CT. Though I acknowledge that it would be useful to site owners, I don't think we should add it because it considerably increases the size of the footgun, by offering the ability to require CT for subdomains that have never even demonstrated to the UA their CT compliance.

(I also suspect that most site owners would primarily use it as a tool to learn about all their subdomains, which is a use that is somewhat orthogonal to Expect-CT's actual purpose.)

**Comment by craigfrancis** [comment]
That's a reasonable approach, if anyone else needs this they could re-open this issue.
