### ISSUE TITLE
Geolocation Header

### ISSUE THREAD

**Issue by luisbargu** [httpwg/http-extensions#364]
Hello,

My name is Luis. I'd like to discuss with you a proposal to solve the following use case:

Currently, the only mechanism to share your location with a website is through the JS Geolocation API. This has some limitations: First, in order to have the server know the client’s location there are two full roundtrips required (one roundtrip to load the page with Javascript code, and a second roundtrip to actually send the location to the server and get back a location-aware response). While not as significant as the first limitation, the second limitation is that the client must execute Javascript in order to acquire location.

For example, for services like Search, it means that the very first response from a server will contain non-localized results, and a second roundtrip would be required to refresh those results (assuming Geolocation permission is already granted for the origin).

There's many ways to solve this problem through headers, so no JS would be required and clients could proactively include geolocation data in the very first request (after the server asked for it in previous sessions, and permissions are granted).

[Here you can find a document detailing the problem and a possible proposal](https://docs.google.com/document/d/1zL4qyOpp6W36H4_eMpmth3Yj_ZTMZ3wCupc01q5qatA/edit)

After discussing with @igrigorik he suggested that Client Hints might be a potential way to implement this too, which makes perfect sense. However, some features in the original proposal would not be possible with current CH draft (parameters for CH-Accept or path restrictions for when the data should be included).

It would be great to get your opinion on this and whether this is something that might be interesting for people in this working group.

Thanks!
Luis.

**Comment by mnot** [comment]
Hi Luis,

Welcome. The best way to make a proposal for new work to the WG is to send e-mail; we generally use this repo to talk about things we've already decided to do.

Client Hints is already very advanced in the process, so we're not likely to add it to that spec. However, it doesn't have to be in that document to be considered a "client hint" (which is really just a use of content negotiation). 

I'd encourage you to bring this up on the WG mailing list:
  https://lists.w3.org/Archives/Public/ietf-http-wg/
(you can just paste the text above into an e-mail)

Be aware that, because it's Geolocation, there's going to be extra scrutiny from a privacy/security perspective. Also, one of the primary things we look at when deciding to adopt something is whether it's likely to get implemented. 

Cheers,

**Comment by igrigorik** [comment]
@mnot I suggested to @luisbargu that we should start a thread here first to hash out a few high-level questions about the existing proposal and possible CH integration, before we take it to the wider list. I'll re-open this, but if you feel that this belongs on the list, we can take it there.

---

First off, I think CH is a great conceptual fit to what @luisbargu is proposing, and I'd _really_ love to see us reusing established CH mechanism to ease implementation, both on the UA/client side and for developers — this makes everyone's life easier. I'll leave the "what" discussion, like granularity and type of data delivered via this hint, for a separate discussion, and focus on the how here...

>Header sent from the server to the user agent when a host is compatible with the Geolocation
> Header and is requesting geolocation to be attached in subsequent requests.
>
>>Geolocation-Request: Path="/localService"; Type=IfAlreadyGranted; Expires=Thu, 18 Dec 2017 12:00:00 UTC

The CH mechanism for the above is:

> Accept-CH: Geolocation
> Accept-CH-Lifetime: 86400 (seconds)

There are two bits missing: Path and Type. 

### Path
This is something we considered for CH in the past — "I want to scope my hints to a subpath" — but punted on due to limited (or so we deemed at the time, at least) utility vs implementation complexity tradeoff (equivalent to cookie paths, which is a burden we didn't want to take on). In the last few years of CH experiments, I've not heard any complaints or requests for this. I think that was the right call, and I'd suggest we stick with it.

### Type
fwiw, I'd like to make an argument that we should omit this. The idea here is to enable sites to trigger a permission prompt via a header, which seems convenient on the surface, but experience shows that this is a bad UX pattern: you [should be using JS API to trigger permission prompt after explaining the intent](https://docs.google.com/document/d/1WNPIS_2F0eyDm5SS2E6LZ_75tk6XtBSnR1xNjWJ_DPE/edit) and motivation. The incremental value we're adding with the header trigger is low, and seems more like a footgun. 

If you buy both of the above, then CH has all the necessary building blocks to enable Geolocation. 

---

@luisbargu WDYT? How critical, or not, are Path and Type for the use case you had in mind?

@yoavweiss curious to hear your thoughts on the above, and Geolocation use case for CDNs.

@mnot tactical question: what's the right process for followup RFC's to "register" hints to be compatible with Accept-CH? Do we need any extra steps in CH for a registry, or some extension hooks?

**Comment by luisbargu** [comment]
I still feel path can be useful, mainly to not "over-send" data that in this case might be sensitive from a privacy point of view. But I also understand the complexity tradeoffs, and Path is not core to this proposal. So if you went through this for CH and considered path was not worth, it probably applies well to this case.

Regarding Type to trigger prompts... Right, it's doable through JS but was nice to offer a purely http based solution. Also understand the tradeoff in this case for value vs complexity, and agree it's also not core to the geolocation header.

So on my side, if others think CH is the right approach for this, then for consistency and simplicity I'd be happy to follow that path and start a draft, on top of CH. Happy to hear other opinions :)

**Comment by yoavweiss** [comment]
One major difference between this and the other CH headers is that this header should only be sent to the first party (or only to hosts which have permission to view geolocation data, so to third parties that got such permissions before).
The use case of using geo info for content adaptation at the edge or origin seems an interesting one.

**Comment by igrigorik** [comment]
> One major difference between this and the other CH headers is that this header should only be sent to the first party (or only to hosts which have permission to view geolocation data, so to third parties that got such permissions before).

See https://github.com/httpwg/http-extensions/issues/372 for discussions related to that. I think this example is highlighting the need for origin-scoped hints, which I think we can do with ACH.

> So on my side, if others think CH is the right approach for this, then for consistency and simplicity I'd be happy to follow that path and start a draft, on top of CH. Happy to hear other opinions :)

I think CH is the right fit. For a hot-off-the-press example, take a look at the [Device Memory i2s on blink-dev](https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/8qlTjzRY9Mc/BYCuqWJXBwAJ).. Assuming we can drop the prompt trigger and path requirements, you can just follow that template.
