### ISSUE TITLE
multiple 103s are cumulating or overwriting headers?

### ISSUE THREAD

**Issue by ddragana** [httpwg/http-extensions#371]
In section 2.  "103 Early Hints" the last paragraph describes that 103 can be send multiple time. The given example reads as if a server may correct its previous 103 that is made from a cached resource. So the following 103 are correcting the older ones, they are only adding headers to the previous ones or are they replacing them completely? Maybe sentence clarifying this would be good.

**Comment by mnot** [comment]
Also, this is a general problem with the HTTP caching model, not specific to 103. See:
  https://github.com/httpwg/http11bis/issues/29

**Comment by kazuho** [comment]
This is an interesting question. I think that we should agree on what the expected behavior is before discussing how (or if) we should update the text.

Regarding the question, I think that we should consider two (or more) Early Hints responses as expectations from different sources, rather than considering the following one to update the earlier ones. 

The reason I think so is because nonexistence of a header field in the 103 response does not imply that the header field will not exist in the final response, since we are not required to include in 103 response all the headers that are expected to be included in the final response.

So consider the following example: a caching intermediary might generate an Early Hints response from a stale-cached response. That Early Hints response could contain a header field that will never be included within an Early Hints response sent from the origin. In such case, considering both of the Early Hints responses as genuine makes the most sense.
