### ISSUE TITLE
UTF-8

### ISSUE THREAD

**Issue by evert** [httpwg/http-extensions#537]
I noticed the structured headers proposal strictly ignores UTF-8, because it's not used much. The recommendation is to use the binary format instead.

I thought that [RFC8187](https://tools.ietf.org/html/rfc8187) was fairly good for this.

I can see structured-headers to be a super useful generic way to describe new standard and proprietary headers, but ignoring UTF-8 means we're limited in what categories of data probably unsafe for the purpose of a header.

Is there a possibility to merge the syntax of RFC8187? It's true that it might not be used as much in practice, but it might expand the potential use-cases. Furthermore, as an implementor I don't have to worry about what someone might encode. The binary format doesn't quite cut it, because it doens't provide a hint as to how a generic client might decode it.

**Comment by mnot** [comment]
This has been discussed a fair amount; non-ASCII payloads in headers is pretty rare (since headers are generally not displayed to users).

You could encode it as binary, or you could use percent-encoding inside a string.

If there's significant demand for it, we could add a new type, but then we need to be able to discriminate it from ascii strings -- both on the wire and in APIs.

**Comment by annevk** [comment]
It'd be good to have use cases indeed. The only case I've seen folks make for this is URLs, which end up being ASCII-compatible once parsed, so are not that compelling.

If we do this a variant on binary makes the most sense to me, where we run https://encoding.spec.whatwg.org/#utf-8-decode-without-bom-or-fail on the bytes before returning the value.

**Comment by evert** [comment]
One thing I'm running into is providing a Title for a link. Basically the specification is saying right now is that Headers are strictly identifiers for computers, and never information for humans.

**Comment by annevk** [comment]
I think it's saying that UI is the exceptional case and that in such exceptional cases you can use "binary" plus UTF-8 processing on top.

**Comment by evert** [comment]
While I understand the argument that it might not be an extremely common case, I am kind of left wondering what the specific argument *against* UTF-8 support, especially in light of the fact that an established mechanism for this exists.

**Comment by mnot** [comment]
Because developers have been trained to use it, and if it's available as a "native" option, will use it out of habit / cargo culting.

While in most places UTF-8 is clearly the right thing to do, this is not at all true in protocols; years of experience has shown that it causes performance overhead, bloat, imprecision, confusion, and sometimes security issues.

It's better to make the right thing easier to do (strings) and make the usually not-right thing harder to do (utf-8). One of the objectives for Structured Headers is to leave as few foot guns lying around as possible.

**Comment by evert** [comment]
Sounds like a solid reason. At least we still have the other syntax for anything else.

**Comment by mnot** [comment]
OK, closing.

**Comment by royfielding** [comment]
FWIW, I disagree with the conclusion. The only compelling reason I can think of to move structured header fields forward on the standards track is if it provides a means to communicate more than the existing HTTP generic parsing algorithm. Basically, that means providing a safe way to introduce UTF-8 and/or standard date/delta formats. Both have been excluded from SH, so 👎
