### ISSUE TITLE
Refer to http-core

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#550]
... when available.

**Comment by mcmanus** [comment]
the first section references 7230.. which immediately begs the question of what about 7540.

assuming http-core won't be an rfc before this is published (and its not worth waiting for it) it would probably be good to have a paragraph just saying that 7230 defines both semantics and wire protocol, and 7540 is an alternative wire protocol for those same semantics (ummm.. plus push.).. and that your text in bcp56bis is generally scoped to the semantics unless otherwise noted. That might at least sort things out a bit.

this might also be a place to say that best practices of using http limit themselves to the semantics.. 4.1 kinda says that - not sure about a specific suggestion

**Comment by mnot** [comment]
My assumption has been that once core settles down, we'll change references appropriately, and this will sit in the queue depending on core.
