### ISSUE TITLE
Server Push

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#579]
Do we feel confident enough to say anything about Push yet? Or conversely, should we warn that we don't know if it's going to be useful?

**Comment by martinthomson** [comment]
Sure.  There is a risk that this dates the document, but then we're committing to maintaining this more actively in the next few years anyway.  I think we probably want to say something like.

Usefulness for web performance: questionable, see 103.
Usefulness for other applications: maybe.
Availability of APIs: patchy.

**Comment by mnot** [comment]
@martinthomson see 9985fa930be5

**Comment by sebdeckers** [comment]
(See also: comments on the commit)

This language sounds very strange in the light of recent(ly improved) implementations of Server Push in major web development frameworks (e.g. Node.js v10) and servers (Nginx). Most CDNs also have support for Server Push so that claim is dubious. All major browsers support it.
