### ISSUE TITLE
[cache digests] Eliminate requirement that the digest size is a power of 2

### ISSUE THREAD

**Issue by yoavweiss** [httpwg/http-extensions#607]
During the implementation of the [Cache Digests reference implementation](https://github.com/yoavweiss/cache-digests-cuckoo) I [realized](https://github.com/yoavweiss/cache-digests-cuckoo/commit/3ee4a45bf0bc03ea47ae7125e409b41d57acb198) that the digest size has to be a power of 2. Otherwise the `xor` operation on the primary index can lead to an out-of-bounds write, resulting in memory and correctness issues.

An alternative to that approach would be to:
* Do an out-of-bounds check to the `xor` operation and if it is out-of-bounds, take as an index the out-of-bounds value minus the digest size.
* Add a bit to the fingerprint which indicates that the alternative index was out-of-bounds.
* In the future, when a fingerprint is displaced and need to be returned to the primary index, the "out-of-bounds" bit can be used as an indication that the original `xor` operation was out-of-bounds, and instead of the index, the `xor` operation now can use the original out-of-bounds index.

@kazuho - Does that make sense?

It will cost us a bit more space (extra bit per fingerprint), but will make the digest size significantly more flexible.

**Comment by kazuho** [comment]
@yoavweiss Thank you for noticing and raising the issue.

I think the proposed solution is plausible. OTOH, I am not sure if we need the flexibility.

I'd assume that a client would not resize the hash every time it adds / removes an entry. I'd rather expect it to resize it based on exponential backoff. That means that in the average case, we will not be transferring a optimally-sized Cuckoo hash anyways. Considering that, I fear having 1-bit overhead for every entry might actually lead us to seeing a bigger hash in practice.

Note also that allowing a table size other than power-of-two increases the CPU cost since it means that we cannot rely on bit operations for calculating modulo.

**Comment by yoavweiss** [comment]
This is not about resizing the table, but about finding an alternative index in case of a collision.

Alternatively to my approach which adds an extra bit, @bdupras and @beala have an alternative [approach](https://github.com/bdupras/guava-probably/blob/10a738234de3830c8bb0dd8d1617e0df123607cf/src/main/java/com/duprasville/guava/probably/CuckooStrategyMurmurBealDupras32.java#L134-L169) for Guava-Probably, which seems to be providing the same benefits without the overhead.

Essentially (IIUC), they calculate a predicable but randomly distributed number from the fingerprint and use that as an offset from the original index. They make sure that it doesn't fall on the original index by requiring that the offset is odd and that the size of the digest is even.




> Note also that allowing a table size other than power-of-two increases the CPU cost since it means that we cannot rely on bit operations for calculating modulo.

That's a good point, and implementations can choose to stick with power-of-two digest sizes. But figuring out a way to remove that as a requirement seems like a win. (especially if we don't have to pay the "extra bit per fingerprint" tax after all)

**Comment by bdupras** [comment]
I'm curious, what digest sizes are you anticipating from implementations?

**Comment by beala** [comment]
I thought it might be useful to post a plain english explanation of the indexing strategy @bdupras and I proposed:

The property that we need to maintain is that the primary and secondary indices can be calculated in terms of each other (ie, the only info we have available is their position in the table, and the fingerprint). We maintain this property in the following way. 

First, we calculate an offset, which is based on the fingerprint. Crucially, this offset is always odd: `offset = makeOdd(hash(fingerprint))`. 

This offset is then either subtracted or added to the current position to get the other index. If the current index is odd, it's added. If it's even, it's subtracted. Since the offset is always the same, this jumps between the two possible indices. Further, because adding or subtracting an odd number always flips the evenness or oddness of a number, this guarantees that one position is always even and one is always odd. 

In pseudo code, it looks like this:

```
makeOdd(x) = x    [if x is odd]
             x+1  [if x is even]

flipIndex(currentIndex) = currentIndex + makeOdd(hash(fingerprint))   [if index is odd]
                          currentIndex - makeOdd(hash(fingerprint))   [if index is even]
```

**Comment by kazuho** [comment]
@bdupras 
> I'm curious, what digest sizes are you anticipating from implementations?

The anticipation is that we would have typically up to hundreds (but not thousands) of entries. Please refer to https://github.com/httpwg/wg-materials/blob/gh-pages/ietf100/cache-digest.pdf.

**Comment by kazuho** [comment]
@beala That's interesting. Thank you for the explanation.

OTOH, I am not sure if it is actually optimal compared to using XOR for a table having a size of power-of-two.

The approach you described distributes the secondary index to N / 2 entries where N is the size of the table. IMO, it is essentially the same as omitting the last bit of the fingerprint (and hard-coding it as `1` instead) when we use XOR-based approach.

What I am trying to state here is that while I can understand the potential benefit of using the approach for tables that do not have the size of power-of-two, I do not see a benefit for the cache-digest use-case adopting that approach, under the assumption that the clients would resize the table using exponential backoff.

**Comment by yoavweiss** [comment]
Yet another alternative, is to (again *sigh*) switch filter methods to one that doesn't have a power-of-two requirement, and does enable resizing, which may significantly reduce the memory requirements.
There was a recent paper about a [Counting Quotient Filter](https://blog.acolyer.org/2017/08/08/a-general-purpose-counting-filter-making-every-bit-count/), which seems promising on that front.

I'm not super excited about changing the filter algorithm once again, but it may be the right call if it'd make implementations on both clients and servers more flexible. Performance-wise and from a digest-size perspective, the Quotient Filter paper claims it's on par with Cuckoo filters.

**Comment by mnot** [comment]
It's starting to sound like we should put the filter algorithm into the frame type name, to future-proof...

**Comment by mnot** [comment]
We want to avoid having too many stabs at this, otherwise it's not going to be useful, because you'll have to figure out what kind of digest the server wants (although I suppose if you have cached state, we could figure something out).

**Comment by yoavweiss** [comment]
> It's starting to sound like we should put the filter algorithm into the frame type name, to future-proof...

That may be the right call. Otherwise, maybe include a flag which will enable algorithm changes in the future.

**Comment by yoavweiss** [comment]
> We want to avoid having too many stabs at this, otherwise it's not going to be useful, because you'll have to figure out what kind of digest the server wants (although I suppose if you have cached state, we could figure something out).

It's true that a different frame names for different algorithms would probably make digest negotiation easier.

**Comment by kazuho** [comment]
IIUC, the reason we did not ship the draft with Golomb-coded sets as experimental was because we thought that having a browser that implements Cache Digests is important.

Considering that, my preference is to wait for a working H2 client implementation that uses whatever algorithm that fits it's needs, then consider if we can adopt the implemented algorithm as-is, or adjust it if necessary.

Changing the digest algorithm is something that can always be done later.

**Comment by mnot** [comment]
Closing, as we're no longer working on cache digests.
