### ISSUE TITLE
Clarify behaviour on page refresh for SameSite cookies

### ISSUE THREAD

**Issue by mozmark** [httpwg/http-extensions#628]
There seems to be some ambiguity around same-site-ness for requests from refreshes. See https://bugzilla.mozilla.org/show_bug.cgi?id=1459321

**Comment by april** [comment]
Some things to think about:

- Do `location.reload()`, `window.location = ...` and other non-user initiated requests count as redirects? Should they send `SameSite` cookies?
- Should POST data be sent on a refresh?

**Comment by johnwilander** [comment]
We've got the meta refresh too.

**Comment by johnwilander** [comment]
The Mozilla issue mentions web platform tests. Were any ever written?

**Comment by chlily1** [comment]
It seems sensible to have different behavior for
1. user/browser-initiated reloads (e.g. pressing the "refresh" button in the browser UI), vs.
2. web-initiated reloads such as `location.reload()`, `meta http-equiv="refresh"` etc.

In case 1, if `SameSite=Strict` cookies are withheld on a cross-site navigation, the page may be broken due to the absence of these cookies, prompting the user to refresh the page. If the cookies were then sent on the refresh, this would defeat the CSRF protection of withholding the cookies in the first place.

In case 2, the page is willingly reloading itself, so it would make sense to give it all of its cookies.

There's no spec infra to distinguish these cases, currently. It's not observable to web developers what type of reload is happening. In the HTML spec, the paragraph below [here](https://html.spec.whatwg.org/#dom-location-reload) basically says that "browser-initiated reloads follow the same spec code path as other reloads".

I'm not sure this is worth codifying in the HTML spec, since it could be dangerous to expose this difference to the web. Should we put something in the cookie spec to the effect of "browsers may withhold `SameSite=Strict` cookies on user-initiated reload requests"?

There's also the separate question of what to do about web-initiated (case 2) reloads: Following a cross-site navigation, Chrome withholds `SameSite=Strict` cookies for case 1, but will send them for case 2. Firefox, on the other hand, also withholds them for the latter. In the [WPTs](https://github.com/web-platform-tests/wpt/blob/master/cookies/samesite/form-get-blank-reload.https.html) for reloads, web-initiated reloads are used and `SameSite=Strict` cookies are expected to be withheld. (There is currently [no way](https://github.com/web-platform-tests/wpt/issues/26893) to write a WPT that emulates a browser/user-initiated reload.)

**Comment by englehardt** [comment]
> It seems sensible to have different behavior for
> 
>     1. user/browser-initiated reloads (e.g. pressing the "refresh" button in the browser UI), vs.
> 
>     2. web-initiated reloads such as `location.reload()`, `meta http-equiv="refresh"` etc.

This sounds right to me. I've flagged a few Firefox folks in https://bugzilla.mozilla.org/show_bug.cgi?id=1459321#c12 to see if they have any concerns we may have missed.

**Comment by englehardt** [comment]
Firefox needs to align with the new spec language, we'll track that in Bug 1459321. Closing since the spec has been updated.
