### ISSUE TITLE
bcp56bis privacy guidelines section

### ISSUE THREAD

**Issue by mcmanus** [httpwg/http-extensions#655]
the doh wg is dicsussing privacy implications of using http as a substrate.

that made me realize that this is ground bcp56bis could cover to help applications realize the implications of generic http from that perspective.

**Comment by mnot** [comment]
Had the same thought; on it.

**Comment by mnot** [comment]
_straw-man; needs references_

## Privacy Considerations 

HTTP clients can expose a variety of information to servers. Besides information that's explicitly sent as part of an application's operation (for example, names and other user-entered data), other information can be gathered through less obvious means -- often by connecting activities of a user over time. 

This includes session information, the tracking the client through fingerprinting, and mobile code.

**Session information** includes things like the IP address of the client, TLS session tickets, Cookies, ETags stored in the client's cache, and other stateful mechanisms. Applications SHOULD avoid using session mechanisms unless they are unavoidable or necessary for operation; these risks SHOULD be documented and implementations SHOULD be encouraged to allow clearing such state.

**Fingerprinting** uses unique aspects of a client's messages and behaviours to connect disparate requests and connections. For example, the `User-Agent` request header conveys specific information about the implementation; the `Accept-Language` request header conveys the users' preferred language. In combination, a number of these markers can be used to uniquely identify a client, impacting its control over its data. As a result, applications SHOULD only emit the information they need to function in requests.

Finally, if an application exposes the ability to run **mobile code**, great care needs to be taken, since any ability to observe its environment can be used as an opportunity to both fingerprint the client and to obtain and manipulate private data (including session information). For example, access to high-resolution timers (even indirectly) can be used to profile the underlying hardware, creating a unique identifier for the system. Applications SHOULD avoid allowing the use of mobile code where possible; when it cannot be avoided, the resulting system's security properties MUST be deeply scrutinised.

**Comment by martinthomson** [comment]
I assume that this assumes https. Otherwise this would need to be broader.

**Comment by mnot** [comment]
Happy to take additional changes / suggestions, etc., either as a PR or separate issue.
