### ISSUE TITLE
Date type

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#685]
It would get some use, if we could figure out how to back port.

**Comment by mnot** [comment]
The main issue would be reliably recognising the date in text. If it starts with one of `MTWFS` (uppercase) that would work, but it would preclude expanding identifiers to start with any of these uppercase letters.

**Comment by phluid61** [comment]
If you want to make back-porting easiest, that would mean accepting RFC850 and `ctime()` formats \[[*](https://tools.ietf.org/html/rfc7231#section-7.1.1.1)\].  Then it would be trivial to say that `Date` and `If-Modified-Since` and the rest are "structured headers whose value is a Date".

A middle ground would be to deny the legacy formats -- only allow IMF-fixdate with a single 'GMT' zone -- which for the most part is real-world-compatible but goes against an RFC7231 MUST.

But if you're making a new syntax like that, you might as well go all in and wrap it in `[]` or something.

In either case, I think it's an interesting idea, especially if it can be sorted out before something like HTTP-QUIC really solidifies where there's an opportunity to encode dates more efficiently.

**Comment by mnot** [comment]
Thing is, if it's new syntax, it can just be specified as an integer number of seconds delta from a/the epoch.

**Comment by enygren** [comment]
Using integer seconds makes me very wary about introducing/encouraging new things that will encounter Y2038 protocols, especially in wire protocols.  (Yes, we can be clear that implementations must be 64-bit but it still seems like it could encourage more implementations to use signed 32-bit integers.)

**Comment by enygren** [comment]
From the httpbis chat, Jonathan Lennox also points out:

"The problem with seconds-since-the-epoch is you run into leap second issues. ISO 8601 might be better?"

**Comment by mnot** [comment]
@enygren we're not specifically defining how to serialise a date in SH here, I think we just want to convince ourselves that we don't need a dedicated Date type.

Having said that -- integers in SH are required to be 64-bit already. WRT leap seconds, I strongly suspect that it's an issue with existing implementations for things like freshness calculation anyway. WDYT?

**Comment by mnot** [comment]
Closing with no action, per discussion in Bangkok. If you have new information / disagree, please ask for reopening.
