### ISSUE TITLE
need to define extensibility for alt-svc parameters

### ISSUE THREAD

**Issue by reschke** [httpwg/http-extensions#69]
must ignore? how to register new ones? IANA registry?

**Comment by enygren** [comment]
From discussions in various threads, it is sounding like "must ignore" is a better default behavior for unknown parameters.  Otherwise trying to guess which combinations of parameters will cause an AltSvc to be ignored becomes impossibly unwieldy.   If "manditory to understand before using a service" parameters are necessary, Martin has the good suggestion of adding a parameter that lists those extension parameters where not understanding them should cause a client to ignore a service.  For example a parameter:
      must="manditory1,manditory2"
such that:
    Alt-Svc: h2=":443"; ma=60; manditory1=1; manditory2="foo"; optional1="bar"; must="manditory1,manditory2"

Would cause the service to be ignored if the client didn't understand manditory1 or manditory2, but optional1 would be ignored if not understood.

**Comment by reschke** [comment]
I've seen that before in <http://greenbytes.de/tech/webdav/rfc2774.html#end-to-end.extensions> :-)

**Comment by mnot** [comment]
... which was promptly ignored by the whole world (except for spawning SOAP, and we know how that went...)

**Comment by mnot** [comment]
Discussed in Prague; sense of the room is to have extensibility at the parameter level. Also, sense was to go ahead and establish a registry.

**Comment by reschke** [comment]
So must-ignore-unknown parameters (but process what remains), and add registry, right?

**Comment by mnot** [comment]
yes.

**Comment by reschke** [comment]
"IETF review", I guess? (would be the same as Cache-Control)

**Comment by mnot** [comment]
Let's talk on-list. I think that bar might be a bit high.

**Comment by reschke** [comment]
Changes done in https://github.com/httpwg/http-extensions/commit/eed78be6f8340a1019a22022168c35fa68654feb, let's discuss IANA details separately when needed.
