### ISSUE TITLE
Purpose of the Content-DPR hint is not entirely clear.

### ISSUE THREAD

**Issue by malchata** [httpwg/http-extensions#697]
I have personally had an especially difficult time tying the purpose and usefulness of the `Content-DPR` client hint to a specific use case, and I don't think I'm alone in this. While the spec at large is straightforward and reads well, I think `Content-DPR` could benefit from a concrete example of how it might be used by the client. Currently, the spec says the following of `Content-DPR` in [section 4](https://tools.ietf.org/html/draft-ietf-httpbis-client-hints-06#section-4):

> The client can use this information to perform additional processing on the resource - for example, calculate the appropriate intrinsic size of the image resource such that it is displayed at the correct resolution.

This seems a bit vague to me. Does Chrome act on this response header a specific way? Are implementing browsers _expected_ to? And what's a specific example where that may be the case? Does any suboptimal behavior result when DPR is _not_ confirmed with `Content-DPR`, and if so, what instances?

**Comment by eeeps** [comment]
I'll add one concrete example of un-clear-ness – my employer, Cloudinary, implemented (and still implements) `Content-DPR` incorrectly. We echo back the `DPR` on the request, no matter how the width of the returned resource matches up with the requested `Width`. The example in section 4 could use some fleshing-out!

Jeremey’s questions are all about describing how `Content-DPR` is actually used on the front end – I'll add that I think there should be more about how the server in the example calculated the `Content-DPR: 1` that it sends back. I assume that the resource it responded with had a width of 160 pixels? That should be added to the example, along with a general formula that:

`Content-DPR` should = response resource width, in pixels ÷ ( request `Width` ÷ request `DPR` )

Related question that the spec may be able to shed some light on – what should servers do, if they don't have both a `Width` and a `DPR`?

**Comment by yoavweiss** [comment]
I think we'd have a hard time explaining the purpose of Content-DPR as part of an IETF draft that's fairly removed from the concepts that govern its impact: The density of the impacted images which then take part in the calculation of their density-corrected intrinsic dimensions. That one more reason why we might be better off defining the image specific bits closer to Fetch and HTML.

> Does Chrome act on this response header a specific way?

Very much like requesting an image using a srcset `x` descriptor, `Content-DPR` will mean that the image's intrinsic dimensions are being corrected by the `Content-DPR` value. E.g. sending down a 200x200 image with `Content-DPR: 2` and no other layout information, would mean the image is laid out ass a 100x100 image.

> Does any suboptimal behavior result when DPR is _not_ confirmed with `Content-DPR`, and if so, what instances?

Yeah, the wrong density corrected intrinsic dimensions. In order to notice that, you'd need your images layout to not be constrained by other means (e.g. CSS).

> what should servers do, if they don't have both a `Width` and a `DPR`?

That depends on the server. Servers should restrict the image dimensions to `Viewport-Width` as images are typically not wider than that, but lacking more specific width information, it's tricky to restrict the images further.

**Comment by malchata** [comment]
> I think we'd have a hard time explaining the purpose of Content-DPR as part of an IETF draft that's fairly removed from the concepts that govern its impact: The density of the impacted images which then take part in the calculation of their density-corrected intrinsic dimensions.

I think it's possible to use language which talks about potential outcomes of failing to adhere to the specification. For nascent or underdocumented technologies, it's not uncommon for developers to seek out specs to understand how they work.

I claim ignorance of the nuanced interactions between specifications and implementations. Yet, I can't see how improving clarity around this in the specification itself could be bad for developers _or_ implementors. In a spec that clearly and superbly explains the vast majority of concepts and behaviors surrounding client hints, I personally felt this (and the issue raised in #698) lacked clarity in authoritative sources. While I understand now how `Content-DPR` works (as well as the concepts referenced in #698), the knowledge was hard-won in my initial research.

That said, if it makes sense to define this behavior elsewhere, I'm supportive. Feel free to tag me in any related issue(s).

**Comment by yoavweiss** [comment]
Yeah, that's the intent.

**Comment by igrigorik** [comment]
Content-DPR is now living in the Fetch spec, closing.

Ref: https://github.com/yoavweiss/client-hints-infrastructure/blob/master/specification_situation.md
