### ISSUE TITLE
Default values for Language (and others?)

### ISSUE THREAD

**Issue by jyasskin** [httpwg/http-extensions#740]
https://github.com/httpwg/http-extensions/compare/master...jyasskin:incomplete-cache-example shows an example of an origin server that contains English, French, and German versions of a resource, a cache that has cached the English and French versions, a request that asks for German or Spanish, and, I believe, permission in the spec for the cache to return the English version instead of asking the origin server for the German version.

This happens because https://httpwg.org/http-extensions/draft-ietf-httpbis-variants.html#content-language appends the first Variant to the list of requested languages even if the list of requested languages overlaps with the available variants. Is this a mistake in the algorithm, or intentional for some reason?

**Comment by mnot** [comment]
The language algorithm does that so that an origin can denote a 'default' language -- i.e., what to serve if there isn't any overlap between the client's preferences and what's available. 

For example, if a user configures their browser to send `Accept: de` and the page is only available in English and French, there needs to be a way to say "send English by default."

I don't know of any use case where someone would want to serve a hard error when the language doesn't match, but if that's in scope, we could figure something out.

If you're looking for something more deterministic in caches (here, the distinction between "these ar the responses that are available and preferred" and "here's the default" is blurred), I'm interested.

P.S. in that diff, the line with the comment "prefers French, will accept English(?)" seems wrong.
```

**Comment by jyasskin** [comment]
I think #741 establishes the default language without confusing it with the responses that are available and preferred.

I am also not interested in a hard error when the language doesn't match.

And thanks, I've fixed the example.

**Comment by mnot** [comment]
I'm not entirely happy with the optionality of behaviour on the cache's part with those MAYs.

The most explicit thing we could do would be to break this information out into a separate header (e.g., `Variant-Defaults`), but sticking with the current syntax for the moment, what if we had special values that, when occurring in that first slot, indicate that the default should NOT match?

E.g.,

~~~
Variants: Accept-Encoding;gzip;br, Accept-Language;!;en ;fr
~~~

where `!` does the magic.

**Comment by jyasskin** [comment]
I'm personally happy with turning those MAYs into MUSTs. They're MAYs because that's what was in the older RFCs, but I agree that I don't like making things optional. If I do this in my update tomorrow morning, do you still want to explore the `!` token? I don't really like it because it seems like always the wrong thing for a client to send. I also don't see a particular need to pull the defaults out to a separate header.

**Comment by mnot** [comment]
I'm a bit interested in `!`, but not adamant. I think it'd be fine if they flipped to MUST as long as the implications were noted.
