### ISSUE TITLE
Clarify difference from chunked

### ISSUE THREAD

**Issue by MikeBishop** [httpwg/http-extensions#752]
I know we're late in the document cycle, but some feedback that was relayed to me:  It's not always clear why this mechanism is better than simply using chunked encoding to stream the live content.  I think the answer is in the document title -- this permits the same resource to serve both live content (as chunked) *and* random-access to past content (as a range request).

**Comment by craigpratt** [comment]
[Thanks for the feedback/thoughts. I actually thought the document cycle was over - but this draft has been on such a slow burn (and I've had so much go into and out of my brain) that the process never crystalized in my head - despite a couple taps with the clue stick by Patrick and company. If there was an IETF dunce cap, I'd nominate myself for it...]

Anyway, whether the content is transferred as chunked or non-chunked is actually orthogonal to the to whether the content is static or live/aggregating - and also orthogonal to Range - unless there's something I'm missing? (I see Chunked in the "how to transfer" category and content type/Range are "what to transfer" category)

Specifically, for strictly live content (non random-access), you can transfer it chunked or non-chunked. Chunked allows the sender to more explicitly signal the end of the live streaming - and allow the connection to stay open - by sending a 0-length chunk. In non-chunked transfer of live content, the sender has to close the connection when the live streaming is completed (since Content-Length can't be provided). (discussing only HTTP 1.1 here)

So yeah - this entire draft is discussing how to support live content that also has random access support - and is titled accordingly. But as is the case with non-random-access live streaming, content transfer of Range responses can be chunked or non-chunked. 

I intentionally left out "Content-Length" headers from the examples because that would imply non-chunked responses and I didn't want to confuse people. And while I could discuss both chunked and non-chunked response forms, I was trying to keep the draft focused/short - and I wanted to keep it future-proof by not discussing transfer forms (esp in the world of HTTP/2+). I also didn't discuss non-random-access live content (as a "remedial/background" section for similar reasons.

I'd like to get this (experimental) draft "out there" and get some feedback from implementors on what's working/not working (and what need to be better clarified/described). But if there's a real issue with comprehension we should address it in this draft. So let me know if you think this falls into that latter category. (this is all something I need to tell myself or I'll keep editing forever)

Disclaimer: I'm writing this off the top of my head - and haven't been working in HTTP specs for a while. So please correct me if I missed some rule about chunking, Range, etc.

**Comment by martinthomson** [comment]
I think that Craig's analysis is correct.  Chunked encoding is orthogonal to this.
