### ISSUE TITLE
define a URI reference type

### ISSUE THREAD

**Issue by royfielding** [httpwg/http-extensions#782]
SH does not have a common type for URI references, which is odd given how common it is to distinguish references from other forms of string. The expected syntax would be the same as the Link header field:

     sh-item      += sh-reference
     sh-reference  = "<" URI-reference ">"

or something like that.

**Comment by bsdphk** [comment]
The reason this was not in my original work, was that it was based on existing headers where (at least at the time) URIs were in a header of their own.

Where we are now, having a URI type probably makes sense.

**Comment by wtarreau** [comment]
On Wed, Apr 03, 2019 at 06:17:00AM -0700, Poul-Henning Kamp wrote:
> Where we are now, having a URI type probably makes sense.

+1, at least because it could allow better normalization.

Willy

**Comment by mnot** [comment]
My inclination is to make this a strict URI reference, not a "sloppy" URL. Thoughts? @annevk?

**Comment by annevk** [comment]
I don't think browsers would implement a second URL parser for this, if that's what you're asking.

**Comment by mnot** [comment]
Even if we define the step-by-step algorithm, like the other types?

**Comment by royfielding** [comment]
Personally, I don't see any reason to limit URI reference other than to say that non-URI octets must be utf-8. That is something we could not say before, but I have no problem saying it for SH.

**Comment by mnot** [comment]
Are we confident that UTF-8 would survive all hops?

If we're going to loosen it up, we should refer to a specific algorithm, so that it's interoperable. The obvious (and probably only workable) candidate is the [whatwg one](https://url.spec.whatwg.org/#url-parsing), but I need to dig into how workable that would be here.

If we use it, we also have to figure out how to reference it; while browsers can keep up with changes over time it's not clear that other libraries will.

**Comment by royfielding** [comment]
URI References is a draft I have already been working on -- I just put it aside for httpbis v5.

**Comment by mnot** [comment]
I'm reluctant to take a dependency on that at such a late stage; maybe we should add a URL type after shipping SHv1.

**Comment by royfielding** [comment]
It's just a string for SH.  My draft would update RFC3986, orthogonal to SH.

All you have to define is the delimiters and refer to it as a URI reference, which is defined by RFC3986. The SH algorithm is a string with angle bracket delimiters, unconstrained by the syntax of URI, which is the same thing 3986 says. All non-URI characters inside that string are handled by the reference algorithm, not the SH algorithm.

**Comment by annevk** [comment]
So it's a UTF-8 string with a different type. Since it's unclear what the base URL is, it cannot be used for "follow your nose", right? What potential benefits does it give?

**Comment by royfielding** [comment]
By default, the base URI would be the same as for all other header fields (the request target). A given field might define some other base, but that would be rare. I would not expect a parser to resolve the reference until it needs to (i.e., evoking the semantics).

**Comment by mnot** [comment]
If it's "just a string for SH", it seems like we're not adding much value over... strings. The whole point of SH is to make sure that things are parsed the same way.

**Comment by martinthomson** [comment]
I would not take a signal that browsers won't do anything special as a blocker. Others may do something special.

**Comment by bsdphk** [comment]
> If it's "just a string for SH", it seems like we're not adding much value over... strings. The whole point of SH is to make sure that things are parsed the same way.

I can see the point of having a SH-type for UR[IL]'s which can cabin and track future developments in that space, but we need to stick a firm SH definition on it.

The SH definition can and should be loose with respect to whatever normative references think a UR[IL] might currently look like, because it just has to reliably pluck the UR[IL] out of the SH stream, it does not have to interpret the UR[IL] or explain its semantics.

I don't think it is SH's job to SHALL 3986 for normative semantics of the data transferred, but a SHOULD or MUST makes sense.

I am however firmly NO on non-ASCII

Strawman:

    sh-urichar = %21-%3C / %3E-%7E
 
    sh-uri = "<" 1*(sh-urichar) ">"

That way, SH does not get in the way of anything 3986 or successors might want to do.

If we wanted to we could do:

    sh-urichar = %21-%3C / %3E-%7E
 
    sh-uri-strict = "<" 1*(sh-urichar) ">"
    
    sh-uri-loose = "<" "<" 1*(sh-urichar) ">" ">"

where sh-uri-strict is SHALL 3986 and sh-uri-loose is for non-3986 URIs

**Comment by reschke** [comment]
> I don't think it is SH's job to SHALL 3986 for normative semantics of the data transferred, but a SHOULD or MUST makes sense.

MUST == SHALL

> I am however firmly NO on non-ASCII

I also don't see why to allow it here but not in strings...

**Comment by mnot** [comment]
I'm now -1 on adding this; I don't think we're going to get something useful out of this without a lot more work, and SH is almost done. Nothing stops this being defined later.

**Comment by bsdphk** [comment]
works for me.

**Comment by reschke** [comment]
I think the ability to apply this to the Link header field is pretty compelling.

**Comment by bsdphk** [comment]
It doesn't really make any real-world difference in context of headers like Link where the only content is the URI.

Where it would make a difference would be headers that have URI(s) and other data in a single header.

**Comment by reschke** [comment]
I think you are confusing "Link" (which has other content) with "Location".

**Comment by kazuho** [comment]
I think not having a URI type would be more consistent to our previous conclusion to not have the Date type (#685).

**Comment by tfpauly** [comment]
Consensus in the room in Montreal was to not include a specific URI type (to close this issue).

**Comment by bsdphk** [comment]
works for me.
