### ISSUE TITLE
Trailing '*' in binary

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#785]
The syntax requires a '*' at the end, but this doesn't seem to be necessary.

**Comment by bsdphk** [comment]
That is a left-over detail from a much earlier version which supported recursive structures.

I like the symmetry of having "quoted" types (string, binary, possibly URI) being bracketed in both ends, but I am not religious about it.

**Comment by wtarreau** [comment]
On Wed, Apr 03, 2019 at 06:14:06AM -0700, Poul-Henning Kamp wrote:
> That is a left-over detail from a much earlier version which supported recursive structures.
> 
> I like the symmetry of having "quoted" types (string, binary, possibly URI) being bracketed in both ends, but I am not religious about it.

I like bracketed strings as well as long as they use a different opening
and closing character, when it's the same it always gets painful once this
has to be embedded somewhere else.

With that said I'm not convinced that leaving only the heading star would
significantly improve readability, reliability, or anything.

Willy

**Comment by bsdphk** [comment]
For "inscrutiable" data like base64, the trailing asterix does make it easier to see that truncation did not happen.

**Comment by wtarreau** [comment]
On Wed, Apr 03, 2019 at 03:28:28PM -0700, Poul-Henning Kamp wrote:
> For "inscrutiable" data like base64, the trailing asterix does make it easier to see that truncation did not happen.
Good point!

Willy

**Comment by mnot** [comment]
@martinthomson do you find that convincing?

This is close to bike shedding, but I like it better balanced.

**Comment by martinthomson** [comment]
I really don't care, but will observe that truncation is unlikely in h2. And = is also good for one in three values.  The notion of aesthetics is bizarre, but everyone has different views on that.

**Comment by wtarreau** [comment]
On Fri, Apr 05, 2019 at 12:07:56AM -0700, Martin Thomson wrote:
> I really don't care, but will observe that truncation is unlikely in h2. And
> = is also good for one in three values.  The notion of aesthetics is bizarre,
> but everyone has different views on that.

Well, to fuel the discussion, I'd say that truncation may happen at the
application layer when retrieving the value before decoding it, but it's
just the same for any other header field or URI or whatever so we don't
significantly improve the situation with this.

Also some other types are prefixed with a "?" and we don't postfix the
value with this character.

While initially my intuition made me prefer the star on each side,
probably due to aesthetic reasons influencing me, now as a developer
I'm thinking that having to add special processing in my parsers to
stop on '*' or '\0' is probably more code for little value, and that
there will unlikely be some specific code to deal with the rare error
where the value is missing the trailing '*', which also means that we
may see such occurrences appear in field.

So in the end I think I'm more in favor of dropping the trailing star
to limit implementation divergence.

Willy

**Comment by mnot** [comment]
We can test for missing `*` to assure consistent implementation (and IIRC we already do).

I'm going to close this as a bike shed; if someone violently disagrees, I guess we can reopen, but I'm not hearing that yet.
