### ISSUE TITLE
Active vs. passive fingerprinting

### ISSUE THREAD

**Issue by yoavweiss** [httpwg/http-extensions#786]
At IETF 104's HTTPWG meeting, @ekr raised concerns about the categorization of Client Hints as an active fingerprinting vector, claiming that they are in-fact passive, because (IIUC) they can be persisted beyond the point where the information was requested, and persisted for future requests on current and future sessions to the same host.

My response to that was that this is something origins already do with cookies today, and that Client Hints access can be monitored by browsers in similar ways to other active fingerprinting vectors. On top of that, Client Hints opt-in persistence is purged when the user deletes their cookies, and support is disabled when JS is disabled.

Talking to @martinthomson, it seems like there's another concern around the fact that the hints change when the values does. That seems similar to me to various change events around the exposed values (which do exist for most if not all Client Hints features). Browsers can track CH value changes in similar ways to active fingerprinting vector change events, and treat registration as if the origin accessed the equivalent API and subscribed to receive future events. Similarly, browsers can also mitigate that change reporting in similar ways (e.g. omit the hints or lie about them in some cases).

@martinthomson & @ekr - Does the above properly captures the concerns you raised? If so, do the mitigations make sense and properly address them?

If they do, I'm happy to modify the security & privacy consideration sections to reflect the above

**Comment by snyderp** [comment]
I believe there is a good deal of overlap between this issue and the concerns raised in https://github.com/httpwg/http-extensions/issues/786

**Comment by yoavweiss** [comment]
> I believe there is a good deal of overlap between this issue and the concerns raised in #786

#786 is this issue. I'm guessing you meant something different :)

**Comment by snyderp** [comment]
Derp you are exactly right, apologies! 

Here is the one I meant: https://github.com/httpwg/http-extensions/issues/767

**Comment by yoavweiss** [comment]
I believe those issues are rather different. The threat model here is persistence of the hints in the browser, where for #767 is seems like the threat model is persistence on the server side. As they are rather different, mitigations for either can be fairly different as well.

**Comment by snyderp** [comment]
I see, point taken. I meant mostly in terms of the discussion of whether or not CH is an increase in FP surface or not.  But I'm happy to deal with that discussion in both issues if thats preferred.

However, I'd like to reiterate my concern / position that its not sufficient to deal with concerns like these in non-normative security & privacy consideration sections; that to be an appropriate addition to the web, the normative portions of the document should be negative or zero regarding fingerprinting surface / privacy risk.

**Comment by yoavweiss** [comment]
@martinthomson and/or @ekr - does the above description match the concerns you raised during the WG meeting and after it? If so, do the mitigations I mentioned address those concerns? If not, why not?

**Comment by ekr** [comment]
> At IETF 104's HTTPWG meeting, @ekr raised concerns about the
> categorization of Client Hints as an active fingerprinting vector,
> claiming that they are in-fact passive, because (IIUC) they can be
> persisted beyond the point where the information was requested, and
> persisted for future requests on current and future sessions to the
> same host.

This seems approximately right. Take your location. With the JS
API, then the client knows whenever the server gets the location,
but with the hint, then the client does not. So, in this respect,
it's passive, not active.


> My response to that was that this is something origins already do with
> cookies today, and that Client Hints access can be monitored by
> browsers in similar ways to other active fingerprinting vectors. On
> top of that, Client Hints opt-in persistence is purged when the user
> deletes their cookies, and support is disabled when JS is disabled.
>
> Talking to @martinthomson, it seems like there's another concern
> around the fact that the hints change when the values does. That seems
> similar to me to various change events around the exposed values
> (which do exist for most if not all Client Hints features).

Right. I think this is the most worrying case.


> Browsers
> can track CH value changes in similar ways to active fingerprinting
> vector change events, and treat registration as if the origin accessed
> the equivalent API and subscribed to receive future events.

I don't quite understand this point. The key thing from my perspective
is that when the only way to get access to a property value is to
make an active request, then the browser knows each time it is accessed,
and has an opportunity to monitor for abuse. But when you can instead
get access to it by subscribing (which is what CH is), and this is
the preferred modality, then it's not really possible to monitor for
abusively high request levels.

For example, consider the case of PeerConnection. As we know, this has
high fingerprinting potential (due to IP disclosure) and so sites
routinely creating PCs for no reason is a marker of abuse. Of course
there are sites which have legitimate uses of PC, but they might
*also* be fingerprinting you. At present, we can distinguish these
by looking to see when they create PCs, but if we were to replace
PC by a hypothetical "host IP address" Client Hint, then it would
not be possible to distinguish sites which are both legitimate
PC users and fingerprinters from sites which are legitimate PC
users and not fingerprinters.

How does the browser "treat registration as if..." usefully?


> Similarly,
> browsers can also mitigate that change reporting in similar ways
> (e.g. omit the hints or lie about them in some cases).

I don't really see how this is going to work. The hints become
problematic if you omit them or lie.

**Comment by yoavweiss** [comment]
>  > At IETF 104's HTTPWG meeting, @ekr raised concerns about the categorization of Client Hints as an active fingerprinting vector, claiming that they are in-fact passive, because (IIUC) they can be persisted beyond the point where the information was requested, and persisted for future requests on current and future sessions to the same host.

> This seems approximately right. Take your location. With the JS API, then the client knows whenever the server gets the location, but with the hint, then the client does not. So, in this respect, it's passive, not active.

I'm not sure I get why. Can't the client consider every time the hint is sent to the server that the server got the info?

(location CH is not currently a thing, but we can have the same discussion for e.g. network info, which is).



> > Browsers can track CH value changes in similar ways to active fingerprinting vector change events, and treat registration as if the origin accessed the equivalent API and subscribed to receive future events.

> I don't quite understand this point. The key thing from my perspective is that when the only way to get access to a property value is to make an active request, then the browser knows each time it is accessed, and has an opportunity to monitor for abuse. But when you can instead get access to it by subscribing (which is what CH is), and this is the preferred modality, then it's not really possible to monitor for abusively high request levels.

I agree that Client Hints is equivalent to subscribing to an active fingerprinting vector. E.g. the `Viewport` CH is very similar in that way to `[MediaQueryList](https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList)`. JS code doesn't have to actively poll for MQ changes, but can get notified for them. I'm assuming that if developers have registered for that info, each time they'd get notified for it would be considered an "active request" for that information, and would be monitored for abuse. Similarly, browsers could track every time a CH value change is sent to the server and consider it an "active request" for that information for abuse tracking purposes. Does that make sense?



> I don't really see how this is going to work. The hints become problematic if you omit them or lie.

In what way? The hints should be built as a progressive enhancement, and browsers which would omit or lie about them can make sure that adopting sites actually treat them like that.

> For example, consider the case of PeerConnection. As we know, this has high fingerprinting potential (due to IP disclosure) and so sites routinely creating PCs for no reason is a marker of abuse. Of course there are sites which have legitimate uses of PC, but they might *also* be fingerprinting you. At present, we can distinguish these by looking to see when they create PCs, but if we were to replace PC by a hypothetical "host IP address" Client Hint, then it would not be possible to distinguish sites which are both legitimate PC users and fingerprinters from sites which are legitimate PC users and not fingerprinters. How does the browser "treat registration as if..." usefully?

I don't really understand this example, but maybe it requires more knowledge about how PC is used for fingerprinting. Is there fingerprinting "value" in revealing the user's IP more than once? How do browsers distinguish legitimate from abusive usage today?

**Comment by ekr** [comment]
On Tue, May 28, 2019 at 10:04 PM Yoav Weiss <notifications@github.com>
wrote:

> At IETF 104's HTTPWG meeting, @ekr <https://github.com/ekr> raised
> concerns about the categorization of Client Hints as an active
> fingerprinting vector, claiming that they are in-fact passive, because
> (IIUC) they can be persisted beyond the point where the information was
> requested, and persisted for future requests on current and future sessions
> to the same host.
>
> This seems approximately right. Take your location. With the JS API, then
> the client knows whenever the server gets the location, but with the hint,
> then the client does not. So, in this respect, it's passive, not active.
>
> I'm not sure I get why. Can't the client consider every time the hint is
> sent to the server that the server got the info?
>
> (location CH is not currently a thing, but we can have the same discussion
> for e.g. network info, which is).
>
> Browsers can track CH value changes in similar ways to active
> fingerprinting vector change events, and treat registration as if the
> origin accessed the equivalent API and subscribed to receive future events.
>
> I don't quite understand this point. The key thing from my perspective is
> that when the only way to get access to a property value is to make an
> active request, then the browser knows each time it is accessed, and has an
> opportunity to monitor for abuse. But when you can instead get access to it
> by subscribing (which is what CH is), and this is the preferred modality,
> then it's not really possible to monitor for abusively high request levels.
>
> I agree that Client Hints is equivalent to subscribing to an active
> fingerprinting vector. E.g. the Viewport CH is very similar in that way
> to [MediaQueryList](
> https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList). JS code
> doesn't have to actively poll for MQ changes, but can get notified for
> them. I'm assuming that if developers have registered for that info, each
> time they'd get notified for it would be considered an "active request" for
> that information, and would be monitored for abuse. Similarly, browsers
> could track every time a CH value change is sent to the server and consider
> it an "active request" for that information for abuse tracking purposes.
> Does that make sense?
>
No, because if this is the default way in which people get this information
then you can't distinguish between abuse and non-abuse.

Again, the abuse monitoring is about looking ad the number of times and the
context in which the site asks for the info, but in this case abuse and
non-abuse will look identical.


I don't really see how this is going to work. The hints become problematic
> if you omit them or lie.
>
> In what way? The hints should be built as a progressive enhancement, and
> browsers which would omit or lie about them can make sure that adopting
> sites actually treat them like that.
>
I'm not following. The point of the hint is lost if you lie, and so there's
an incentive not to.


> For example, consider the case of PeerConnection. As we know, this has
> high fingerprinting potential (due to IP disclosure) and so sites routinely
> creating PCs for no reason is a marker of abuse. Of course there are sites
> which have legitimate uses of PC, but they might *also* be fingerprinting
> you. At present, we can distinguish these by looking to see when they
> create PCs, but if we were to replace PC by a hypothetical "host IP
> address" Client Hint, then it would not be possible to distinguish sites
> which are both legitimate PC users and fingerprinters from sites which are
> legitimate PC users and not fingerprinters. How does the browser "treat
> registration as if..." usefully?
>
> I don't really understand this example, but maybe it requires more
> knowledge about how PC is used for fingerprinting. Is there fingerprinting
> "value" in revealing the user's IP more than once? How do browsers
> distinguish legitimate from abusive usage today?
>
We typically do it via crawling and looking for what looks like abuse. See,
for instance,
http://randomwalker.info/publications/OpenWPM_1_million_site_tracking_measurement.pdf

**Comment by mikewest** [comment]
Hey folks! I'm skimming through this thread with https://github.com/WICG/ua-client-hints/ in mind, as it's something I'd like Chrome to continue pushing forward (also https://github.com/WICG/lang-client-hint/, but that turns out to be a bit more difficult given its usage).

In the UA use-case, browsers are broadcasting the value as an HTTP header on every request, which I think we would all agree enables completely passive fingerprinting. The CH infrastructure gives us a path towards requiring sites to affirmatively ask for details above and beyond the brand/version (either via CH or via the JS API), which would make usage visible to mechanisms like OpenWPM and browsers themselves. That seems like a strict improvement over the status quo. Would y'all disagree?

@ekr: With regard to more traditional hints, I think you're correct to state that forcing information requests through JS APIs currently gives you more insight into the ways in which that information is used by a given application. I think you're also correct to say that CH removes the necessity to ask for a given bit of information on an ongoing basis. This means that fundamentally dual-use APIs will be more difficult to categorize if the work can be pushed to an opaque backend server.

That said, it seems likely that this is what we'll end up with in the not-so-distant future, as there are certainly incentives to reduce the number of times information is gathered in a world where it's well-known that those requests feed into a behavioral model for a given page. I talked with @yoavweiss about a model which would require a page to more persistently opt-in. Would a model in which `Accept-CH-Lifetime` would be dropped if the next navigation didn't include the relevant `Accept-CH` header, be interesting? That would give you more or less the same page-level detail about data being explicitly requested.

**Comment by yoavweiss** [comment]
> abuse and non-abuse will look identical

Can you clarify what you consider abusable values and if any of the current hints fall into that category? (i.e. viewport width, DPR, image width, network RTT, BW, and effective type, data saving preference, UA string information or Accept Language information)
If not, is this a concern about potential future values?

I'm trying to understand if the concern is exposing bits in a larger fingerprinting map, or something more directly abusable (e.g. the theoretical local IP address case you raised before).

 

> We typically do it via crawling and looking for what looks like abuse

Is that at runtime in the browser, or something done ahead of time? (the use of "crawling" here confused me, so trying to clarify)

**Comment by yoavweiss** [comment]
This was [discussed](https://github.com/httpwg/wg-materials/blob/gh-pages/ietf105/minutes.md#10-min---client-hints---yoav-weiss) at the IETF 105 HTTPWG meeting, and I believe we have a path to resolution here. (although the minutes don't really capture the subtleties)

@martinthomson - I believe you wanted we'd add some language around the criteria for features that might be able to use client hints, to make sure we capture the range of possible information exposure (from "clamping down User-Agent string" on one hand of the spectrum, and geolocation headers on the other). I'll take a stab at doing that and send to you for review.

**Comment by yoavweiss** [comment]
Closed by #879
