### ISSUE TITLE
Parameterised Identifier -> Parameterised Item?

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#797]
in [Signed Exchanges](https://tools.ietf.org/html/draft-yasskin-http-origin-signed-responses-05#section-3.1.2), @jyasskin asks about having Parameterised Lists whose parameterised identifiers are things other than Tokens. 

Because of the way SH is put together, I think this would be a fairly easy change, in terms of the spec and implementations; it would require a few more tests.

The only downside I can think of immediately is that specs would need to constrain the type of the parameterised identifier themselves, and specify error handling (if it weren't the default "blow up").

Thoughts?

I also wonder if we should come up with a better name than "parameterised identifier", especially since we've ditched "identifier" elsewhere. _member name_? _member id_? _primary identifier_?

**Comment by phluid61** [comment]
That works, since splitting lists from parameterised lists.  Are you thinking `primary-id = sh-item`, or just adding a few types?

It also changes my thinking a tiny bit on #782 , although not much.

> I also wonder if we should come up with a better name than "parameterised identifier", especially since we've ditched "identifier" elsewhere. _member name_? _member id_? _primary identifier_?

I like "parameterised element" but that introduces a new word. "parameterised item" is a nice shade, if any item is allowed there, but "primary identifier" works too. :art: :paintbrush:

**Comment by mnot** [comment]
The downside here is that it would be very hard to represent in JSON -- e.g., in the [test suite](https://github.com/httpwg/structured-header-tests). At least some programming languages support hashes/dictionaries/objects with arbitrary key types (e.g., Python, JavaScript, Ruby), but I'm not sure how widespread that is -- especially if folks represent the different between `token` and `string` with an object for `token`.

@jyasskin is this a nice-to-have or something that's a blocker?

**Comment by mnot** [comment]
(Fwiw I do think we should call this a Parameterised Token)

**Comment by phluid61** [comment]
> The downside here is that it would be very hard to represent in JSON -- e.g., in the [test suite](https://github.com/httpwg/structured-header-tests).

At this point do we just have to accept that the SH data model is essentially a subset of the JavaScript model?  Numbers are bounded by JavaScript's limitations, object keys have to be stringy, nobody likes 'token' because it isn't a native JS type...

I don't mind if that's the case, but it would be good to just say it outright somewhere.  It would also give us a solid position to start from when considering other proposals.

> At least some programming languages support hashes/dictionaries/objects with arbitrary key types (e.g., Python, JavaScript, Ruby), but I'm not sure how widespread that is -- especially if folks represent the different between `token` and `string` with an object for `token`.

Hmm, C++ and Go could be have issues mixing key types within a single map, and Perl is definitely not going to like non-string keys.

**Comment by mnot** [comment]
It doesn't have to be -- it's just easier for me to write tests this way :)

**Comment by jyasskin** [comment]
This was a nice-to-have for me. I’d worked around it by putting an unused string as the identifier. It looks like that workaround is no longer necessary? 😃
