### ISSUE TITLE
tls_unexpected_peer_certificate details

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#819]
This field uses `details` for a specific purpose, but that's already in the generic parameters. Suggest `cert_id` or similar. 

/cc @PiotrSikora

**Comment by PiotrSikora** [comment]
Looks like `tls_unexpected_peer_identity` has the same issue. Should we use `cert_id` for both?

Note that the identifier is context-based, since if proxy configured SHA256-based validation, then `cert_id` would be `SHA256(peer_certificate)`, if it configured SPKI-based validation, then `cert_id` would be `SPKI(peer_certificate)`, etc.

We could also use `sha256` and `spki` instead of `cert_id` (and `identity` for  `tls_unexpected_peer_identity`), but that doesn't seem very future-proof.

What do you think?

**Comment by mnot** [comment]
Hmm, that's awkward. Maybe two fields? E.g.,
  * `validation_type`: [`sha256`, `spki`... ]
  * `cert_id`: ...

Is there a registry we can refer to, maybe?

**Comment by PiotrSikora** [comment]
I'm afraid that there isn't any registry that we can refer to, at least none that I know of.

`validation_type` (opaque type) and `cert_id` (opaque value) seem a bit awkward. Wouldn't it be easier to just have `sha256` and `spki` params?

Also, in Envoy, we actually configure list of acceptable `sha256` and `spki` values, and matching against any of them works, so we should probably emit both of them anyway.

I could envision merging `tls_unexpected_peer_certificate` and `tls_unexpected_peer_identity` into a single status type `tls_unexpected_peer_certificate` that lists all 3 params, e.g.
`tls_unexpected_peer_certificate; sha256=xxxx; spki=aaaa; identity=backend.local`

See #864.

What do you think?

**Comment by mnot** [comment]
Better than what we had :)
