### ISSUE TITLE
Considering http_response_status

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#821]
All proxy status types share a property; they indicate that the response was generated by a proxy, rather than the origin. This is useful; it allows a recipient to know not only that, but where it _was_ generated (by inspecting `proxy`).

However, there is one exception -- `http_response_status` is explicitly decorating a response that's been forwarded by the origin. 

Besides the _one-of-these-things-is-not-like-the-others_ factor, I suspect this is going to trip some folks up, because they'll log or otherwise act on the presence of the header field with an understanding of "this response was generated by a proxy, not by the origin." Since it's a debugging tool, that's especially concerning.

I think this could be addressed by moving those use cases into a new header field (still defined by this document; e.g., `Proxy-Info`), but I'm open to other approaches.

@PiotrSikora I know you had use cases around this, so would be very interested in your take.

**Comment by mnot** [comment]
(also cc @alyssawilk)

**Comment by PiotrSikora** [comment]
This status type has two major use cases:

1) It explicitly states that the status code and response body were generated by the next hop and not by the proxy.
e.g. Can you tell whether this response was generated by the proxy (which may or may not support `Proxy-Status`) or by the backend?
```
HTTP/1.1 503 Service Unavailable
Date: Tue, 02 Jul 2019 11:33:08 GMT
Server: someproxy
```
Compare with:
```
HTTP/1.1 503 Service Unavailable
Date: Tue, 02 Jul 2019 11:33:08 GMT
Proxy-Status: http_response_status; proxy=foocdn
Server: someproxy
```

2) It acts as a `traceroute` for proxies.
```
HTTP/1.1 502 Bad Gateway
Date: Tue, 02 Jul 2019 11:33:08 GMT
Proxy-Status: http_response_status; proxy=foocdn,
              http_response_status; proxy=example.com,
              tls_rejected_proxy_certificate; proxy=lb-us-west
Server: someproxy
```

Notably, in both of those use cases, this status type gets more useful the less familiar you are with the proxy chain that you're dealing with. i.e. it doesn't provide too much benefit if you consider `Proxy-Status` only as an "edge" header to be emitted by CDNs, but once you consider that origins can emit those as well, and that you can see the route that the request took outside of your product/organization, it becomes really useful.

> Besides the one-of-these-things-is-not-like-the-others factor, I suspect this is going to trip some folks up, because they'll log or otherwise act on the presence of the header field with an understanding of "this response was generated by a proxy, not by the origin." Since it's a debugging tool, that's especially concerning.

Well, that really depends on how we're going to present this feature :), and how is it going to be implemented in the open-source proxies and major CDNs.

If they are going to append `Proxy-Status` at each hop (`traceroute` / reverse `Forwarded`), then I don't think anybody is going to be confused by this "special" type. On the other hand, if `Proxy-Status` is going to be used primarily as an "error indicator", then yes, we might want to migrate this status type and `proxy_internal_response` (#807) elsewhere.

Perhaps we should mandate one or the other?

cc @ghedo, since he expressed interest in deploying this at Cloudflare.

On a separate note, it isn't obvious (to me) what happened from just looking at the status type name, perhaps `http_response_forwarded` would be a bit more descriptive? What do you think?

**Comment by mnot** [comment]
I agree this is an interesting and important use case -- I just want to talk about how we're expressing it in the protocol.

My preference would be to keep `Proxy-Status` confined to responses that are generated by the proxy, to make it crystal clear when that is happening. To serve this use case, I'm thinking we could use a different header, something like `Proxy-Info`; e.g.,

~~~
Proxy-Info: node="fooProxy", nextHop="barOrigin", latency=525
~~~

Note that this lets us migrate some of the generic parameters over, because they don't apply to just error responses.

That would make your example above:

~~~
Proxy-Info: node="foocdn",
            node="example.com",
            node="lb-us-west"
Proxy-Status: tls_rejected_proxy_certificate; node="lb-us-west"
~~~

WDYT? To me this is better, because it's really clear that the status is generated by a proxy. After all, the most common case is going to be normal, non-error operation, which means that we avoid a lot of repeating `http_response_status` to scan through; i.e., it'll look like:

~~~
Proxy-Info: node="foocdn",
            node="example.com",
            node="lb-us-west"
~~~

**Comment by mnot** [comment]
@PiotrSikora please see #843 for a rough idea of what this would look like; still needs a fair amount of cleanup and obviously we'd want to think about more information types, but you can get the idea.

**Comment by martinthomson** [comment]
At some point we're going to need a map to explain how all these intermediation header fields contribute: Cache-Status, Via, Proxy-Status (or Proxy-Error), Proxy-Info, CDN-Loop, et al all provide value independently, but navigating all of this is hard.

**Comment by alyssawilk** [comment]
From a user-perspective where the desire is to know where the response came from, I'd prefer as few sources of truth as possible.  Splitting into proxy-status and proxy-info seems like a step back in that regard as compared to the traceroute style trace in Piotr's example.  

Additionally, I think there's also a range of generated responses from responses fully generated by a proxy to responses fully proxied from another source, where one might for example, get instructions and partial headers and/or data from a side-car and synthesize a response from that.  In a world with user-defined headers and body transformations and lua/wasm filters operating on responses I'm not sure it's going to be easy to divide things into two buckets of "internally generated response" and "not"

**Comment by mnot** [comment]
@PiotrSikora PTAL - https://httpwg.org/http-extensions/draft-ietf-httpbis-proxy-status.html

If we like this direction, I think the next step is to define some more parameters for other aspects that intermediaries might want to talk about...

**Comment by mnot** [comment]
@PiotrSikora ping? I'm inclined to publish this as-is for discussion in Vancouver...

**Comment by mnot** [comment]
Submission deadline is tomorrow, so I'm going to go ahead and submit, but not close this so we can continue discussion.

**Comment by LPardue** [comment]
FWIW the deadline is 2020-03-**09**, so one more week

**Comment by mnot** [comment]
Closing, we can always open more!
