### ISSUE TITLE
Should the obsolescence of MD5 be stronger?

### ISSUE THREAD

**Issue by tfpauly** [httpwg/http-extensions#867]
While it is great that SHA-1 and MD5 are being obsoleted, there are cases in which MD5 is a MUST NOT (and SHA-1 is on track to that, but not there yet). For example, IPsec marks it a MUST NOT: https://tools.ietf.org/html/rfc8221#section-6.

If the state of things is such that we can't reasonably say MUST NOT, can we have text that gives indication of the future of this algorithm's usage?

**Comment by LPardue** [comment]
@ioggstream from your experience in actual digest usage would strong obsolescence 
cause issues?

**Comment by ioggstream** [comment]
The original discussion was something like:

- MUST NOT in signatures;
- NOT RECOMMENDED on the rest, so we retain backward compatibility.
  It's fine to me to MUST NOT, providing a suitable way to report it in the iana table.

**Comment by LPardue** [comment]
As another datapoint, RFC 8221 also says:

> It is expected that deprecation of an algorithm be performed
   gradually.  This provides time for various implementations to update
   their implemented algorithms while remaining interoperable.  Unless
   there are strong security reasons, an algorithm is expected to be
   downgraded from MUST to MUST- or SHOULD, instead of MUST NOT (see
   Section 2).  Similarly, an algorithm that has not been mentioned as
   mandatory-to-implement is expected to be introduced with a SHOULD
   instead of a MUST.

I don't believe our intention is to make the Digest header document something that is continually updated. There a gradual approach may not be suited to our goals.

**Comment by ioggstream** [comment]
If there's consensus on `MUST NOT`, I'd go for it. 
We could use RFC8221 as a reference.

**Comment by LPardue** [comment]
Also, at IETF 105 "[Deprecating MD5 and SHA-1 signature hashes in TLS 1.2](https://datatracker.ietf.org/doc/draft-lvelvindron-tls-md5-sha1-deprecate/)" was adopted by the TLS working group. 

Given the general community direction, I think a stronger MUST NOT is acceptable.

**Comment by ioggstream** [comment]
Ok. Here is for completeness the original thread https://github.com/ioggstream/draft-polli-resource-digests-http/issues/16

**Comment by ioggstream** [comment]
Do we want to "MUST NOT" even sha-1 ?

**Comment by ioggstream** [comment]
Preliminary patch here. #875

**Comment by tfpauly** [comment]
@ioggstream Yes, that looks great! 

To your other question, my impression is that deprecating SHA-1 is probably less advisable at this point, but if someone has further information, I'd love to hear it.
