### ISSUE TITLE
Serialisation of Floats

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#896]
... is currently unrealistic; it rejects values that have too much precision, which is going to be difficult to handle in many implementations.

**Comment by phluid61** [comment]
So, what do?

1. leave it; accept that sh-float is not the same as double-precision 64-bit binary format IEEE 754
2. make it a lot closer to '', and come up with a different serialisation
3. drop floats (for now)

Option 1 will cause pain for the rest of forever, because I know that nobody cares about that sort of thing, they'll just want to `sprintf("%f")` their `double`.

Option 2 interests me (hex with a dot? explicit exponent and significand parts? something else?) but probably nobody else.  I'm sure people would love to see numbers like `-0xC.90FEp-2` in their HTTP headers.  Let alone having to convert them to/from JS numbers.

Option 3 feels bad, but maybe it's easier?  Are any of the known/impending uses of SH going to notice the absence?

**Comment by phluid61** [comment]
Perhaps there's a 1.b: an algorithm for converting a double to an sh-float (or phrased another way: an algorithm for serialising a double) that includes a consistent, reliable rounding strategy.

**Comment by mnot** [comment]
I think we just need to remove the "fail serialisation" step for the fractional component, and then enforce it in the actual serialisation.

**Comment by mnot** [comment]
(and truncate, not round)

**Comment by phluid61** [comment]
:thinking: . o O ( round-towards-zero or round-towards-negative-infinity..? )

**Comment by mnot** [comment]
"If the fractional component has more than six digits of precision, truncate it after the first six digits."

**Comment by phluid61** [comment]
Kinda weird if `0.1234567` becomes `0.123456` and is ok, but `1234567890.1234567` becomes `1234567890.123456` and isn't.

**Comment by mnot** [comment]
Why is that weird? It sounds like you're experiencing regret about the current approach to limiting floats...

**Comment by phluid61** [comment]
It's not a blocker. It just feels weird that it truncates at 6 digits whether or not that's the appropriate number.  So some numbers with >6 digits of precision will truncate fine, but others won't.

**Comment by mnot** [comment]
PTAL
