### ISSUE TITLE
SameSite attribute is not easily extensible

### ISSUE THREAD

**Issue by sbingler** [httpwg/http-extensions#933]
If we add a new attribute to SameSite (e.g. previously we added SameSite=None and [draft-west-cookie-samesite-firstparty-01](https://tools.ietf.org/html/draft-west-cookie-samesite-firstparty-01) proposes SameSite=FirstPartyLax and FirstPartyStrict), site owners will need to get the right behavior on both old and new UAs. The current specification (-03) makes this difficult because all unknown values as parsed as “None” (or “Lax” after [draft-west-cookie-incrementalism-00](https://tools.ietf.org/html/draft-west-cookie-incrementalism-00#section-3))

If unknown values were instead ignored, older UAs would fallback onto an earlier declaration, while newer ones would get the new behavior.

For instance, a site using FirstPartyStrict could fallback to None, to keep cookies accessible in older browsers, with SameSite=None; SameSite=FirstPartyStrict.

Alternatively, the site may wish to fallback to Strict, preferring the tighter CSRF protection, via SameSite=Strict; SameSite=FirstPartyStrict.

If we added, say, a StrictOnOrigin mode which used same-origin instead of same-site, a site might use SameSite=Strict; SameSite=StrictOnOrigin.

Interestingly, the [draft-02](https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-02#section-5.3.7) does this, however [draft-03](https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-03#section-5.3.7) changed this to unconditionally take the last attribute. Firefox implements -02 while Chrome implements -03 (@chlily1, @martinthomson, @mikewest). Whichever option we choose, we should make sure implementations align.

Below are findings comparing how a variety of UAs, along with the above drafts, interpret different combination of SameSite attributes. (@johnwilander, which did you all implement for the new Safari behavior?)

All UA results were taken from each UA's dev tools.

| SameSite Attribute | Draft 02 | Draft 03 | Draft 03 + Inc | Chrome 77 | Firefox 69 | Safari OS X 10.14 |
|-----------------------------------|----------|----------|----------------|-----------|------------|-------------------|
| " | Unset | Unset | Lax | Unset | Unset | Unset |
| SameSite=garbage | Unset | None | Lax | Unset | Unset | Strict |
| SameSite=garbage; SameSite=None | Unset | None | None | None | Unset | Strict |
| SameSite=garbage; SameSite=Lax | Lax | Lax | Lax | Lax | Lax | Lax |
| SameSite=garbage; SameSite=Strict | Strict | Strict | Strict | Strict | Strict | Strict |
| SameSite=None; SameSite=garbage | Unset | None | Lax | Unset | Unset | Strict |
| SameSite=Lax; SameSite=garbage | Lax | None | Lax | Unset | Lax | Strict |
| SameSite=Strict; SameSite=garbage | Strict | None | Lax | Unset | Strict | Strict |
| SameSite=Lax; SameSite=None | Lax | None | None | None | Unset | Strict |

**Comment by sbingler** [comment]
For those interested in recreating the results, here is the code used:
```
document.cookie = "no_samesite=1";
document.cookie = "garbage=1; samesite=garbage";
document.cookie = "garbage_none=1; samesite=garbage; samesite=none";
document.cookie = "garbage_lax=1; samesite=garbage; samesite=lax";
document.cookie = "garbage_strict=1; samesite=garbage; samesite=strict";
document.cookie = "none_garbage=1; samesite=none; samesite=garbage";
document.cookie = "lax_garbage=1; samesite=lax; samesite=garbage";
document.cookie = "strict_garbage=1; samesite=strict; samesite=garbage";
document.cookie = "lax_none=1; samesite=lax; samesite=none";
```

**Comment by mikewest** [comment]
@sbingler, @davidben, @chlily1, and I chatted about this last week.

My current opinion is that https://tools.ietf.org/html/draft-west-cookie-samesite-firstparty-01 is misguided, and that extending `SameSite` further is not going to be the right way to make further changes to cookies. I think it's quite reasonable to ensure that implementations land on a consistent story with regard to garbage values for `SameSite`, but I don't think it's important for us to make room for extension to the currently accepted values.

I feel like there are reasonable arguments for both Chrome's current behavior and Firefox's current behavior. I don't have a strong reason to pick one or the other. Perhaps it's simplest for Chrome to match Firefox's behavior by simply ignoring cookies that assert `SameSite=garbage`? Is that the outcome you'd prefer, @sbingler?

**Comment by davidben** [comment]
I believe Firefox's behavior is that it ignores the attribute when `SameSite=garbage` (falling back to a previous one, if any). That's the -02 behavior, rather than the -03 behavior, which unconditionally takes the last one attribute (so no falling back to a previous one) and *then* ignores unrecognized ones.

I believe Chrome and Safari (as of 10.15) implement the -03 behavior, while Firefox implements the -02 behavior. If we were trying to extend `SameSite`, I think the -02 behavior would be ideal because it gives the developer full control over the fallback chain. That would requiring changing Chrome as well as the macOS/iOS cookie logic again. Failing that, leaving rfc6252bis alone but changing cookie-incrementalism to treat `SameSite=garbage` as `SameSite=None` rather than the default would cover the most likely desired fallback when trying to extend `SameSite`.

That said, I agree with you that we probably shouldn't try to extend `SameSite` anymore, so trying to optimize for that is not terribly important.

Whatever happens, at least one of Chrome+Safari or Firefox should change because they do not behave the same. As things currently stand, it's Firefox that's out of date, since they implement the -02 behavior rather than the -03 behavior.

**Comment by englehardt** [comment]
Modifying https://github.com/httpwg/http-extensions/issues/933#issuecomment-532888081 to include `Secure`:

```
document.cookie = "no_samesite=1; Secure";
document.cookie = "garbage=1; samesite=garbage; Secure";
document.cookie = "garbage_none=1; samesite=garbage; samesite=none; Secure";
document.cookie = "garbage_lax=1; samesite=garbage; samesite=lax; Secure";
document.cookie = "garbage_strict=1; samesite=garbage; samesite=strict; Secure";
document.cookie = "none_garbage=1; samesite=none; samesite=garbage; Secure";
document.cookie = "lax_garbage=1; samesite=lax; samesite=garbage; Secure";
document.cookie = "strict_garbage=1; samesite=strict; samesite=garbage; Secure";
document.cookie = "lax_none=1; samesite=lax; samesite=none; Secure";
```

I re-ran these tests on more recent versions of Firefox and Chrome, and compared the the draft text in #1325.

SameSite Attribute | #1325  |  Firefox 84 (Nightly) | Chrome 88
--- | --- | --- | ---
SameSite=garbage | Default | Lax | Unset
SameSite=garbage; SameSite=None | None | None | None
SameSite=garbage; SameSite=Lax | Lax | Lax | Lax
SameSite=garbage; SameSite=Strict | Strict | Strict | Strict
SameSite=None; SameSite=garbage | Default | None | Unset
SameSite=Lax; SameSite=garbage | Default | Lax | Unset
SameSite=Strict; SameSite=garbage | Default | Strict | Unset
SameSite=Lax; SameSite=None | None | None | None

**Comment by englehardt** [comment]
Firefox is now aligned with Chrome and Safari here in only parsing the final SameSite attribute, even if it is invalid and proceeded by a valid attribute. See [Bug 1682450](https://bugzilla.mozilla.org/show_bug.cgi?id=1682450). I've also added web platform tests https://github.com/web-platform-tests/wpt/pull/26978.

**Comment by englehardt** [comment]
I agree with @mikewest's sentiment that extending samesite does not feel appropriate. We chose to align with Chrome (rather than suggest Chrome/Safari align with us) because all other key-value cookie attributes only consider the final attribute.

@mnot @mikewest Given that we now have alignment between Chrome, Firefox, and Safari to only parse the final attribute I think we can close this issue.
