### ISSUE TITLE
Top-level serialise

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#984]
... is written as if you can infer the header type from the type of the input data. That isn't true any more; we probably need something like the parse algo's concept of `header_type`.

**Comment by phluid61** [comment]
Feels like you're edging towards specifying an API.  You _can_ infer header if the types defined in the spec are real bona fide types.  And the mapping between $LANG's array type and SH's List is an API choice.

**Comment by mnot** [comment]
Yes; right now we have this uneasy balance between the two, and it's muddy. I think we need to specify unambiguously while allowing it to be surfaced in different ways.

**Comment by mnot** [comment]
oops

**Comment by phluid61** [comment]
I keep mulling over what it would take to define them as actual types, like specifying the sorts of operations that can be performed on them.  For the most part I think it would just add a lot of text for stuff that seems obvious (integers support arithmetic operations 🤔) but it might be worthwhile?

Maybe just giving them silly trademarkable names, like SHList and SHInteger, could help.

**Comment by phluid61** [comment]
I realise that having the spec say "If the value is an SHToken.." doesn't help you map your native string one way or another, but it might highlight that you need to explicitly build that mapping.

**Comment by bsdphk** [comment]
We discussed the "point blank parsing" issue a fair bit long time ago, and I think the conclusion was that it would have to be (header-)syntax directed parsing in most cases, and that the few cases which were not (presumably debugging) could live with a back-tracking parsing algorithm.

With respect to defining SH elements as actual types:  Please Dont, it would add a lot of text for no discernable benefit to anybody.

**Comment by phluid61** [comment]
This isn't the parsing issue.  Given a (native) string, how do you know whether to serialize it as a token, string, or binary?  It's not just a matter of assuming token and then 'upgrading' every time you hit an illegal character – native `"xy"` could legitimately become `xy`, `"xy"`, or `*eHk=*`.

Looking at it from the parser side, **Parsing a Token** says:

```
Given an ASCII string as input_string, return a token.
[...]
2. Let output_string be an empty string.
[...]
4. Return output_string.
```

So is it saying that a token is a string?  Because the algorithm for parsing a string says roughly the same thing.  If **Parsing an Item** emits `["foo", {}]` as a tuple, there's no way to tell if that _foo_ was a token or a string. What the parser emits should be enough to feed into the serialiser (although not vice versa).

**Comment by mnot** [comment]
See commit; I think this addresses the issue in the most minimal way possible.
